### ISSUE TITLE
au-prescription; no examples present in identifier.value

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#109]
Hi Brett,
This applies to both _identifier_ slices - please include examples in Description & Constraints column for _identifier.value_ in both slices

**Comment by oridashi** [comment]
these are system assigned identifiers - i don't think we should get some real system owner examples; i am going to hold this over until a later version

**Comment by dbojicic-agency** [comment]
@dtr-agency, no, identifier slices have been replaced with data type profiles.
