### ISSUE TITLE
Feature - Adding AHPRA identifier slice to AustralianPractitionerRole

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#11]
@oridashi has requested an AHPRA identifier slice to added to the [AustralianPractitionerRole](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html).
Query whether to use MD - Medical License Number in http://hl7.org/fhir/v2/0203/index.htm, but as AHPRA is used for nurses, so query whether creating an "AHPRA" code in http://hl7.org.au/fhir/v2/0203/index.htm.
Awaiting details from AHRPA on the format on the number ie length, content and check digits etc.

**Comment by oridashi** [comment]
need to allocate a system url

**Comment by robeastwood-agency** [comment]
Following email discussion with AHPRA about the format of the number, a value constraint can be added to the profile (3 uppercase characters followed by 10 digits). This has been drafted in PR #16.

Have also sought a namespace uri from our AHPRA contact, via email.

**Comment by oridashi** [comment]
hl7.org.au domain system url applied to prevent validation errors on discriminator
