### ISSUE TITLE
FHIRPath invariant :: au-patient :: inv-dva-number-unspecified and inv-dva-number-{other 4}

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#110]
Hi Brett,

- Can you please check if the invariant at the following link 
https://github.com/hl7au/au-fhir-base/blob/54c1700bec247d839c53b807f2c9c3f101266564/resources/au-patient.xml#L317

type.coding.exists() and type.text != 'DVA Number' 
is doing what the statement states: 
"DVA Number identifier type text must be 'DVA Number' when colour is not specified"

As it seems to be working differently to me.

- Similarly about inv-dva-number-gold, inv-dva-number-lilac, inv-dva-number-orange, inv-dva-number-white

Thanks.
Vikas

**Comment by RichardTON** [comment]
Some proposed changes
Replace 
inv-dva-number-gold: DVA Number identifier type text must be 'DVA Number (Gold)' when colour coding is DVG (: type.coding.code='DVG' and type.text != 'DVA Number (Gold)')
with one of the following
1/ inv-dva-number-gold: When colour code is DVG the identifier type is 'DVA Number (Gold)' (: type.coding.code='DVG' implies type.text = 'DVA Number (Gold)')

2/ inv-dva-number-gold: Colour code is DVG when and only when the identifier type is 'DVA Number (Gold)' (: (type.coding.code='DVG' implies type.text = 'DVA Number (Gold)') and (type.text = 'DVA Number (Gold)') implies type.coding.code='DVG')

3/ inv-dva-number-gold: Colour code is DVG when and only when the identifier type is 'DVA Number (Gold)' (: type.coding.code='DVG' xor type.text != 'DVA Number (Gold)')

I believe that 2 and 3 be different fhirpath experessions with the same tructh conditions.equivalent

**Comment by oridashi** [comment]
updated the DVA invariants along these lines
