### ISSUE TITLE
Practitioner example - AHPRA content using old identifer slice structure

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#111]
The early iteration of structure for AHPRA registration number content was based on a discrete identifer slice. More recently, the AHPRA number has moved to being represented in the qualification node instead.

The sole example for practitioner has an AHPRA number but it is within the outdated identifer structures - see [these lines](https://github.com/hl7au/au-fhir-base/blob/master/examples/practitioner-example0.xml#L27-L38). The AHPRA number needs to be updated to reflect this new qualification structure.

**Comment by oridashi** [comment]
fixed
