### ISSUE TITLE
Is identifier.system value in PBS Manufacturer Organisation correct?

### ISSUE THREAD

**Issue by dbojicic** [hl7au/au-fhir-base#114]
identifier.system has fixed value of "http://pbs.gov.au/identifier/manufacturer"
Is this the correct value? The actual page cannot be found. 
Description & Constraints column says this is a placeholder URL: "PBS manufacturer (placeholder URL)"

**Comment by oridashi** [comment]
I have converted this to 
http://pbs.gov.au/code/manufacturer -this matches the url used in PBS V3 xml format publication

**Comment by oridashi** [comment]
I think this is the right URL to use although it is an identifier in this usage - this matches what PBS uses and has the same definition as they use
