### ISSUE TITLE
PBS Manufacturer Organisation identifier

### ISSUE THREAD

**Issue by dbojicic** [hl7au/au-fhir-base#116]
Is it possible to have a PBS manufacturer organisation that does not have a PBS assigned identifier? 
The profile currently allows for this with the identifier/PBS identifier slice being optional.
How is this profile different from the base organisation profile that would also allow for a PBS manufacturer organisation? What are the attributes of a PBS manufacturer organisation that are different to other organisations - would this be a PBS assigned identifier (two letter code as in https://www.pbs.gov.au/browse/manufacturer-list)?
Suggest update the PBS identifier slice cardinality to 1..1.

**Comment by oridashi** [comment]
yes - change made

**Comment by dbojicic** [comment]
Thanks Brett, that was quick :)
I am still confused as to why we need a separate profile for a PBS manufacturer organisation and not just organisation that has an identifier slice for PBS code? I think if we want two different profiles then the identifier in PBS Manufacturer Organisation profile should be mandatory too. Otherwise we can just add another slice to the AU Base Organisation profile with some guidance text possibly?

**Comment by oridashi** [comment]
I made it mandatory identifier and only allow PBS Sponsor (Manufacturer) in the extension - so think that covers it?

**Comment by dbojicic** [comment]
that's better, thank you

**Comment by oridashi** [comment]
will call this done for now
