### ISSUE TITLE
"General:123456" shown as Example

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#118]
Hi Brett,

The definitions page of the profiles e.g. http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient-definitions.html has the following text in the Examples --- “**General:123456**”
I am not able to figure out where it is coming from so that I can fix it, is it some tooling issue?

Cheers,
Vikas

**Comment by oridashi** [comment]
I can't see why this happens; not from the core specs either... better check this one on zulip

**Comment by vikasmittal-dh** [comment]
Right Brett. Will do. Thanks.

**Comment by oridashi** [comment]
believe this is a snapshot generator issue - should raise ticket as tooling issue on HL7 international GForge

**Comment by robeastwood-agency** [comment]
Checking a number of HL7 Au profiles and noticed this issue is still apparent.

**Comment by vikasmittal-dh** [comment]
Created a jira ticket 
https://jira.hl7australia.com/browse/PA-25 

Thus closing this issue.
