### ISSUE TITLE
Feature - Adding employee number identifier slice to AustralianPractitionerRole

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#12]
@oridashi has requested an employee number identifier slice to added to the [AustralianPractitionerRole](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html).
Use the code "EI" Employee number in http://hl7.org/fhir/v2/0203/index.htm.

**Comment by oridashi** [comment]
closed completed
