### ISSUE TITLE
FHIRPath invariant :: au-organisation:: identifier.value length

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#124]
Hi Brett,

In the following three invariants at
http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-organisation-definitions.html

- inv-asic-abn-length (type.coding.code='ABN' and value.length()=11)
- inv-asic-acn-length (type.coding.code='ACN' and value.length()=9)
- inv-asic-arbn-length (type.coding.code='ARBN' and value.length()=9)

the invariant uses "type.coding.code". 

Do you think it shall be "type.text" in place of "type.coding.code" ?

Thanks.
Vikas

**Comment by brianpos** [comment]
If anything, I'd be suggesting a change to check the **system** on the identifier

**Comment by vikasmittal-dh** [comment]
That is right Brian. As system is unique and mandatory, it will be much better.

**Comment by oridashi** [comment]
think only length check is needed - the system is already fixed and there is no type.coding.code at all defined
