### ISSUE TITLE
Au Dispense Record; identifier slices

### ISSUE THREAD

**Issue by dbojicic** [hl7au/au-fhir-base#129]
Hi Brett
Just looking at the identifier slice 'Local Script Number' that is almost identical to the Local Prescription slice in the AU Prescription. I might be completely wrong here but would not a dispense record be identifier by a 'local dispense record number' and there could be multiple dispenses for the same prescription number (local prescription number if one exists, or as in authorisingPrescription.identifier)?

**Comment by oridashi** [comment]
this is now changed to Local Dispense Identifier for dispense record; prescription numbers should be in MedicationRequest only
