### ISSUE TITLE
PBS Manufacturer Organisation - identifier is still optional

### ISSUE THREAD

**Issue by dbojicic** [hl7au/au-fhir-base#135]
_identifier_ element is still optional with mandatory PBS Sponsor identifier slice. 
Brett, did we agree to make _identifier_ mandatory as well? This way the profile still does not offer anything over the base Organisation profile that could have a PBS code slice and an invariant/guidance on how to use for PBS Manufacturer Organisation.

**Comment by oridashi** [comment]
have set the cardinality but this does not appear in the IG output... will follow this up as an IG publisher question
