### ISSUE TITLE
Extension URL's not resolving

### ISSUE THREAD

**Issue by udaychandrupatla** [hl7au/au-fhir-base#138]
Hello Brett, 

Below URL's which exist in extension description page do not seem to resolve when one copies and pastes in a browser.
e.g.
![image](https://user-images.githubusercontent.com/32316167/45004422-bd427200-b02f-11e8-9503-b6db4edadc6d.png)

- http://hl7.org.au/fhir/StructureDefinition/attester-related-party
- http://hl7.org.au/fhir/StructureDefinition/section-author
- http://hl7.org.au/fhir/StructureDefinition/information-recipient
- http://hl7.org.au/fhir/StructureDefinition/composition-author-role
- http://hl7.org.au/fhir/StructureDefinition/dispense-number
- http://hl7.org.au/fhir/StructureDefinition/medication-long-term
- http://hl7.org.au/fhir/StructureDefinition/medication-batch-serialnumber
- http://hl7.org.au/fhir/StructureDefinition/medication-brand-name
- http://hl7.org.au/fhir/StructureDefinition/medication-generic-name
- http://hl7.org.au/fhir/StructureDefinition/minimum-interval-between-repeats
- http://hl7.org.au/fhir/StructureDefinition/pbs-manufacturer-supplier
- http://hl7.org.au/fhir/StructureDefinition/au-receivingapplication
- http://hl7.org.au/fhir/StructureDefinition/au-receivingfacility
- http://hl7.org.au/fhir/StructureDefinition/au-assigningauthority
- http://hl7.org.au/fhir/StructureDefinition/au-receivingapplication
- http://hl7.org.au/fhir/StructureDefinition/au-receivingfacility
- http://hl7.org.au/fhir/StructureDefinition/encryption-certificate-pem-x509
- http://hl7.org.au/fhir/StructureDefinition/meta-source

Regards, 
Uday

**Comment by oridashi** [comment]
these are redirects from hl7.org.au and should now be functional
