### ISSUE TITLE
Profile URL's not resolving

### ISSUE THREAD

**Issue by udaychandrupatla** [hl7au/au-fhir-base#139]
Hello Brett, 

The following URL's for profiles which exist in profile description page are not resolving when one copies and pastes in a browser.
e.g.
![image](https://user-images.githubusercontent.com/32316167/45004362-3b524900-b02f-11e8-8807-c316f776096c.png)

http://hl7.org.au/fhir/StructureDefinition/au-observation-age
http://hl7.org.au/fhir/StructureDefinition/au-condition
http://hl7.org.au/fhir/StructureDefinition/au-relatedperson
http://hl7.org.au/fhir/StructureDefinition/au-location
http://hl7.org.au/fhir/StructureDefinition/au-prescription
http://hl7.org.au/fhir/StructureDefinition/au-dispenserecord
http://hl7.org.au/fhir/StructureDefinition/au-medicationstatement
http://hl7.org.au/fhir/StructureDefinition/au-immunisation
http://hl7.org.au/fhir/StructureDefinition/au-pbs-pharma-manufacturer
http://hl7.org.au/fhir/StructureDefinition/au-bodysite
http://hl7.org.au/fhir/StructureDefinition/au-bodyheight
http://hl7.org.au/fhir/StructureDefinition/au-bodyweight
http://hl7.org.au/fhir/StructureDefinition/au-condition
http://hl7.org.au/fhir/StructureDefinition/au-allergyintolerance
http://hl7.org.au/fhir/StructureDefinition/au-composition
http://hl7.org.au/fhir/StructureDefinition/au-address
http://hl7.org.au/fhir/StructureDefinition/au-dosage

Regards, 
Uday

**Comment by davidmckillop** [comment]
OFFICIAL

Hi Uday, Brett,

I think the issue may be related to this Zulip conversation:
https://chat.fhir.org/#narrow/stream/99-IG-creation/topic/Forthcoming.20fix.20for.20IG.20publisher.20that.20impacts.20all.20authors

Cheers
D. Mc

David McKillop – Clinical Information Modeller – Service Delivery – Core Services Systems Operations
Phone: +61 7 3023 8506<tel:+61%20730238506>  Mob: +61 407 780 269<tel:+61407780269>  Email: david.mckillop@digitalhealth.gov.au<mailto:david.mckillop@digitalhealth.gov.au>  Web: www.digitalhealth.gov.au<http://www.digitalhealth.gov.au/>

**Comment by oridashi** [comment]
this is a redirect from the hl7.org.au sites - this has been updated and believe fixed
