### ISSUE TITLE
An identifier slice of Care Agency Employee Identifier (CAE-I) to au-practitioner profile

### ISSUE THREAD

**Issue by udaychandrupatla** [hl7au/au-fhir-base#14]
A request to add Care Agency Employee Identifier (CAE-I) to au-practitioner profile.

The potential fixed values and constraints will be -
fixed value for system = http://ns.electronichealth.net.au/id/pcehr/caei/1.0
constraints -
The value shall be a 16 digit number
The identifier SHALL contain a prefix of 9
The identifier shall pass the Luhn algorithm check

If this identifier is added the Fixed value for System, Code and Display for type.coding element shall be requested from HL7 AU.

**Comment by udaychandrupatla** [comment]
A pull request has been done to HL7AU via d20d007b2c96523aca31b1f771efea77897dbbe1

**Comment by robeastwood-agency** [comment]
The CAEI definition has been added to the [au-practitionerrole profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html) via commit #[b36ed61](https://github.com/hl7au/au-fhir-base/commit/b36ed61a4b62a8cc97d9adc4eb1aeebd6d2f68aa#diff-e7fa0c35696cf3f28a932de9d8a44dfa).
This issue can be closed.

**Comment by oridashi** [comment]
thanks completed
