### ISSUE TITLE
Close the Gap Registration extension - should it be Closing the Gap?

### ISSUE THREAD

**Issue by dbojicic** [hl7au/au-fhir-base#145]
Hi Brett
Government, Dept of Health, PBS, various registration forms etc all refer to this as "Closing the Gap". 
"Close the Gap" seems to be an abbreviation. HL7 AU Implementation Guide should probably refer to this strategy by its official name.If you decide to change it, changes affect the extension name, URL and descriptions, as well as the au-patient profile.

Thanks
Dushi

**Comment by oridashi** [comment]
yes think that is right

**Comment by dbojicic** [comment]
Sorry Brett, not sure if you mean yes "Close the Gap" is right or you mean yes, it should be "Closing the Gap"?

**Comment by oridashi** [comment]
Closing the gap is correct I think

**Comment by robeastwood-agency** [comment]
Official link: https://closingthegap.pmc.gov.au/

**Comment by robeastwood-agency** [comment]
Discussed with @oridashi at the recent working group meeting and Brett has agreed to this change including updating the URL to be
`http://hl7.org.au/fhir/StructureDefinition/closing-the-gap-registration`

**Comment by robeastwood-agency** [comment]
This ticket can be closed as the associated PR (#173) has been merged in.
