### ISSUE TITLE
Au Base Address Profile invariants

### ISSUE THREAD

**Issue by SatyaYelisetti** [hl7au/au-fhir-base#150]
Hi Brett,

Can you please check the invariants in Address Profile. After testing i didnt find them working as they are supposed to so below are some proposed changes, replace the existing FHIRpath with below mentioned ones after having a look:

1. **inv-add-0: The address shall at least have text or a line:**
`address.text.exists() or address.line.exists()`

2. **inv-add-1: If not a fixed address, the type shall be 'physical':**
` address.extension.where(url='http://hl7.org.au/fhir/StructureDefinition/no-fixed-address' and value=true).exists() implies address.type='physical'`

3. **inv-add-2: If not a fixed address, the address text shall begin with 'NO FIXED ADDRESS':**
`address.extension.where(url='http://hl7.org.au/fhir/StructureDefinition/no-fixed-address').exists() implies address.text.startsWith('NO FIXED ADDRESS')`

The below XML is the test data for the existing invariants in the profile to test the above in FHIRpath TESTER:

```
<?xml version="1.0" encoding="UTF-8"?>
<Patient xmlns="http://hl7.org/fhir">    
    <address>
        <extension url="http://hl7.org.au/fhir/StructureDefinition/no-fixed-address">
            <valueBoolean value="true"/>
        </extension>
        <use value="temp"/>
        <type value="postal"/>
        <text value="I NO FIXED ADDRESS Melbourne, VIC"/>
        <state value="VIC" />
        <country value="AU"/>
    </address>
</Patient>
```

**Comment by oridashi** [comment]
could we check current publication - these look okay now?
