### ISSUE TITLE
Script owing (How to represent prescription created out of dispense event?)

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#152]
How is prescription created out of dispense event represented? 

Script owing is a common practice where a dispenser rings a doctor who verbally approves a script and the script gets created later (it is legal obligation to create this script). How is this prescription linked to DispenseRecord? Is an extension required? 

The profile should also include guidance on how to do this.

**Comment by oridashi** [comment]
We should discuss this further - on reading rules there should be an 'oral prescription' before dispensing - I think we should record that (will need some properties that make it known that this is a a verbal script not a paper one) then be able to replace it with a full script when done by the doctor.  Dispensing can refer to the verbal script then to the final script when completed.

**Comment by oridashi** [comment]
MedicationRequest.category - script owing can work on terms to describe a verbal/informal script that can be 'upgraded' to a full script

**Comment by dbojicic-agency** [comment]
Mentioned in [Meds WG 20200303 meeting notes](https://confluence.hl7australia.com/pages/resumedraft.action?draftId=31588660&draftShareId=b6d718a4-f9e6-40e0-96ea-6a2a9f2494c3)

**Comment by oridashi** [comment]
already proposed solution - eprescribing deals with this

**Comment by oridashi** [comment]
Simple 
 mr-status https://fhir.medicationknowledge.com.au/dev/StructureDefinition-mr-status.html

**Comment by brettesler-ext** [comment]
f2f discussion: propose to hold pending ETP reconcilliation

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
