### ISSUE TITLE
How to represent PBS/RPBS Authority Prescription Number, PBS/RPBS Authority Approval Number, Streamlined Authority Approval Number and State Authority Number?

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#153]
How should the following identifiers found in ETP be represented: 
a)	PBS/RPBS Authority Prescription Number
b)	PBS/RPBS Authority Approval Number
c)	Streamlined Authority Approval Number
d)	State Authority Number

Options for including in AU Base IG: 
- include as  a set of identifier slices for each of these
- include as separate extensions

**Comment by dbojicic-agency** [comment]
Discussed in [Meds WG 20200303 meeting notes](https://confluence.hl7australia.com/pages/resumedraft.action?draftId=31588660&draftShareId=b6d718a4-f9e6-40e0-96ea-6a2a9f2494c3)

**Comment by dtr-agency** [comment]
Related to https://github.com/hl7au/au-fhir-base/issues/370.

**Comment by oridashi** [comment]
repeat - already proposed solution - eprescribing deals with this
