### ISSUE TITLE
Please create an extension for Medical Benefit Category Type and ExplanationOfBenefit in prescribing context profile to be referenced by the extension

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#155]
Hi Brett

Please create Medical  Benefit Category Type extension that represents the category of subsidy appropriate to the item being prescribed, and the ExplanationOfBenefit profile to be referenced by the extension.
It can be a single code or a reference to ExplanationOfBenefit, with possible uses for both. 
Agreed design is to define an extension as a choice between a code and Reference(ExplanationOfBenefit in prescribing context). 

Background information: 
Medical Benefit Category Type (as seen in ETP) is the category of subsidy appropriate to the item being prescribed. 
The set of values in the SCS:  
- 1, PBS A subsidy under the Pharmaceutical Benefits Scheme applies to this item.
- 2, RPBS A subsidy under the Repatriation Pharmaceutical Benefits Scheme applies to this item.
- 3, CTG A subsidy under the Closing the Gap-PBS Co-Payment Measure applies to this item.
- 9, No benefit This item is not covered by a medical subsidy.

There is also NCTS code system that includes all of these concepts: https://healthterminologies.gov.au/fhir/CodeSystem/australian-benefit-payment-category-1. It does not include other concepts like "private" that might be required.

Thanks
Dushi

**Comment by oridashi** [comment]
will look at this when ETP is in focus

**Comment by oridashi** [comment]
already proposed solution - eprescribing deals with this

**Comment by oridashi** [comment]
this is done by; extension subsidised-concurrent-supply extesion - closing
