### ISSUE TITLE
MedicationDispense & MedicationRequest - identifier slices

### ISSUE THREAD

**Issue by dbojicic** [hl7au/au-fhir-base#158]
MedicationDispense and MedicationRequest have exactly the same identifier slice rules with slightly different names - 
a) consistency problems but 
b) is a dispense uniquely identified by the local script number? seems strange to me that this isn't a link to the a request aka authorizingPrescription instead of an identifier for a dispense record.

**Comment by oridashi** [comment]
identifiers changed now to include a local dispensing record identifiers; referent to the original script local prescription number will need to be through relationship to MedicationRequest from MedicaitonDispense
