### ISSUE TITLE
Bodyheight & bodyweight profiles - autogenerated summary text issue

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#178]
Currently the summary tab for these 2 profiles states this
> ​This profile contains the following variations from Observation:

With the hyperlink on "observation" being http://hl7.org/fhir/STU3/bodyweight (or to bodyheight)

As this AU profile is directly derived from the vital signs profile, not the observation resource, then the text should read:
> ​This profile contains the following variations from the Vital Signs Profile:

And the hyperlink to the profile as is (although the link gives 404 as it needs ".html" at the end)

I guess this auto-generated text from the XSLT transform is picking up the value in the profile element `<type value="Observation"/> `

**Comment by oridashi** [comment]
fixed [503377f]
