### ISSUE TITLE
Address profile narrative - suggested update

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#179]
The [Base Australian Address profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-address.html) has this text on the [profile.md](http://build.fhir.org/ig/hl7au/au-fhir-base/profiles.html) file
> Base Australian Address - well defined representation of an Australian address

which is different from other profiles on the same page (most of which start with "AU"). Also the text "well defined" differs from other descriptions on this page. Also note that the address profile page starts with the heading "AU Base Address Profile"

Therefore suggest that the profiles.md file be updated to read something like:
>AU Base Australian address - Australian address with common local coding

**Comment by oridashi** [comment]
done [b3f7e12]
