### ISSUE TITLE
Condition and AllergyIntolerance asserter - consider adding extension for role

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#180]
The STU3 [Condition](http://hl7.org/fhir/condition-definitions.html#Condition.asserter) and [AllergyIntolerance](http://hl7.org/fhir/allergyintolerance-definitions.html#AllergyIntolerance.asserter) resources both have an element to capture the asserter of the respective information. And the allowed references for both include Practitioner, Patient or RelatedPerson.

The R4 [Condition](http://build.fhir.org/condition-definitions.html#Condition.asserter) and [AllergyIntolerance](http://build.fhir.org/allergyintolerance-definitions.html#AllergyIntolerance.asserter) resources however have the additional allowance for a PractitionerRole to be recorded as an asserter. 

The role of an asserter in both Condition and AllergyIntolerance is of clinical value and therefore this ticket is to raise the need for a means of recording the role in the 2 AU profiles.

**Comment by oridashi** [comment]
PA - is reasonable to do this; make consistent across profiles

**Comment by robeastwood-agency** [comment]
As this affects the HL7 AU STU3 IG, which is no longer in development, this is being closed.
