### ISSUE TITLE
Condition and AllergyIntolerance - considerations about asserted date

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#181]
In R4 the Condition and AllergyIntolerance resources removed the STU3 allowance for recording the date the informationm was asserted ([here](http://hl7.org/fhir/allergyintolerance-definitions.html#AllergyIntolerance.assertedDate) and [here](http://hl7.org/fhir/condition-definitions.html#Condition.assertedDate)). R4 have instead an element for the date the record was first recorded, which in our view is different from _asserted_.

This ticket is to therefore to raise this point of difference and consequently the queries:
- is this information regarding _assertion_, as different from _recorded_, important to capture?
- and if so, would this warrant an extension?

**Comment by robeastwood-agency** [comment]
Note that both of the resources mentioned have core extensions available for representing asserted date; see
- [allergyintolerance-assertedDate](http://hl7.org/fhir/extension-allergyintolerance-asserteddate.html)
- [condition-assertedDate](http://hl7.org/fhir/extension-condition-asserteddate.html)

If these extensions are applicable to the wider HL7 AU community, then they can explicitly be added into the structure and narrative (as birthdate is for patient). Otherwise can be left as is.

**Comment by dtr-agency** [comment]
My 10 cents is that the original requirement coming out of the Agency is only STU3 relevant; happy with the R4 structure and changes. The Agency has no known requirements at this time for these core extensions and no reason to advocate including them.

**Comment by robeastwood-agency** [comment]
Closing on the basis that it is no longer an issue. The core extensions are available should they be needed to be used.
