### ISSUE TITLE
AllergyIntolerance profile - consider encounter profile

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#182]
The R4 AllergyIntolerance resource has an additional [encounter reference](http://build.fhir.org/allergyintolerance-definitions.html#AllergyIntolerance.encounter) to capture "_The encounter when the allergy or intolerance was asserted_" (ie not in STU3).

Suggest a pre-adoption extension of an encounter reference for STU3 AU Base AllergyIntolerance.

**Comment by oridashi** [comment]
have put references in narrative rather than model
