### ISSUE TITLE
Condition profile - add examples

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#183]
The [AU Base Condition profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-condition.html) would benefit from a few examples that demonstrate and support the usage as described in the resource (for example a confirmed diagnosis via evidence, a positive health state (such as pregnancy), a condition expressed by a patient, or a risk identified by a clinician etc).

Could also include various uses of the included SNOMED CT terminology.

**Comment by oridashi** [comment]
just a basic example added... can suggest more in ballot
