### ISSUE TITLE
Condition profile - consider extension for reference to BodySite profile

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#185]
The Condition resource includes an element to capture the [bodySite as a CodeableConcept](http://hl7.org/fhir/condition-definitions.html#Condition.bodySite). The included note states:
>  If the use case requires attributes from the BodySite resource (e.g. to identify and track separately) then use the [standard extension body-site-instance](http://hl7.org/fhir/extension-body-site-instance.html).

However, the HL7 AU base IG now includes [AU Base BodyStructure profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-bodystructure.html) that carries SNOMED CT terminology support; therefore consider creating an extension referencing the AU BodyStructure profile to be optionally used within a Condition record (and possibly others such as Specimen, Procedure etc).

Furthermore, proposing:
- incorporate the extension into AU Base Condition, as optional
- add narrative, explaining that if more detail is required to be represented than is supported by bodySite (as CodeableConcept), then use the extension can be used.

To proceed, seeking agreement with this approach.

**Comment by dtr-agency** [comment]
The core extension should be used if a body structure resource is to be referenced by a Condition. An HL7 AU extension offers no value to implementers, it conveniently allows for typing the resource to be AU Base BodyStructure but that comes at the cost of a reduction in interoperability when redefining a core extension locally for the same concept. 

If the desired behaviour is that the referenced resource conforms to Au Base Body Structure this can be achieved via other means e.g. invariants. Though given that AU Base Condition and AU Base Body Structure are both base profiles there is limited value in applying this rule - this would likely be useful downstream for a set of profiles derived from AU Base but not in AU Base itself.

Suggest that a note is added to the Extensions part of AU Base Condition to call out the core extension as a potentially useful extension.

**Comment by dtr-agency** [comment]
Closing due to lack of requirement.
