### ISSUE TITLE
NATA lab identifier

### ISSUE THREAD

**Issue by oridashi** [hl7au/au-fhir-base#19]
Advice
1.    A single corporate NATA/RCPA accreditation number (2639) and then each Laboratory also has their individual NATA accreditation site number, e.g.,

NATA/RCPA Accreditation No. 2639
Corporate Site No. 12542

NATA/RCPA Accreditation No. 2639
Corporate Site No. 12544
 
2.     The Corporate number is four digits, the Laboratory number may be either four or five digits.  There are no leading zeros on the reports provided.

**Comment by andrewpatto** [comment]
@oridashi - any movement on an official URI for this?

**Comment by oridashi** [comment]
nothing official but think we should sort this out - i'll continue on your question from the start of the year on zulip 
think we should do hl7.org.au namespace; and verify what V2 messages contain

**Comment by oridashi** [comment]
Discussion
https://confluence.hl7australia.com/display/PA/2018-07-18+Minutes

**Comment by oridashi** [comment]
profiles added to Organization.identifier + Location.identifier in AU Base
