### ISSUE TITLE
HCS serviceProvisionCode

### ISSUE THREAD

**Issue by oridashi** [hl7au/au-fhir-base#190]
serviceProvisionCode
Codesystem available from NHSD to replace example ValueSet
example binding
publish in AU base
service-provision-code
Jaco: send a copy to  Brett

**Comment by oridashi** [comment]
completed at [49bfe45]

**Comment by jaco-olivier** [comment]
Hi Brett - 

I noticed that the CodeSystem/ValueSets have been created off the sample we discussed in the Melbourne meeting.
I did email a much more defined CodeSystem and valueset definition to you.
Can I ask that you update the HCS.ServiceProvisionCode CodeSystem/Valueset with the ones as per email (I also uploaded them to this GitHub Issue)

[AU  service-provision-code.zip](https://github.com/hl7au/au-fhir-base/files/2498712/AU.service-provision-code.zip)
