### ISSUE TITLE
Practitioner.qualification - AHPRA slice terminology query for specialty certification

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#191]
The STU3 [Practitioner.qualification node](http://hl7.org/fhir/practitioner-definitions.html#Practitioner.qualification) contains a child element for the `code` and its _example_ terminology binding from [table 0360](http://hl7.org/fhir/v2/0360/2.7/index.html) has things like "Certified Registered Nurse", "Doctor of Pharmacy", "Registered Pharmacist" etc. That is, what looks like the name of the certification (degree, diploma, master, etc) and the profession in which the certification has been granted.

In the AHPRA slice, this element has a binding to the [NCTS valueset based on ANZSCO](https://healthterminologies.gov.au/fhir/ValueSet/anzsco-1), which covers the profession well, but does not include the type of certification. For example, "Physiotherapist", "Vascular Surgeon" etc.

Therefore, this ticket is to query whether this binding goes far enough (ie doesn't align with the STU3 intent of this element) and whether an extension should be introduced to capture the additional name of the certification.

**Comment by robeastwood-agency** [comment]
As an example (my own in fact), I have a _Bachelor of Applied Science_ in Physiotherapy, but if I did postgraduate studies I may have ended up with a _Graduate Certificate_ in Clinical Physiotherapy, a _Masters_ of Physiotherapy or even a _Doctor_ of Physiotherapy.
Does this distinction matter for an AHPRA registration?

**Comment by oridashi** [comment]
decision needed at PA call

**Comment by oridashi** [comment]
have decided to remove ANZSCO binding as it does not reflect the way AHPRA content is defined - this will be followed up with further discussions and development of a suitable binding - this is left as a text description only for now

**Comment by robeastwood-agency** [comment]
Closing as subsumed by #314
