### ISSUE TITLE
Extensions: isModifier flag related query

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#202]
Hi Brett,

Currently 6 extensions in the resources folder has Extension element with `<isModifier value="false" />`.
They are:
- [structuredefinition-closing-the-gap-registration.xml](https://github.com/hl7au/au-fhir-base/blob/master/resources/structuredefinition-closing-the-gap-registration.xml#L40)
- [structuredefinition-encryption-certificate-pem-x509.xml](https://github.com/hl7au/au-fhir-base/blob/master/resources/structuredefinition-encryption-certificate-pem-x509.xml#L39)
- [structuredefinition-ihi-record-status.xml](https://github.com/hl7au/au-fhir-base/blob/master/resources/structuredefinition-ihi-record-status.xml#L40)
- [structuredefinition-ihi-status.xml](https://github.com/hl7au/au-fhir-base/blob/master/resources/structuredefinition-ihi-status.xml#L40)
- [structuredefinition-indigenous-status.xml](https://github.com/hl7au/au-fhir-base/blob/master/resources/structuredefinition-indigenous-status.xml#L37)
- [structuredefinition-no-fixed-address.xml](https://github.com/hl7au/au-fhir-base/blob/master/resources/structuredefinition-no-fixed-address.xml#L40)

The query is: Are these deliberately present in only these 6 extensions and not in others?
Or it is immaterial and mean the same thing, whether isModifier flag is present with a value of 'false' or is just absent.

Thanks,
Vikas

**Comment by oridashi** [comment]
this is not a problem as default value is false - but would be good to be consistent and include everywhere

**Comment by oridashi** [comment]
[e2eda7d] removed all instead; not necessary
