### ISSUE TITLE
au-extensions :: QA issues 

### ISSUE THREAD

**Issue by udaychandrupatla** [hl7au/au-fhir-base#204]
Hi Brett, 

We found following issues when QA'ing au-extensions page.

1. http://build.fhir.org/ig/hl7au/au-fhir-base/extensions.html - The HealthCare Service Communication link appears twice under the same heading
**Resolution**: possibly duplicate entries in extensions.md
2. At the same page as above the "HL7 V2 Receiving Application" and "HL7 V2 Receiving Facility" and "Composition Author Role" links appears twice although under different headings
**Resolution**: just an observation and it might be intentional
3. http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-pbs-sponsor.html
**Resolution**: "Summary of Search Criteria for StructureDefinition-pbs-sponsor" section needs to have the text "none defined" 
4. http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-healthcareservice-communication.html - The Intro does not have "The extension applies to ..." format as most other extensions. Similar but may not be the same for http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-meta-source.html and http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-encryption-certificate-pem-x509.html
**Resolution**: since all the extensions do have introduction text which says "This extension applies to...", this extension needs to have it too.

Please let us know if you want us to do any of these changes and do a pull request.

Kind Regards,
Uday

**Comment by oridashi** [comment]
#1 fixed; #2 is intentional; #3 done; #4 done

**Comment by udaychandrupatla** [comment]
Hi Brett, 

Just a gentle reminder that I have just checked the fix's, we believe that point #4 is not fixed yet.

4. http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-healthcareservice-communication.html - The Intro does not have "The extension applies to ..." format as most other extensions. Similar but may not be the same for http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-meta-source.html and http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-encryption-certificate-pem-x509.html
**Resolution:** since all the extensions do have introduction text which says "This extension applies to...", this extension needs to have it too.

Thanks and Kind Regards,
Uday
