### ISSUE TITLE
AU Prescription: extension minimum-interval-between-repeats, suggest in dispenseRequest

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#206]
The extension minimum-interval-between-repeats is dispense request information. Suggest that this extension would be more appropriately located in the MedicationRequest.dispenseRequest structure.

**Comment by oridashi** [comment]
will discuss this further

**Comment by oridashi** [comment]
will move this

**Comment by oridashi** [comment]
remember to update narrative and examples to match this move

**Comment by oridashi** [comment]
missed for AU Base 1 reconsider

**Comment by oridashi** [comment]
mapped and solved in eprescribing

**Comment by oridashi** [comment]
unclear if ETP needs this in instances? put on hold

**Comment by dtr-agency** [comment]
This extension was not needed in R4 and is removed via https://github.com/hl7au/au-fhir-base/pull/688
