### ISSUE TITLE
Update description of http://hl7.org.au/id/ahpra-registration-number/ to include OID

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#207]
In order to represent this identifier in OID-based systems, and transform to and from CDA we will need an OID associated with this namespace. Please update the description of the namespace http://hl7.org.au/id/ahpra-registration-number/ with the equivalent OID (1.2.36.1.2001.1005.56) that can be used.

**Comment by RichardTON** [comment]
I found this from Phil Wilford

OID                             | description                             | symbolic name
1.2.36.1.2001.1005.56 | AHPRA Registration number  | ahpra-registration-number

So a number exits. Consider adding it the page for http://hl7.org.au/id/ahpra-registration-number/

**Comment by robeastwood-agency** [comment]
I am preparing a modification to the [responsible file](https://github.com/hl7au/au-fhir-base/blob/master/web-content/id/ahpra-registration-number/index.html) in preparation for a pull request; along the lines of:
> In OID-based systems use 1.2.36.1.2001.1005.56

**Comment by robeastwood-agency** [comment]
PR #218 added.

**Comment by robeastwood-agency** [comment]
Thanks Brett for merging in the related PR #218.

I just noticed though that the actual webpage for this http://hl7.org.au/id/ahpra-registration-number/ doesn't have the new OID info. So my assumption that this content is managed via the file https://github.com/hl7au/au-fhir-base/blob/master/web-content/id/ahpra-registration-number/index.html is incorrect - something else is required.

Would you mind pointing me in the right direction as to what else is needed to implement this change. Thank you.

Note that this also impacts issue #208 as I am currently in the process of preparing content via a PR for related changes for ABN and ACN.

**Comment by oridashi** [comment]
manual update of content on this site is needed; this now done - please close this issue if you are happy

**Comment by dtr-agency** [comment]
Thanks, this looks good.
