### ISSUE TITLE
Update http://hl7.org.au/id/nata-accreditation with info on OID-based system

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#209]
Recommend updating description of the namespaces http://hl7.org.au/id/nata-accreditation to provide advice on the OID that can be used to represent a NATA Accreditation number. The OID is 1.2.36.1.2001.1005.12; see http://www.hl7.org/oid/index.cfm?Comp_OID=1.2.36.1.2001.1005.12

**Comment by dtr-agency** [comment]
Should also update description of namespace http://hl7.org.au/id/nata-site/ to provide advice on the OID for NATA Site accreditation number which is 1.2.36.1.2001.1005.74

**Comment by oridashi** [comment]
done
