### ISSUE TITLE
HealthcareService.ServiceProvisionCode - update/improve CodeSystem

### ISSUE THREAD

**Issue by jaco-olivier** [hl7au/au-fhir-base#211]
I noticed that the CodeSystem/ValueSets have been created off the sample we discussed in the Melbourne meeting.
I did email a much more defined CodeSystem and valueset definition to you.
Can I ask that you update the HCS.ServiceProvisionCode CodeSystem/Valueset with the ones as per email (I also uploaded them to this GitHub Issue)

[AU  service-provision-code.zip](https://github.com/hl7au/au-fhir-base/files/2498712/AU.service-provision-code.zip)

_Originally posted by @jaco-olivier in https://github.com/hl7au/au-fhir-base/issue_comments#issuecomment-431630923_

**Comment by oridashi** [comment]
Thanks Jaco - will fix this in the current build...

Regards,
Brett Esler
mobile: 0423 083 847
skype: brett.esler
web: www.oridashi.com.au
