### ISSUE TITLE
geojson extension 

### ISSUE THREAD

**Issue by oridashi** [hl7au/au-fhir-base#214]
Base IG trunk geojson extension http://build.fhir.org/extension-location-boundary-geojson.html  (inline/reference) and search param http://build.fhir.org/ig/HL7/VhDir/SearchParameter-searchparameter-location-contains.html (BP putting up samples)

**Comment by oridashi** [comment]
will not be done in STU3 base - will address in R4 version of PD

**Comment by brianpos** [comment]
:(

**Comment by oridashi** [comment]
only an R4 extension defined in core - will just include in R4 version of AU Base
