### ISSUE TITLE
Query: Slice name and short description

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#217]
Hi, Just a query on similar lines as the following pull request (https://github.com/hl7au/au-fhir-base/pull/216) made.

Is there a need to update the slice name (https://github.com/hl7au/au-fhir-base/blob/d3a6e77550d6d367b05df339cca2e82ba240bae7/resources/au-immunisation.xml#L233) to something like "snomedReasonNotAdministered" and short description (https://github.com/hl7au/au-fhir-base/blob/d3a6e77550d6d367b05df339cca2e82ba240bae7/resources/au-immunisation.xml#L234) to may be "Reason Vaccine Not Administered (SNOMED CT)"?

Asking this as this may help in making the two slices look similar. Cheers, Vikas

**Comment by oridashi** [comment]
still to do

**Comment by oridashi** [comment]
modified structure so no slices any more; change not needed
