### ISSUE TITLE
HealthcareService.characteristic discussion

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#219]
https://confluence.hl7australia.com/display/PA/HealthcareService+Discussion+Topics+-+13-09-2018

**Comment by oridashi** [comment]
still to do

**Comment by oridashi** [comment]
this needs more discussion at PA

**Comment by oridashi** [comment]
placed on hold for ballot QA; not a priority

**Comment by brettesler-ext** [comment]
f2f comment - keep on hold; will be relevant  for service directories originally NHSD raised
moved supporting info https://hl7.org.au/archive/fhirwg/HealthcareService-Discussion-Topics---13-09-2018_14582296.html

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
