### ISSUE TITLE
medicationCodeableConcept and medicationReference are both 1..1

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#225]
http://hl7.org.au/fhir/base2018Sep/StructureDefinition-au-medicationstatement.html
https://jira.hl7australia.com/browse/FHIRIG-52

medicationCodeableConcept and medicationReference are both 1..1
This makes it impossible to create a profile where only codes are permitted and references are prohibited.

It also means that both must be provided, not just one of the two.

This applies to many of the medication profiles.

**Comment by dtr-agency** [comment]
Resolving this is a big priority for us to derive some medication profiles. Both profiles where we want to derive and force medicationReference and profiles where we want to derive and force supply of medicationCodeableConcept.

**Comment by oridashi** [comment]
This is a $type sliced mandatory element - so might need to get some advice
here as the cardinality of the slice is set by the cardinality of the
choice element itself

Regards,
Brett Esler
mobile: 0423 083 847
skype: brett.esler
web: www.oridashi.com.au

**Comment by oridashi** [comment]
believe this is reflecting current publication method - will follow up re presentation

**Comment by oridashi** [comment]
not sure there is any alternative to this presentation - will leave this in the hands of the IG publisher tooling authors
