### ISSUE TITLE
Add 'Do not discontinue' flag for MedicationStatement?

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#226]
In MedicationStatement profile, do we want to include some way to allow specifying that a new medication item should not be discontinued; this would be an extension to flag 'do not discontinue'. 
Possible use scenario is in a specialist letter or a discharge summary, e.g. a patient is admitted to hospital, and the hospital reviews the patients current medication. The hospital clinician decides to put the patient on a new medication, and needs to tell the patient's GP (primary care physician) that the new medication should not be discontinued. 
This is related to Zulip chat https://chat.fhir.org/#narrow/stream/4-implementers/subject/Medications.20not.20to.20be.20discontinued

**Comment by oridashi** [comment]
withdrawn - not needed at this time
