### ISSUE TITLE
Changed: PAI-D prefix is 8003640003 not operating as expected

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#230]
I'm attempting to validate example instances against their corresponding profiles rather than a base resource. And in so doing, noticed that various FHIRpath expressions in the HL7 AU profiles may not work as they are currently written. Suspicions are that the expression should include the absolute element path from the perspective of the root element instead of from the perspective of the element where the invariant sits.

**To demonstrate this**, see the [HL7 AU base device profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-device.html) and its [corresponding example](http://build.fhir.org/ig/hl7au/au-fhir-base/Device-example0.html).

This example is currently has no errors/warnings in [the QA report](http://build.fhir.org/ig/hl7au/au-fhir-base/qa.html#_scratch_ig-build-temp-UT4UT7_repo_examples_device-example0), noting that it does not include a meta.profile assertion that the example complies with this profile.

However, when meta.profile assertion is added, as such
```
<Device xmlns="http://hl7.org/fhir">
    <id value="example0"/>
    <meta>
        <profile value="http://hl7.org.au/fhir/StructureDefinition/au-device"/>
    </meta>
    <identifier>
```
the QA report then compains about a missing system value (it is 1..1 in the profile), and once that is added and the IG publisher run again, the example goes back to passing.

Now, regarding the invariant [inv-paid-1](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-device-definitions.html#Device.identifier:paid.value): PAI-D prefix is 8003640003 (with the FHIRpath of `startsWith('8003640003')`) - if the example is changed so that this value starts with eg `900364....` instead, an error would be expected. However, **no error** is raised on a new IG publisher run. If extra digits are added though to this value, in order to test the maximum length of 16, this expected error is indeed raised.

Experimenting in the [FHIRpath tester](https://github.com/brianpos/FhirPathTester) with this example leads to the following expression working - that is, the slice is identified by system and the full element path relative to the root element is added:
```
identifier.where(system='http://ns.electronichealth.net.au/id/pcehr/paid/1.0').value.startsWith('8003640003')
```

My **conclusion** is that FHIRpath expressions need to include their context relative to the root element, irrespective of which nested child element they are located within.

This needs verification - and if found correct, then a number of invariant expressions across the HL7 AU base IG need to be updated.

**Comment by oridashi** [comment]
I am assured the constraint expression path is in the context of the element in which it it is defined and that is how StructureDefinitions are validated in servers.  We had better confirm if the IG builder is not operating as expected in this regard - so will leave this open for follow up.

**Comment by oridashi** [comment]
Title was: FHIRpath expression path query - relative to root element?

**Comment by oridashi** [comment]
this is now for review
