### ISSUE TITLE
Medication Type extension

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#231]
I think that the description of use for http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-medication-type.html is quite wrong.

The extension is suitable to classify the medication into a medication item type, e.g. "Unbranded product with strengths and form" or "Branded product with form but no strengths". The guidance suggests to use alternate values of CodeableConcept.coding to represent a classification hierarchy for the medication. That is an error. Alternate values of CodeableConcept.coding are meant to be alternate codes for the same thing, not represent a classification hierarchy for that thing. The part of the classification hierarchy relevant to the medication needs to be recorded in a different element.

Also the name "medication type" is unclear. What sort of type? Consider calling it "medication item type".

**Comment by oridashi** [comment]
we can review in AU Base 2 issues

**Comment by oridashi** [comment]
as discussed in committee this is left for open use and we await feedback on any required modifications
