### ISSUE TITLE
Brand and generic names in Medication profiles

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#232]
I think that the design in http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationstatement.html needs

- a constraint that at most one slice form the AMT is permitted in medicationCodeableConcept,
- a codeable concept element for the generic name of the medication - this will include the medication-type extension, and
- guidance on the use of medication-type.

This applies to all of the medication profiles

see also #231

**Comment by oridashi** [comment]
done in AU Base 1 resolution
