### ISSUE TITLE
closing-the-gap-registration clarification on meaning and use required

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#233]
The intro content states that this extension is for indicating whether the patient is eligible for a Closing the Gap (CTG) co-payment but the definition in the extension states that this is actually whether or not the patient is registered for Closing The Gap - I am fairly sure the extension is about indicating eligibility not whether or not a patient has been registered but the extension definition and short need to be clearer.

I am not sure whether or not this is in general about a general Close The Gap benefit category or whether it is actually about eligibility for the specific Closing The Gap co-payment (see https://meteor.aihw.gov.au/content/index.phtml/itemId/603671). If it is about the co-payment the extension definition and short should also be clear about this.

**Comment by oridashi** [comment]
include in ballot issue

**Comment by oridashi** [comment]
reworded
