### ISSUE TITLE
Error raised re RelatedPerson.identifier:commonwealthSeniorsHealthCard

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#239]
We are creating a range of local examples and are validating against their associated profiles, with a value in meta.profile. The example is an instance of composition which has been derived from the [HL7 AU Base Composition profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-composition.html). However, the same error occurs with 3 of the 4 HL7 AU RelatedPerson examples (ie those that have an identifier node) when they temporarily include a meta.profile value for testing.

The error is:
```Unsupported CodeableConcept pattern - using text - for discriminator(type) for slice RelatedPerson.identifier:commonwealthSeniorsHealthCard```

The meta.profile value added is 
```
<RelatedPerson xmlns="http://hl7.org/fhir">
  <id value="example0"/>
  <meta>
    <profile value="http://hl7.org.au/fhir/StructureDefinition/au-relatedperson"/>
  </meta>
```
Is this a problem with the slice definition re use of pattern on [RelatedPerson.identifier.type](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-relatedperson-definitions.html#RelatedPerson.identifier:commonwealthSeniorsHealthCard.type)?

**Comment by oridashi** [comment]
technical correction made to address this and other issues
