### ISSUE TITLE
Add web aliases for new profiles

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#240]
The following profiles do not have resolvable uris:
- http://hl7.org.au/fhir/StructureDefinition/au-norelevantfinding

Also none of the extensions do either. Of immediate interest to CI at the Agency are:
- http://hl7.org.au/fhir/StructureDefinition/recorder

**Comment by oridashi** [comment]
fixed - please verify and close

**Comment by robeastwood-agency** [comment]
Thanks @oridashi - the 2 URIs listed above now resolve (as well as AU Medicine List). 
Closeable (I don't have the access rights to do so).

**Comment by davidmckillop** [comment]
Hi Brett,

In the following extensions the "The official URL for this profile is" is not resolving:
1)  http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-author-role.html the uri http://hl7.org.au/fhir/StructureDefinition/author-role is not resolving.
2)  http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-healthcareservice-communication.html the uri http://hl7.org.au/fhir/StructureDefinition/healthcareservice-communication is not resolving
3)  http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-encounter-description.html the uri http://hl7.org.au/fhir/StructureDefinition/encounter-description is not resolving
4) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-author-role.html the uri  http://hl7.org.au/fhir/StructureDefinition/author-role is not resolving
5) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-closing-the-gap-registration.html the uri http://hl7.org.au/fhir/StructureDefinition/closing-the-gap-registration is not resolving
6) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-pbs-sponsor.html the uri  http://hl7.org.au/fhir/StructureDefinition/pbs-sponsor  is not resolving
7) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-medication-administration-witness.html the uri http://hl7.org.au/fhir/StructureDefinition/medication-administration-witness is not resolving
8) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-medication-strength-text.html the uri http://hl7.org.au/fhir/StructureDefinition/medication-strength-text is not resolving 
9) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-change-description.html the uri http://hl7.org.au/fhir/StructureDefinition/change-description is not resolving
10) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-list-source-role.html the uri http://hl7.org.au/fhir/StructureDefinition/list-source-role is not resolving
11) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-recorder-related-person.html the uri http://hl7.org.au/fhir/StructureDefinition/recorder-related-person is not resolving
12) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-list-source-role.html the uri http://hl7.org.au/fhir/StructureDefinition/list-source-role is not resolving
13) http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-recorder-related-person.html the uri http://hl7.org.au/fhir/StructureDefinition/recorder-related-person is not resolving

Can you do the "redirection" thing please.

**Comment by oridashi** [comment]
replaced with #297 - all are broken
