### ISSUE TITLE
OID for CodeSystem-au-hl7v2-0203

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#244]
What is the OID for http://hl7.org.au/fhir/v2/0203? The page on this code system in the HL7 AU Base implementation guide needs to be updated with this information.

Current build page is here: http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-hl7v2-0203.html

**Comment by oridashi** [comment]
OID noted 
https://jira.hl7australia.com/browse/FHIRIG-31
change pending

**Comment by dtr-agency** [comment]
Thanks, this looks good.
