### ISSUE TITLE
Medication.form - changes to terminology binding are visible in the snapshot only

### ISSUE THREAD

**Issue by dbojicic** [hl7au/au-fhir-base#246]
Brett, changes to add Medication.form binding to [Medication Form](https://healthterminologies.gov.au/fhir/ValueSet/medication-form-1) value set were done and merged into HL7 AU build in Aug 2018; please see https://github.com/hl7au/au-fhir-base/pull/79. 
However, something seems to have gone wrong with the merge as the changes are not visible in the differential but can be seen in the snapshot (snomedForm slice with required binding to the Medication Form value set). 
The text summary says that manufacturer is bound to that form set (this was reported in one of the ballot issues).

**Comment by robeastwood-agency** [comment]
This is due to the parent of `Medication.form.coding` not being present in the xml immediatley prior (see [this line](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-medication.xml#L447)). Ie adding this prior resolves the problem:
```
<element id="Medication.form">
      <path value="Medication.form"/>
</element>
```

**Comment by robeastwood-agency** [comment]
And on closer inspection, the same thing applies to the constraints for `Medication.package`; they appear in the snapshot but not differential. And adding this before [line 520](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-medication.xml#L520), resolves the problem:
```
<element id="Medication.package">
      <path value="Medication.package"/>
</element>
```

**Comment by robeastwood-agency** [comment]
@oridashi - Brett would you like a PR for these changes?
