### ISSUE TITLE
Verify all HI Service numbers in the au-fhir-base are appropriate for use

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#252]
There is a small set of HI Service numbers (IHI, HPI-O, HPI-I, PAI-O and PAI-D) that are approved by Medicare for usage in test/demo environments. 

This ticket has been raised for a review to be done of all artefacts in the au-fhir-base to ensure that all HI Service numbers used comply with the above approved list.

Note that this includes 
* any actual instance examples 
* profiles which may include a value in the [ElementDefinition.example element](http://hl7.org/fhir/STU3/elementdefinition-definitions.html#ElementDefinition.example)

This may result in changes to artefacts should they be using a non-approved number.

**Comment by davidmckillop** [comment]
Sample Healthcare Identifiers

Mentioned below are the approved test healthcare identifiers from the IT14 handbook. These identifiers are test identifiers with generic information associated with them, These identifiers shall be used in all Agency CDA/SCS specifications.

IHI number:

1.2.36.1.2001.1003.0.8003608833357361

HPII Number:
1.2.36.1.2001.1003.0.8003619900015717

HPIO Number:
1.2.36.1.2001.1003.0.8003621566684455

**Comment by robeastwood-agency** [comment]
And PAI numbers:

- PAI-O: 8003640011000000
- PAI-D: 8003640013000008

**Comment by oridashi** [comment]
fixed for AU Base 1
