### ISSUE TITLE
HL7 AU extension section author - deprecate and convert to R4 canonical pre-adoption convention

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#261]
R4 FHIR std defines in https://build.fhir.org/versions.html#extensions the recommended means of adopting an element in another version of FHIR as an extension.

The majority of 'R4' preadoption extensions in HL7 AU Base extend the types allowed and are not adoption of an element.

There are only two that pre-adopt an element:
http://hl7.org.au/fhir/StructureDefinition/section-author
http://hl7.org.au/fhir/StructureDefinition/meta-source

meta-source is supported in a HL7 AU IG this isn't recommended to be changed. 
section author has not been supported in an HL7 AU IG - or any other IG I can find. 

Recommend HL7 AU section author is deprecated and HL7 AU Base Composition is updated to refer to "http://hl7.org/fhir/4.0/StructureDefinition/extension-Composition.section.author".

**Comment by oridashi** [comment]
added narrative referencing pre-adopt approach
