### ISSUE TITLE
HL7 AU extension associated healthcare service constrains the valueReference to a profile

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#263]
HL7 AU extension associated healthcare service (see http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-associated-healthcareservice.html) should not have its reference type constrained by a profile.

The valueReference should be the base HealthcareService resource.

**Comment by oridashi** [comment]
https://github.com/hl7au/au-fhir-base/pull/264 fixed
