### ISSUE TITLE
Medication diff and snapshot do not align

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#268]
**Misalignment between snapshot and diff**
Medication.form.coding is sliced in the snapshot but not the difference
Medication.ingredient.item is sliced differently in the snapshot and difference

**Misalignment between snapshot and STU3 not visible in the snapshot**
Medication.package.content is 0..1 in the snapshot but 0..* in STU3

**Comment by RichardTON** [comment]
This may apply to other meds profiles.

**Comment by RichardTON** [comment]
medication.batch.serialnumber is in snapshot but not differential, and is not wanted as it is not in the final version of R4.

**Comment by RichardTON** [comment]
batch.serialnumber removed in [28739c7]

**Comment by RichardTON** [comment]
pull request created

**Comment by oridashi** [comment]
type slicing seems to expand the typed elements in snapshot and not show as a slice; but shows as a slice in differential

**Comment by oridashi** [comment]
tooling issue see https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Slicing.20a.20non-repeating.20element  
no fix for IG; wait for tooling changes

**Comment by RichardTON** [comment]
Issue has gone.
