### ISSUE TITLE
Medication defect allows multiple instances of elements that should be 0..1

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#269]
medication-brand-name should be 0..1
medication-generic-name should be 0..1
medication-strength-text should be 0..1

**Comment by RichardTON** [comment]
This applies to other meds profiles.

**Comment by RichardTON** [comment]
I've committed this change locally and will create a pull request later.

**Comment by RichardTON** [comment]
pull request created

**Comment by oridashi** [comment]
merged
