### ISSUE TITLE
Some medication extensions have useless definitions of their root element

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#270]
The extensions brand-name and generic-name have only “An Extension” as the element definition. (They do have reasonable text for short.)

definition of generic-name could be : "The generic medication text name for an associated medication, this may not be the same as the subject medication (prescribed, dispensed or stated) but may be used to provide an additional or equivalent drug name that is a generic medication concept."

definition of brand-name could be : ??? Medication brand name.

**Comment by RichardTON** [comment]
This applies to other meds profiles.

**Comment by oridashi** [comment]
fixed in CI build
