### ISSUE TITLE
Introduction is poor in medications profiles

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#271]
1. In Medication it states that Medication.package, has been profiled to 0..1. Medication.package is 0.1 in the base and does not need profiling.
2. In medication the elements deleted in R4 (e.g. Medication.isBrand, do not have extensions defined at http://hl7.org/fhir/r4/medication-profiles.html
3. The actual text under the heading Extensions is wrong in every profile e.g. the MedicationRequest profile has “MedicationDispense: Medication Generic Drug Name” in it 
4. Associated with that incorrect text is a less helpful explanation of usage than is what in the extension; guidance on use for these extensions needs to be placed and similar to the guidance on usage of elements in AU Base Medication profile – potentially just by directing people that guidance on use of the extension is in the extension definition or properly repeat it here (see below for suggestion).  
5. If someone takes the time and effort they can work out what is going on but it isn’t good for a naïve or skimming reader – I think this presentation is sufficient to degrade an informed ballot response.  
6. Is the guidance on brand-name and generic-name correct? Does it only apply when there is no code.
7. The guidance on strength isn’t as good as the others.

**Comment by RichardTON** [comment]
More suggested wording

Suggested kind of paragraph for guidance on extensions
The following text-only extensions available in AU Base Medication are discouraged for use where a system can include multiple codings to represent these medication concepts:
- medication-brand-name
- medication-generic-name

or even
It is recommended to include multiple codings in a medication code to represent brand and generic medication concepts rather than text name only extension medication-brand-name or medication-generic-name.

**Comment by oridashi** [comment]
as discussed in committee sufficient wording for now; will take feedback based on actual use
