### ISSUE TITLE
Issues with PBSSponsor

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#272]
1. The extension (http://hl7.org.au/fhir/StructureDefinition/pbs-sponsor) does not use the correct URI for the profile of organization (http://hl7.org.au/fhir/StructureDefinition/pbs-sponsor-organisation) , it uses http://hl7.org.au/fhir/StructureDefinition/au-pbs-sponsor

2. The profile of organization (http://hl7.org.au/fhir/StructureDefinition/pbs-sponsor-organisation) uses the wrong value for Organization.identifier.system, it uses http://hl7.org.au/id/pbs-sponsor.

3. I’ve again asked in Zulip (https://chat.fhir.org/#narrow/stream/179249-Medication/topic/Scope.20of.20Medication.2Emanufacturer) whether we can use Medication.manufacturer. Possibly the US and Europe actually record sponsor instead of manufacturer. 

4. If we do need to use an extension, the extension would be much simpler to understand and implement if it was an identifier instead of a reference to a profile of Organization. I believe the simpler design is better in such a specialised extension.

**Comment by RichardTON** [comment]
The HL7 Meds WG has ruled that Medication.manufacturer does not include the sponsor of the medicine. 
https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=22652
We need an extension for pbs-sponsor.

**Comment by RichardTON** [comment]
And the Med WG decision is still being debated. See https://chat.fhir.org/#narrow/stream/179249-Medication/topic/Scope.20of.20Medication.2Emanufacturer

**Comment by oridashi** [comment]
bad reference to org profile, cardinality of valueReference and logical identifier does not match profile

**Comment by RichardTON** [comment]
Decided on 7/6/19 - Re meds ballot 2 meeting.
Remove reference to PBS Sponsor extension from AU Base Medication - awaiting guideline amendments.
