### ISSUE TITLE
AU Base Patient profile - cardinality of extensions now 0..* (?Forge removed 0..1)

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#273]
Hi @oridashi - the recent commit https://github.com/hl7au/au-fhir-base/commit/69e716e43920672c6254c57676b62e794da14d56 on Base Patient for a rewording of the Close the Gap definition also had a number of changes to cardinalities of extensions. 

For example, all of these extensions are now 0..* rather than their original 0..1 - birthPlace, indigenous-status, closing-the-gap-registration, patient-mothersMaidenName, ihi-status, ihi-record-status, date-accuracy-indicator (x2) & patient-birthTime.

Presumably this was Forge doing some unwanted pruning.

**Comment by oridashi** [comment]
believe now fixed

**Comment by robeastwood-agency** [comment]
Looks good; thanks @oridashi
