### ISSUE TITLE
Deprecate extension Medication Batch Serial Number (was for R4 preadoption but did not make it to R4 publication)

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#274]
The Extension: Medication Batch Serial Number http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-medication-batch-serialnumber.html was developed and proposed as part of aligning STU3 HL7 AU Base Medication to R4. 

At the time of alignment work there was an element in R4 for serialNumber; thus a preadoption extension was defined in HL7 AU and referenced by HL7 AU Base Medication. Final R4 publication does not have this element; its need / use case has been deprecated. 

We should therefore remove the reference to the element in HL7 AU Base Medication profile, and consider deprecating the extension itself.

**Comment by oridashi** [comment]
fixed in build
