### ISSUE TITLE
Extension cardinality issue

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#28]
The [base patient profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) has a number of extensions that have cardinality of `0..*` in the patient differential data hierarchy but when viewed directly in Forge the cardinality shows up as `0..1` (as expected). I gather that the cardinality within each extension definition is not getting propagated into the patient profile itself. 

For example, the [extension for Australian Indigenous status](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-indigenous-status.html) has its root Extension element cardinality set to `0..1`. However, the rendered view of the patient profile shows its cardinality as `0..*`.

This is seen for these extensions:
- Australian Indigenous status
- Birth Place
- Close the Gap Registration
- IHI status
- IHI Record Status
- Patient birthTime

I also gather that this does require some manual intervention outside of Forge to add the correct cardinality of `0..1`.

**Comment by oridashi** [comment]
Fixed as per referenced commit
