### ISSUE TITLE
au-immunization vaccineCode.coding slice for AMT - should be extensible?

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#281]
The [au-immunization profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-immunization.html) has 2 slices on vaccineCode.coding - one for slice for AMT and another for AIR. Both have their respective valueset bindings. However, the AIR binding has been set to required whereas the one for AMT is extensible.

We are wondering whether the binding for AMT should also be set to required, in order for the slice discriminator to work. That is, a value that extends AMT may satisfy both slices.

**Comment by oridashi** [comment]
slice on system needs a fixed value for system to discriminate - make the fixed system values SNOMED CT and AIR systems that match the valueset bindings; make SNOMED CT binding preferred

**Comment by oridashi** [comment]
Fix applied bfc8b36
