### ISSUE TITLE
Extend List to allow a related person to be the source

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#283]
List.source excludes RelatedPerson.
We want to allow a list to be authored by a non-professional carer of the patient. In STU3 and R4 that will require an extension.
Please add RelatedPerson as a possible reference for List.source.

I have requested this change for R5 in https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=22667

**Comment by dbojicic-agency** [comment]
Recorder as a Related Person (http://hl7.org.au/fhir/StructureDefinition/recorder-related-person)
extension is created to pre-adopt R4 AllergyIntolerance.recorder as a related person, defined as 'Individual who recorded the record and takes responsibility for its content.' which sounds like an author and aligns with the List.source definition 'The entity responsible for deciding what the contents of the list were. Where the list was created by a human, this is the same as the author of the list.'.

I suggest updating Recorder as a Related Person to make it less specific & update context to 'Resource' and use the same extension in both AllergyIntolerance and List profiles.


--

**Comment by oridashi** [comment]
merged in CI build
