### ISSUE TITLE
Deprecate ListSourceRole extension and use more generic AuthorRole extension instead

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#284]
Both ListSourceRole  and AuthorRole extensions preadopt from R4 an author that is a practitioner role. Suggest deprecating ListSourceRole extension, used in AU Medicine List profile, and using AuthorRole extension instead. AuthorRole definition allows it to be used in any profile already. 

Brett, as agreed, we will provide this change via a pull request.

**Comment by oridashi** [comment]
complete and merged
