### ISSUE TITLE
Correct heading on XML display pages

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#287]
In the published profiles (e.g. http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html), on the XML tab for a profile (e.g. http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.xml.html) the Heading is "Example: <filename>"

1/ This is not an example
2/ The resource title (or even the name) is a better choice than the file name.

The file format.html defines the presentation of these pages.

**Comment by RichardTON** [comment]
Also see http://build.fhir.org/ehrsrle/ehrsrle-auditevent.profile.xml.html

**Comment by oridashi** [comment]
fix: just the tile added to CI build
