### ISSUE TITLE
How to represent information that a medicine list contains medicine items packed in a DAA?

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#293]
We have a requirement to include a flag, setting, statement or other indicator in a current medicine list/document, to inform the reader that the current medicine list contains one or more medicines that are packed by a pharmacy in a dose administration aid. This is to inform healthcare providers that a patient is receiving packed medicines so consultations and healthcare can be tailored to benefit the patient . 

From the requirements, this could be a conceptual a yes/no/ or true/false statement but could also contain a 'not provided' value or similar to support systems that do not have the capacity to include this information. 

How do we represent this? One possibility is to include this information for each medicine item on the list (e.g. packed in DAA); another to have one 'statement' for the list that the list includes medicines packed in DAA without specifying which medicines.

**Comment by oridashi** [comment]
* will it affect workflow /decision support - sorting, filtering ? 
* is it an alert/flag with some status higher than an annotation ?

We think neither of the above are true(BA Gary).
So we will support this using element List.note (Annotation) which is a comment about the medicines list.

Where desired in implementation guides narrative to describe this case and preferred text may be provided.
