### ISSUE TITLE
Organisation examples incompletly converted to R4

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#295]
In organization-example1 and In organization-example3
replace
            `<system value="http://hl7.org/fhir/organization-type"/>"`
with
           ` <system value="http://terminology.hl7.org/CodeSystem/organization-type"/>` 

In organization-example4
replace
        `<extension url="http://hl7.org.au/fhir/StructureDefinition/meta-source">`
           `<valueUri value="http://hl7.org.au/project/provider-directory"/>`
        `</extension>`
with
       `<source value="http://hl7.org.au/project/provider-directory"/>`

**Comment by robeastwood-agency** [comment]
organization-example1 and organization-example3 are now fixed via https://github.com/hl7au/au-fhir-base/commit/1ba102a4e206ab081b5764dfc0235141209ff9c7

organization-example4 no longer has this content

I believe this issue can now be closed

**Comment by RichardTON** [comment]
Agreed
