### ISSUE TITLE
Patient uses obsolete URLs for value sets

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#296]
Patient has some instances of
`<system value="http://hl7.org/fhir/v2/0203" />`
but in R4 the code system's URL is `http://terminology.hl7.org/CodeSystem/v2-0203`
it should be 
`<system value="http://terminology.hl7.org/CodeSystem/v2-0203" />`

**Comment by RichardTON** [comment]
Practitioner, PractitionerRole, and RelatedPerson have the same problem.

**Comment by robeastwood-agency** [comment]
This can be closed as the work has been done.
