### ISSUE TITLE
URLs for AU profiles do not resolve.

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#297]
For example
`http://hl7.org.au/fhir/StructureDefinition/au-patient`
gives a 404 error

**Comment by oridashi** [comment]
needs updating now still a few missing

**Comment by RichardTON** [comment]
Au base profiles resolve nicely for stu3.

However, the latest R4 build says that it is superseded by a stu3 version 1.0.2.
http://hl7.org.au/fhir/history.html says that it has a date of 2019-07-31, but the file name is http://hl7.org.au/fhir/2019Aug/

And there is no more recent R4 build. That will cause problems.

**Comment by RichardTON** [comment]
> Au base profiles resolve nicely for stu3.
> 
> However, the latest R4 build says that it is superseded by a stu3 version 1.0.2.
> http://hl7.org.au/fhir/history.html says that the latest R4 build has a date of 2019-07-31, but the file name is http://hl7.org.au/fhir/2019Aug/
> 
> And there is no more recent R4 build. That will cause problems.

This has been fixed.
