### ISSUE TITLE
Why does the discriminator for the slicing of Patient.identifier include system

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#299]
Why does the discriminator for the slicing of Patient.identifier include system?
system is optional and not fixed in one slice (Medical Record Number (MRN)), and is mandatory but not fixed in another slice (Private health insurance member number.)
It would be sufficient and simpler to slice on type.

**Comment by robeastwood-agency** [comment]
With the transition to represent identifiers as datatype profiles rather than slices, this issue can be now closed.
