### ISSUE TITLE
Feature - Device.identifier PAI-D slice, add type.coding for "NDI"

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#3]
Add into the [Device profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-device.html) slice for the PAI-D identifier a fixed value for the `identifier.type.coding` as has been done with the [Organisation HPI-O slice](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-organisation.html).
The fixed value details (as found in the [HL7 V2 Table 0203 - Identifier Type (AU Extended) code system](http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-codesystem-au-hl7v2-0203.html)) are:
- System: http://hl7.org.au/fhir/v2/0203
- Code: NDI
- Display: National Device Identifier

(Note that the example device instance already uses the above values.)

**Plan**: candidate pull request

**Comment by oridashi** [comment]
looks good merged

**Comment by oridashi** [comment]
done
