### ISSUE TITLE
Proposing improvements to the Address profile

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#30]
The current [Address profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-address.html) caters for Australian as well as non-Australian residences. To cater for these 2 address categories, the profile has a number of invariants doing the job of differentiating the 2 categories. As such, there are a number of elements represented as text that could be better represented using terminology particularly given that NCTS support is imminent. 

This ticket is aimed at proposing some improvements (yet to be determined) that will eventually be offered up in the form of a pull request.

**Comment by oridashi** [comment]
Australian address now specifically only for addresses in Australia and binding made for state element and country fixed to AU
