### ISSUE TITLE
AU Medicare Prescriber Number Identifier datatype profile - example value for Medicare Prescriber Number doesn't meet namespace format

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#301]
The [AU Base Practitioner Profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitioner.html) has an example value for the Medicare Prescriber Number identifier slice of `453221` - see [this line](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-practitioner.xml#L165).
However, the [supporting namespace page](http://ns.electronichealth.net.au/id/medicare-prescriber-number/) defines the format as
> The format of the value of the identifier is 8 characters, made up of:
> - 6 digits
> - the seventh character (the location) is alphanumeric
> - the eighth character (the check digit) is alphabetical

Suggest change to `049960CT` which is the value for this identifier found in the _Heathcare identifier HL7 implementation guide_ (SA HB 234-2012 - section 16 Medicare Prescriber number, pg 36) as well as found on [Grahame Grieve's blog](http://www.healthintersections.com.au/?p=721). 

Maybe even consider further defining the slice to add an invariant to verify the above format, using something like 
```
value.matches('^([0-9]{6}[A-Za-z0-9][A-Za-z])$'))
```

**Comment by oridashi** [comment]
this is not prescriber number format - which is just a number - looks like a Provider Number format which is different

**Comment by oridashi** [comment]
reviuew in MEDS wg

**Comment by dionmcm** [comment]
@robeastwood-agency can you check and confirm your suggested change given @oridashi 's comment?

**Comment by dionmcm** [comment]
At the Meds WG prescriber number comes after you have a provider number and as far as we are aware it is just a number, we're not sure what the scheme is. What @robeastwood-agency has suggested looks like a provider number, not a prescriber number (PBS).

**Comment by dionmcm** [comment]
https://www.mater.org.au/group/careers/files/careers/medical-employees/provider-and-prescriber-numbers.pdf

**Comment by dtr-agency** [comment]
> At the Meds WG prescriber number comes after you have a provider number and as far as we are aware it is just a number, we're not sure what the scheme is. What @robeastwood-agency has suggested looks like a provider number, not a prescriber number (PBS).
> 
> @robeastwood-agency can you review whether this answers/resolves this issue?

If the above is true and it is not an eight digit identifier made up of two alphanumeric characters then the registered namespace has this wrong here: http://ns.electronichealth.net.au/id/medicare-prescriber-number/index.html

This needs to be tracked down and resolved.

**Comment by dtr-agency** [comment]
A prescriber number is not location specific. It is issued by Services Australia (Medicare) to doctors, dentists, optometrists, midwives and nurse practitioners who are approved to prescribe PBS medicines under the National Health Act 1953.

See https://www.pbs.gov.au/info/healthpro/explanatory-notes/section1/Section_1_2_Explanatory_Notes

I think we need to improve the informative material for this identifier type - we should be consistent with the language used from Services Australia and PBS.

**Comment by dtr-agency** [comment]
Agreement to correct the namespace. This is in progress.
