### ISSUE TITLE
AU Base RelatedPerson.communication valueset binding needs updating

### ISSUE THREAD

**Issue by rodneycollins-agency** [hl7au/au-fhir-base#303]
Should the valueset binding for 'communication' be: https://healthterminologies.gov.au/fhir/ValueSet/common-languages-australia-2 (extensible)?

Are you able to update the RelatedPerson profile or would you like us to do so and create a Pull Request?

**Comment by dtr-agency** [comment]
This binding looks to be in AU Base - does this still need to be open?

**Comment by rodneycollins-agency** [comment]
Our Pull Request was merged. This issue has been resolved.
