### ISSUE TITLE
HealthcareService profile has  binding to 'v2 Identifier Type - AU Extended' as 'extensible'

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#31]
The valueset [v2 Identifier Type - AU Extended](http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-au-hl7v2-0203.html) is used for the various identifier slices, specifically as the terminology binding for the element `.identifier.type.coding`. The terminology binding is set to 'required' in all cases except for the [HealthcareService profile identifier slice for HPI-O](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-healthcareservice.html), where the binding strength is instead 'extensible'.

Not sure if that is a deliberate variation or not and therefore raising to be reviewed.

A PR can be logged if this should change to 'required'.

**Comment by oridashi** [comment]
Fixed as per referenced commit
