### ISSUE TITLE
Medication.ingredient.item -AMT slice on Coding only allows for AMT MP codes

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#311]
Medication.ingredient.item[x]:itemCodeableConcept.coding is sliced on value:system, with an
amtMP slice defined with binding to AMT Medicinal Product with the strength of required. This does not allow for any other SNOMED codes, e.g. substance codes, which is an issue. Maybe remove the slice and bind Medication.ingredient.item[x]:itemCodeableConcept to the AMT with the strength of preferred?

This is also an issue in STU3 AU Base Medication, please see https://github.com/hl7au/au-fhir-base-stu3/issues/6.

**Comment by RichardTON** [comment]
The binding strength is now preferred. The problem is resolved.

**Comment by dbojicic-agency** [comment]
The CodebleConcept binding should include both medications and substances. That suggests a new value set; it could use the [AMTMedicinalProduct](http://hl7.org.au/fhir/ValueSet/amt-mp-codes) and 
[Substance](https://healthterminologies.gov.au/fhir/ValueSet/substance-1).

**Comment by oridashi** [comment]
WG agree we should do this

**Comment by oridashi** [comment]
will fix this by changing the valueset to include substance and renaming

**Comment by oridashi** [comment]
updates values set for med wg review

**Comment by dbojicic-agency** [comment]
The value set been updated to include  medicinal products + substances. This issue can be closed.
