### ISSUE TITLE
Medications DataType profiles

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#312]
Slices -> datatype profiles for AMT, PBS, GTIN, MIMS
Apply to Medications, MedicationRequest, MedicationAdministration, MedicationDispense

**Comment by oridashi** [comment]
CodeableConcept profile - with all slices defined in the profile; need to test downstream profiles e.g. add a new terminolgy slice

**Comment by dtr-agency** [comment]
A single AU MedicationCodeableConcept Data Type profile that moves the slicing out of each of the Medications profiles is supported by the Agency.

**Comment by brettesler-ext** [comment]
f2f comment - approved already; @brettesler-ext to action

**Comment by brettesler-ext** [comment]
withdrawn as superseded by additional bindings discussions
