### ISSUE TITLE
Practitioner, PractitionerRole, Organization, HealthcareService DataType profiles

### ISSUE THREAD

**Issue by oridashi** [hl7au/au-fhir-base#313]
Convert identifier slices -> datatype profiles for IHI, HPI-I, HPI-O, NPI-O, Medicare Provider Number, Medicare Prescriber Number, Employee Number, CSP, NATA accreditation, NATA site number, PAIO, ABN, ARBN, ACN.
- IHI    (DONE)
- HPI-I   (DONE)
- HPI-O   (DONE)
- NPI-O  (DONE)
- Medicare Provider Number  (DONE)
- Medicare Prescriber Number  (DONE)
- Medicare Card Number (DONE)
- DVA Number identifier  (DONE)
- MRN Identifier (DONE)
- Employee Number (DONE)
-  CSP  (DONE)
- NATA accreditation  (DONE)
-  NATA site number  (DONE)
- PAIO  (DONE)
- ABN  (DONE)
- ARBN  (DONE)
- ACN  (DONE)

**Comment by oridashi** [comment]
+ Location also

**Comment by robeastwood-agency** [comment]
Following agreement at the 26 Feb 2020 PAWG meeting, a confluence page has been created to track/coordinate efforts to develop the Identifier datatype profiles: 
[au-fhir-base - creation of Identifier datatype profiles](https://confluence.hl7australia.com/display/PA/au-fhir-base+-+creation+of+Identifier+datatype+profiles)

**Comment by robeastwood-agency** [comment]
The Medicare Number datatype identifier has now been implemented (but not yet incorporated into any 'parent' profiles)

**Comment by robeastwood-agency** [comment]
Pull request created for IHI Identifier profile #378

**Comment by robeastwood-agency** [comment]
Pull request created for Medical Record Number Identifier profile #379

**Comment by brianpos** [comment]
PA-AU 1July2020: Investigation into using datatype profiles in slices approved and will move forward in cleaning these up, and applying to the resource profiles noted above.

**Comment by oridashi** [comment]
From #429 
## Background considerations
Background considerations (including what we are moving away from) are:
A. Defining an identifier by slicing inline in an AU Base profile (e.g. [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html)) - current
B.  Defining an identifier as a profile of the Identifier profile - future

### A. Defining an identifier by slicing inline in an AU Base profile 
#### Pros:

1. The definition of the identifier can be seen inline
1. Lets you test the uniqueness of definition of identifiers (within the limitations of the discriminator(s))

#### Cons:

1. The same identifier definition cannot be defined once and then reused, it must be redefined in each profile (AU Base or otherwise) to make use of the definition 
1. Introduces risk of diversion between different resource profile definitions of the same concept - harder and more costly to maintain
1. The AU Base resource profile itself can become heavyweight with a significant set of rules
1. Slicing is a useful conformance mechanism - in this case we are not interested in forcing all instance of an identifier of that type into compliance to one or more defined slices (as in the Vital Signs profiles as this is a 'Base' resource) so the slice is used to list 'options' at a level at which they _must still be constrained further for implementation_ purposes so slicing is an awkward mechanism if derivation is desired
1. Differentiation between identifier definitions (depending on how comprehensive the set is) is not possible with just one or two discriminators (assigner, system, type)
1. Derivation from the AU Base resource profile is inhibited:
    - the choice of discriminator is inherited and forces a conformance mechanism that may not suit
    - adds complexity and effort to place rules on the identifier element itself, e.g. all identifiers shall have a system
     - if a tight implementation profile is desired derivation from AU Base resource profile brings in the full set of identifiers slice that need to be removed or adjusted - adds complexity and effort
    - adds complexity and effort (and depending on discriminator may make it impossible) to define local profiles, e.g. for indicating that this is my MRN in my local system, or to add a new identifier type that is relevant e.g. a state-issued seniors card


### B.  Defining an identifier as a profile of the Identifier profile
#### Pros:
1. Define once and re-use - improves interoperability, validation, reduces risk and effort to maintain
2. Flexibility in the options for inclusion in a resource profile, AU Base or otherwise
3. Supports an easy means of modellers and implementers to use those identifier definitions in a manner of their choosing incl:
     - to apply the identifier definition to a new resource type or directly in a capability statement it can be referenced directly instead of having to recreate the definition in that new material

#### Cons:
1. Cannot see the full definition of the identifier inline in the AU Base resource profile


_The conversion of identifier slices in AU Base resource profiles to [Identifier](http://hl7.org/fhir/R4/datatypes.html#Identifier) profiles is in progress via [# 313](https://github.com/hl7au/au-fhir-base/issues/313)._

# Solution options
We need to assess the options for referencing / including identifier data type profiles in AU Base profiles of resources e.g. [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html).

Options to be considered:
1. Inclusion by guidance only - no direct reference in an AU Base StructureDefinition
2. Inclusion by adding as a set of allowed types on the identifier element (in addition to the base Identifier type)
3. Inclusion by slicing on the identifier element and defining a slice for each identifier we decide is relevant to the base resource profile
4. Inclusion by invariant

_NOTE: This decision will set a precedent to be applied to other data type profiles, e.g. how will [AU Base Address](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-address.html) be referenced / included in [AU Base Practitioner](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitioner.html)._

**Comment by dtr-agency** [comment]
Identifier data types have now been created. @oridashi this can be closed.

**Comment by RichardTON** [comment]
Identifier data types have now been created.
