### ISSUE TITLE
au-practitioner :: Add ValueSet for Qualification.code to suit Australian Localisation

### ISSUE THREAD

**Issue by udaychandrupatla** [hl7au/au-fhir-base#314]
There is a need for two slices for qualification.code to suit HL7 (example) valueset and Australian Localisation valuesSet as the existing HL7 example valueSet (http://hl7.org/fhir/R4/v2/0360/2.7/index.html) from FHIR does not really capture some key Australian qualifications such as AHPRA and MBBS.

Ci team from Australian Digital Health Agency have requested NCTS to add a valueSet to cater for Australian localisation of Qualification code in au-practitioner profile preferably from SNOMED.

A request has been made to include the following two codes as a minimum in the valueSet

- AHPRA

- MBBS

A second query is that does the Australian qualifications also need to cater codes from http://www.abs.gov.au/ausstats/abs@.nsf/mf/1220.0 ?

e.g.

![image](https://user-images.githubusercontent.com/32316167/66442848-ee397580-ea7f-11e9-83e4-ef9c20fcb128.png)

**Comment by oridashi** [comment]
Create 
CodeSystem - http://terminology.hl7.org.au/CodeSystem/v2-0360
* Degrees + Colleges  https://en.wikipedia.org/wiki/Medical_education_in_Australia
Valueset with above + http://terminology.hl7.org/CodeSystem/v2-0360|2.7
Publish in AU base
qualification.code binding preferred

**Comment by udaychandrupatla** [comment]
Hello Brett, 

After discussion with my team I want to make you aware that the solution of creating a valueSet with codes from http://terminology.hl7.org.au/CodeSystem/v2-0360 and http://terminology.hl7.org/CodeSystem/v2-0360|2.7 seems to be not we are looking for to satisfy the qualification codes because of the following reasons.

1.	The source of qualifications from https://en.wikipedia.org/wiki/Medical_education_in_Australia seems to be not complete to draw the Australian qualifications
2.	Having a binding of “required” by doing slices for qualification.code.coding is our preference rather than a binding of “preferred” for qualification.code with valueSet coming from above codeSystems

I suggest it would be a good idea to discuss this again at the next PAWG meeting with Brian P if possible.

Thanks, 
Uday

**Comment by brianpos** [comment]
Would be good to create some sample practitioners that have the spread of intended qualifications.
Even if its as a logical model for consideration.

**Comment by davidmckillop** [comment]
Discussed at the HL7 AU PA WG on 
- 23rd Nov 2019 [here](https://confluence.hl7australia.com/display/PA/2019-10-23+Minutes);
- 11th Nov 2019 [here](https://confluence.hl7australia.com/display/PA/2019-11-06+Minutes);
Also for consideration the [VhDir](http://build.fhir.org/ig/HL7/VhDir/index.html) has some extensions on this backbone element: http://build.fhir.org/ig/HL7/VhDir/StructureDefinition-practitioner-qualification.html

**Comment by davidmckillop** [comment]
Given the above discussions it will be interesting to see what is progressed for Practitioner.qualification in R5 core.  
However, following discussions with @oridashi  it would be good to have the:
a) AHPRA lists of qualifications made available/published, and versioned, and for the list(s) to be made into codesystem and value sets for use in the [AU Base Practitioner profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitioner.html).  Need to followup with @LB-Agency on how this may be progressed.
b)  a "Fellowship" slice on qualification in [AU Base Practitioner profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitioner.html) where the list of Australian College fellowships eg FRCPA, FRACP, FRACGP, etc could be made into a value set.  The contents of the slice would be the code for the fellowship plus the issuer details.  To be progressed in GitHub

**Comment by robeastwood-agency** [comment]
Another aspect of this regarding APHRA registration is to represent the AHPRA roles / sub-roles coding to go along with AHPRA number as qualification.

This has been added to the PAWG agenda for 12 Aug 2020.

**Comment by RichardTON** [comment]
http://hl7.org.au/fhir/ValueSet/au-hl7v2-0360
 and 
http://terminology.hl7.org.au/CodeSystem/v2-0360
are relevant

**Comment by oridashi** [comment]
lower priority at this stage - will check a PA WG

**Comment by oridashi** [comment]
Discussion : https://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4//CodeSystem-au-hl7v2-0360.html has been added - this can have further items added for other qualifications
action : http://terminology.hl7.org/CodeSystem/v2-0360 - is available for educational qualifications - add this as narrative in the AU Base Practitioner to reference this - no binding.
Issue  GitHub #463 covers college membership - look ther for outcome.

**Comment by oridashi** [comment]
KM to supply some narrative update for BE to add in

**Comment by mcguirek** [comment]
Proposed narrative to be added to Practitioner Usage Notes after the current section entitled AHPRA data:
### Qualifications
The above section describes how to include AHPRA professions and registrations in the qualifications backbone element.

Tertiary qualifications can be included in the qualification backbone element with a code taken from the international value set: http://hl7.org/fhir/R4/v2/0360/2.7/index.html.  There are no plans to add codes for Australian tertiary qualifications.  If no suitable code exists in the international valueset, a text representation of the qualification can be included without a coding.

Professional memberships (of colleges etc) can be included in the qualification backbone element using a text representation of the qualification without a coding.  Codes for Australian college memberships may be added to the Australian valueset in the future: http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-au-hl7v2-0360.html

**Comment by oridashi** [comment]
PAWG : narrative above is good; second paragraph adjusted to reflect codes have been added for colleges

**Comment by oridashi** [comment]
change now committed
