### ISSUE TITLE
Multiple profiles not opening in Forge R4

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#318]
6 profiles are unable to be opened in Forge, which displays the error 
```
Unable to cast object of type 'HL7.Fhir.Model.FhirUri' to type 'HL7.Fhir.Model.FhirString'
```

After investigation, this is due to problems with supporting extensions. When the extensions are opened in Forge a number of changes are imposed, presumably to bring up to R4-speed. With these changes saved, all of the affected profiles can then be opened in Forge.

The affected profiles are:
- au-encounter (ext: encounter-description, associated-healthcareservice)
- au-medication (ext: medication-brand-name, medication-generic-name, medication-type)
- au-medicationstatement (ext: medication-long-term, medication-brand-name, medication-generic-name)
- au-medlist (ext: author-related-person, change-description)
- au-patient (ext: patient-birthPlace, indigenous-status, closing-the-gap-registration, patient-mothersMaidenName, ihi-record-status, ihi-status, date-accuracy-indicator, patient-birthTime)
- au-relatedperson (ext: ihi-record-status, ihi-status)

**Comment by RichardTON** [comment]
These problems no longer occur.

**Comment by robeastwood-agency** [comment]
Closing as per above comment. Thanks
