### ISSUE TITLE
Patient profile: consider adding STU3 extension 'patient-mothersmaidenname'

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#32]
It may be worthwhile adding the STU3 extension for [mother's maiden name](http://hl7.org/fhir/extension-patient-mothersmaidenname.html) into the [HL7 AU base patient profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) as an optional element.

**Comment by oridashi** [comment]
fixed
