### ISSUE TITLE
How to record information that a medicine list contains medicine items packed in a dose administration aid?

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#320]
During recent consultation with external stakeholders, an ability to indicate in the medicine list for a patient that a patient is receiving medicines packed in a dose administration aid (DAA) was flagged as important, specially when there changes to the medicines regimen. For example, healthcare provider conducts a medicine review for a patient after a hospital discharge, comparing the details of the patient's existing medicines list with the list of medicines on a discharge and updating patient's medicines list accordingly; healthcare provider notes that some of the DAA packed medicine items changed and notifies patient's doctor, community pharmacist or prescribing provider for further instructions and action.

This  could be a flag, setting, statement or another indicator that informs the reader that the current medicines list contains medicines that are packed by a pharmacy in a DAA. Previously suggested solution (see https://github.com/hl7au/au-fhir-base/issues/293) is to include this information as a comment about the medicines list: e.g. 'Packed medicines: Yes', 'Packed medicines: No' and 'Packed medicines: Unknown'. 

Given the impact of this information on reducing the risk of problems and increasing communication between patient's and healthcare providers around medicines reviews and reconciliation,  please reconsider this requirement for solution and potential inclusion in the HL7 AU base content.

**Comment by RichardTON** [comment]
See https://confluence.hl7australia.com/display/MED/MED20191127

**Comment by RichardTON** [comment]
Pull request #328 has a suggested draft of a solution

**Comment by dbojicic-agency** [comment]
This will be progressed as the Agency specific content and not as part of HL7 AU; see Medications WG [meeting 12/05/2020 notes](https://confluence.hl7australia.com/display/MED/MED20200512+Meeting). 
HL7 AU Medications WG will progress [How to record information that a medicine item is packed in a dose administration aid? #397](https://github.com/hl7au/au-fhir-base/issues/397).
