### ISSUE TITLE
Represent patient's biological sex

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#321]
FHIR [Patient](http://hl7.org/fhir/R4/patient.html) model allows for recording administrative gender for a patient. It does not allow recording sex for a patient and it discusses various aspects of gender and sex, please see [Patient Gender and Sex](http://hl7.org/fhir/R4/patient.html#gender). 
Australian Government approach is to collect gender information. 

We have a requirement to record patient's biological sex (sex at birth) as well as gender. There seem to be lots of interest of addressing the issue of collecting both sex and gender information from other groups and willingness to progress clinical information systems in that directions. 

Recording biological sex is important in making clinical decisions, e.g. calculating of medicine dosages and laboratory test ranges by adjusting for an individual's typical hormonal history and anatomy, or can be used for timely health checks such as mammogram, pap smear, prostate exam etc. 

This issue is to discuss and come to a national agreement on how to record patient's biological sex.
The solution should align with the Australian Government Guidelines on the Recognition of Sex and Gender https://www.ag.gov.au/Publications/Pages/AustralianGovernmentGuidelinesontheRecognitionofSexandGender.aspx.

**Comment by oridashi** [comment]
talk to Primary Care project

**Comment by RichardTON** [comment]
I think that "sex at birth" is a term best avoided. 
LOINC has Sex assigned at birth (76689-9) a code for US birth certificates with preferred values Male, Female and Unknown. The word "assigned" makes it clear that it is a classification. 

LOINC also has Sex (46098-0) which seems closer to what we want.

**Comment by RichardTON** [comment]
LOINC Sex (46098-0) seems to be similar to [METeOR Person—sex, code X](https://meteor.aihw.gov.au/content/index.phtml/itemId/635126), [METeOR Person—sex, code A](https://meteor.aihw.gov.au/content/index.phtml/itemId/602450) and the approach of Australian Government Guidelines on the Recognition of Sex and Gender

**Comment by robeastwood-agency** [comment]
Link to HL7 International project page for [The Gender Harmony Project](https://confluence.hl7.org/display/VOC/The+Gender+Harmony+Project); which states
>This is project born of the ongoing frustration the ideas encompassed by "sex" and "gender" have never been easy to capture consistently within health models. Those terminologists among us have always said this topic was the quintessential example that proves "terminology is hard." This project is going to try use some tried and true approaches to how we model information (data elements, value sets, code systems) and use them to define/harmonize some aspects, likely not all, for representing sex/gender. This project will result in a balloted informational document that will define use-context collections that also include appropriate value sets. These artifacts can then be associated with model elements using binding parameters that are informed by the metadata the project will identify with each use context.

**Comment by dbojicic-agency** [comment]
Proposed changes to the existing draft profile have been provided via PR #581
* Observation.code
   * Changed SNOMED code from 268476009 |Sex of baby| to 1515311000168102 |Biological sex at birth|
   * Current design of having a pattern with a SNOMED code on Observation.code.coding and a defined LOINC slice is failing validation; the proposed design has a defined mandatory SNOMED and an optional LOINC slice; 
* Removed constraints on Observation.status fixed value and Observation.effective[x] minimum cardinality as the AU profile should leave these open and available to be constrained by specific implementation requirements;
* Observation.value[x] is bound to the [Biological Sex](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/biological-sex-1) value set with the strength of extensible

**Comment by RichardTON** [comment]
[Sex assigned at birth](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-sexassignedatbirth.html) is a part of supporting biological sex. It is not a complete solution.

Other concepts may need to be supported, e.g. Clinical Sex described in [Patient Gender and Sex](http://hl7.org/fhir/R4/patient.html#gender). 
I suggest that working on them can wait for community demand and this issue can be closed.

**Comment by dbojicic-agency** [comment]
More changes to [AU Sex Assigned At Birth](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-sexassignedatbirth.html) will be provided in a forthcoming PR. These changes are related to evolving the informational content to provide meaningful and consistent definition, usage, guidelines etc.

There are a few items for discussion in HL7 AU PAWG meeting, see [PA/2021-06-09+Minutes](https://confluence.hl7australia.com/display/PA/2021-06-09+Minutes) and [PA/2021-06-23+Agenda](https://confluence.hl7australia.com/display/PA/2021-06-23+Agenda): 

1. Suitability of LOINC 76689-9 - Sex assigned at birth defined as "The sex that was assigned and recorded on the birth certificate at the time of an individual's birth." as an alternative to SNOMED 1515311000168102 | Biological sex at birth, for representing  the concept of biological sex at birth defined as "Sex assigned at birth refers to what was determined by biological sex characteristics including genital and chromosome composition observed at birth or infancy. Sex assigned at birth is captured once for a person and is not expected to change within their lifetime."

Biological sex at birth and sex recorded on a birth certificate are different concepts. Noting that the values would be expected to align early in a person’s lifetime, the biological sex recorded on a person’s birth certificate may change over a person’s lifetime. LOINC 76689-9 - Sex assigned at birth seems suitable to represent the birth certificate sex but not for representing biological sex at birth. Could it be used as an acceptable translation though? 

An email has been sent to LOINC to ask them the code to use to represent the biological sex at birth if there is one. Depending on their response we might submit a request to add a new term to LOINC. 

2. Observation.performer allows the performer to be Practitioner | PractitionerRole | Organization | CareTeam | Patient | RelatedPerson. Consider constraining out the Patient as the patient and the patient is never expected to perform this obvservation,e.g. newborn making observation of their own biological sex at birth.

3. Observation.effective[x] type is constrained to dateTime only excluding Period, Timing and instant. While this seems acceptable and is easier on possible implementations to support one rather than four different types, consideration to be given whether this constraint is suitable to be made in the AU profile considering possible use cases and what it means to derived profiles; taking into account HL7 AU's AU Base principle to provide guidance not constraints.

**Comment by dtr-agency** [comment]
@dbojicic-agency, action from PA WG 23/06/2021 to note in the introductory material that we are seeking clarification from LOINC on the specificity and use of that LOINC code in a biological sex assigned at birth observation. Please include this in the forthcoming PR.

**Comment by dbojicic-agency** [comment]
Thank you @dtr-agency, the introduction material has now been updated to include above actions, as well StructureDefinition update to constrain Observation.performer to Practitioner | PractitionerRole | Organization | CareTeam | RelatedPerson. 
Updated content is in peer review at the moment, and expected to be offered to HL7 AU via pull request by the end of the week.

**Comment by dbojicic-agency** [comment]
The Agency terminology team looked into existing SNOMED CT concepts around investigating and reporting of different types of biological sex, e.g. gonadal, ductal, al or phenotypic etc via [FTR-1240](https://jira.aws.tooling/browse/FTR-1240).
The result of the analysis is that SNOMED CT provides general observable and finding concepts but there is no current content  that supports the types of specific biological sex values.

**Comment by dt-r** [comment]
Consideration on pre-adoption of international material. See meeting minutes from HL7 AU FHIR working group here: https://confluence.hl7australia.com/display/PA/2023-04-12+Minutes

**Comment by dt-r** [comment]
Further consideration in meeting minutes  here: https://confluence.hl7australia.com/display/PA/2023-04-26+Minutes

**Comment by brettesler-ext** [comment]
f2f comment - this is superseded by gender harmony inclusion currently in progress - propose to close

**Comment by hl7auadmin** [comment]
eVote: now under complete review by AU Core TDG; close issue

**Comment by brettesler-ext** [comment]
Closed as no longer relevant https://confluence.hl7.org/display/HAFWG/2024-04-10+FHIRWG+Meeting+Minutes
