### ISSUE TITLE
ig.xml uses undefined extensions

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#323]
ig.xml contains undefined extensions:

- http://hl7.org/fhir/StructureDefinition/igpublisher-folder-resource
- http://hl7.org/fhir/StructureDefinition/igpublisher-folder-pages

Define them or remove them

**Comment by robeastwood-agency** [comment]
Also noting that the respective values for these extensions are all absolute paths on a specific machine; ie 
```
<extension url="http://hl7.org/fhir/StructureDefinition/igpublisher-folder-resource">
    <valueString value="C:\Users\Administrator\Documents\GitHub\au-fhir-base\resources"/>
</extension>
```

**Comment by robeastwood-agency** [comment]
This content has since been removed as part of a ig.xml bugfix ticket (#325); via commit https://github.com/hl7au/au-fhir-base/commit/1343cd36d5059ae0f700b4b7ea1dec126794d6cc#diff-5239954e990dfe0d80bc915f92e318ca

This ticket can be closed @RichardTON

**Comment by RichardTON** [comment]
Great.
