### ISSUE TITLE
StructureDefinition-au-norelevantfinding :: incorrect use of fixedCodeableConcept on Observation.code

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#326]
The AU Assertion of No Relevant Finding profile fixed the value on Observation.code by using fixedCodeableConcept. The result of this is to prohibit use of other elements and attributes, and is not recommended for CodeableConcept, please see: http://hl7.org/fhir/R4/elementdefinition-definitions.html#ElementDefinition.fixed_x_
Please update to use recommended way of fixing values for CodeableConcept by using [ElementDefinition.pattern[x]](http://hl7.org/fhir/R4/elementdefinition-definitions.html#ElementDefinition.pattern_x_).

**Comment by oridashi** [comment]
changed to pattern c2f95ef - CI team please review

**Comment by dbojicic-agency** [comment]
Confirmed the use of pattern & closing this issue.
