### ISSUE TITLE
codesystem-au-hl7v2-0203 :: QA error re CodeSystem.valueSet

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#327]
The QA report includes this error for the codesystem-au-hl7v2-0203 resource:
> CodeSystem http://terminology.hl7.org.au/CodeSystem/v2-0203 has a 'all system' value set of http://hl7.org.au/fhir/ValueSet/au-hl7v2-0203, but doesn't have a single include

The responsible R4 element is CodeSystem.valueSet, for which the HL7 AU codesystem has this value (see [here](https://github.com/hl7au/au-fhir-base/blob/master/resources/codesystem-au-hl7v2-0203.xml#L27)):
```
<valueSet value="http://hl7.org.au/fhir/ValueSet/au-hl7v2-0203"/>
```
The R4 spec definition/comment of this element is:
> Definition: Canonical reference to the value set that contains the entire code system.
> Comment: The definition of the value set SHALL include all codes from this code system and only codes from this code system, and it SHALL be immutable.

This element is used when the referenced ValueSet is implicit, ie includes ALL and ONLY the concepts in the codesystem. As the valueSet for v203 combines the extended Australian codes with the international codes, this principle is broken, hence the error. When this specific node is removed, the error is eliminated.

There appears to be no overt functional impact related to this error, as the build can expand the relevant concepts etc. However, there are likely unintended consequences of retaining a technical defect. Making this technical correction eliminates the QA error but in so doing, loses the capability to represent an implicit value set. As a consequence, it is worth considering rewriting the value set in order to provide a implicit capability.

Also note that the identical problem is present for another codesystem, codesystem-au-hl7v2-0443

**Comment by robeastwood-agency** [comment]
Can this be discussed at the next PAWG, time permitting?

**Comment by robeastwood-agency** [comment]
Following the merge of the related PR (#338), the error no longer appears. However, it would still be worthwhile addressing any unintended consequences (mentioned in the original text of this issue) in a forthcoming PAWG.

**Comment by oridashi** [comment]
Satya's fix - believe this is correct and now fixed...

**Comment by robeastwood-agency** [comment]
The fix has been made successfully and the possible implications discussed at the [11 Mar 2020 PAWG](https://confluence.hl7australia.com/display/PA/2020-03-11+Minutes), with these notes taken:
- currently no implicit valueset on codesystem - fixes immediate issue with validation
- valueset for 0203 is hl7.org.au based url 
- if implicit valueset is needed for 0203 codesystem then will use terminology.hl7.org.au domain (not needed currently)

Closing
