### ISSUE TITLE
Improve presentation of documentation of identifier namespaces

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#330]
Identifier namespaces, such as ABN, are poorly displayed on their current pages, e.g. http://hl7.org.au/id/abn/
Improve the display.
The name spaces are http://hl7.org.au/id/abn, http://hl7.org.au/id/acn, http://hl7.org.au/id/arbn, and http://hl7.org.au/id/nata-accreditation

**Comment by oridashi** [comment]
fixed layout style issues
