### ISSUE TITLE
AU Base Organization: support for Australian Organization types

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#333]
Currently the [AU Base Organization profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-organization.html) does not change the default resource binding on element **Organization.type**: [OrganizationType](http://hl7.org/fhir/valueset-organization-type.html) ([example](http://hl7.org/fhir/terminologies.html#example)) 

There is an opportunity to provide better support for Australian organisation types, such as concepts appropriate for describing a kind of organisation or facility including organisational units, e.g. hospital, pharmacy, ward, specific types of hospital wards, insurance company, cleaning company, government dept, etc.

NCTS has made available a ValueSet based in SNOMED, which is https://healthterminologies.gov.au/fhir/ValueSet/healthcare-organisation-role-type-1
This binding is ready now to be incorporated into the profile.

Also, the [Australian and New Zealand Standard Industrial Classification](https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1292.0.55.0022006) (ANZSIC) code system is widely implemented but not yet available as a proper published code system, but is on the list of work for the NCTS. This code system is currently in use in the My Health Record, HI Service (and thus every system using the HI Service). It would be worthwhile considering this option as well, as it will be available some time in the (not sure when) future.

**Comment by brianpos** [comment]
Valueset not currently expanding, this seems like the correct path to be taking, and propose updating the binding strength to preferred or extensible if the values appear to cover the scope adequately and should be able to get wide support for them.

**Comment by oridashi** [comment]
recommend preferred for AU base

**Comment by RichardTON** [comment]
> Valueset not currently expanding, this seems like the correct path to be taking, and propose updating the binding strength to preferred or extensible if the values appear to cover the scope adequately and should be able to get wide support for them.

To expand value sets at healthterminologies.gov.au through a browser you have to be logged in. That can be done after clicking on the National Clinical Terminology Service link in the page header.

**Comment by RichardTON** [comment]
Both terminologies [Healthcare Organisation Role Type](https://api.healthterminologies.gov.au/integration/R4/fhir/ValueSet/healthcare-organisation-role-type-1) and [ANZSIC](https://www.abs.gov.au/ausstats/abs@.nsf/mf/1292.0) are now mentioned in the introduction to [AU Base Organization](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-organization.html). 

There is a current NCTS task to add ANZSIC to NCTS.

**Comment by RichardTON** [comment]
Is

**Comment by RichardTON** [comment]
We need a long-term strategy for terminology that includes guidance on dealing with alternate preferred terminologies. The solution used here may not be the best.

**Comment by dtr-agency** [comment]
We need to consider the implications of some of the technical options downstream, especially slicing in relation to derivation. For now, an update to the introductory material to provide a link to this value set is the next best placeholder. A new issue on looking into support for multiple terminologies in a Base profile needs to created.

**Comment by oridashi** [comment]
narrative present but not modelled - check with PA WG

**Comment by brianpos** [comment]
Consider how slicing without a discriminator could work (and provide the description)
In the AU base this specific set of terminology bindings aren't here for validation purposes.

**Comment by oridashi** [comment]
* Investigate how to deal with multiple preferred valuesets and how to slice/bind 
*** Organisation type needs a broader SNOMED valueset (beyond Healthcare service only)  - raise with NCTS**
*** Change the wording in narrative to 'recommended' rather than 'preferred'** 
*  Propose a combined valueset (preferred) which includes both ANZSIC and SNOMED valuesets in AU Base
* Profiles on this would need to create their own binding and cardinatlity rules as needed

**Comment by oridashi** [comment]
LB: ANZSIC draft codesystem will be published end of Apr - will seek feedback from PAWG

**Comment by dtr-agency** [comment]
To copy the usage notes paragraph on Organization type into the comments field of the Organization.type element in the profile. Ensure the hyperlinks render like hyperlinks.

Approved for action with @oridashi,  @davidmckillop please progress this via PR.

**Comment by davidmckillop** [comment]
The Organization profile "Usage notes" that were specific for the element Organization.type have been copied to the comment field of the Organization.type element.
