### ISSUE TITLE
AU Base Organization: support for more options in contact.purpose

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#334]
Currently the profile does not change the default resource binding for [Organization.contact.purpose](http://hl7.org/fhir/organization-definitions.html#Organization.contact.purpose): [Contact entity type](http://hl7.org/fhir/valueset-contactentity-type.html) ([Extensible](http://hl7.org/fhir/terminologies.html#extensible))

The current value set seems insufficient - would like to accommodate "emergency contact", "Out of hours".

**Comment by brianpos** [comment]
code: emerg-cont
Display: Clinical Emergency Contact
Definition: Contact to be used under emergency conditions?
I would like to see the definition expanded upon to get a better understanding under what type of conditions this would be used, and how it differentiates itself from the other contact types (BILL, Admin, HR, Press)

**Comment by RichardTON** [comment]
Related to #73

**Comment by dtr-agency** [comment]
We need to support a number of different contact purposes, including:
- contact for correction of records e.g. when sending an Organization in Composition.custodian or when correcting a DiagnosticReport
- contact for the retrieval of records, e.g. a practitioner calling QLD X-ray to send over results or one practitioner calling another to fax over some records

I am less interested in emergency contact but definitely interested in after hours for organisation - we have some requests for this in related to supporting care facilities.

**Comment by robeastwood-agency** [comment]
The related ticket #458 was extensively discussed at PAWG today, see [minutes](https://confluence.hl7australia.com/display/PA/2020-08-12+Minutes). 

Refer to the comment on #458

**Comment by dtr-agency** [comment]
Draft code system and value set here: https://confluence.hl7australia.com/display/PA/Contact+purpose+terminology

**Comment by dbojicic-agency** [comment]
The HL7 AU Base Organization profile has been updated to add Organization.contact.purpose binding to be to the new [Contact Purpose Extended ValueSet](http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-contact-purpose.html) with an extensible binding. 

More changes will be provided via another PR shortly: 

Existing example [Albion Hospital with Australian Business Number](http://build.fhir.org/ig/hl7au/au-fhir-base/Organization-example1.html) update demonstrate the inclusion of the following contacts: 
- phone number for medical records
- phone number and email for press enquiries
- email for Human Resources

The AU Base Organization profile will also include a reference to the newly created extension 
[Contact Purpose](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-contact-purpose.html) via link to the extension page and a usage statement on its use.
