### ISSUE TITLE
NATA Identifier datatype profiles (Site and Accreditation) - add constraints for NATA identifier value

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#335]
The AU Base Organization identifier slices all have invariants to ensure the quality of their respective values, except for the NATA slice.

Consider sourcing an authoritative source for the correct NATA number format and create invariant(s) to suit.

**Comment by oridashi** [comment]
believe this is just a number

**Comment by davidmckillop** [comment]
Received the following information from Andrew Griffin at NATA:
1)  NATA Number format:
- The number is Purely sequential and it is currently up to a 5 digit number - the highest accreditation number in use is approx. 20700. the highest site number approx. 25000
-  The number is unlikely to go beyond this anytime soon we have not restricted to 5 digits.
- NATA do not use any alphabetic characters pre or post the accreditation number.

2)   Accreditation number vs Site number:

The NATA accreditation number has 2 aspects -  Accreditation number and site number.
 
There is the accreditation number which could be unique to the standalone facility or can be unique to a corporate network of labs
 
The site number is unique to the actual site.
 
Examples are:
Corporate accreditation
 
Pathology Queensland - same Accreditation number but different site numbers

![GitHub-335](https://user-images.githubusercontent.com/19895989/74211558-16f6a380-4cdc-11ea-9b97-fd2834e8a71d.JPG)

Standalone:
![GitHub-335-standalone](https://user-images.githubusercontent.com/19895989/74211694-c764a780-4cdc-11ea-868b-7033b7047423.JPG)

The accreditation generally covers the whole lab e.g. chemistry, haematology, microbiology etc

**Comment by robeastwood-agency** [comment]
This was reassessed with the shift to identifier datatype profiles; specifically
- [AU NATA Accreditation Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-nataaccreditationnumber.html)
- [AU NATA Site Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-natasitenumber.html)

This query is still of outstanding for both of these datatype profiles.

**Comment by davidmckillop** [comment]
Issue raised with HL7 AU PA WG on [8th Apr 2020](https://confluence.hl7australia.com/display/PA/2020-04-08+Minutes) with the following considerations discussed:
- no definitive number of digits i.e. maybe up to 5 digits, but will roll over to 6 at some stage.
- only real constraint was digits;
hence decided to no add constraints to the NATA identifiers i.e. Accreditation number or Site number.
This issue can be closed.

**Comment by robeastwood-agency** [comment]
Closing issue as per above comment
