### ISSUE TITLE
Identifier datatype profiles - controls for known Identifier.value character lengths

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#336]
10 of the 23 Identifier datatype profiles now in the au-fhir-base (as of Aug 2020) have a maxLength constraint on their respective `identifier.value` values. For example:
- [AU HPI-O Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-hpionumber-definitions.html#Identifier.value)
- [AU DVA Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-dvanumber-definitions.html#Identifier.value)

There are a number of other Identifier datatype profiles, where the character length of the Identifier.value is known (and is the subject of an invariant), but the maxLength constraint is not used. For example
- [AU Australian Business Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-australianbusinessnumber.html)
- [AU Australian Company Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-australiancompanynumber.html)

And there are other Identifier datatype profiles where the Identifier.value does not have a specific length, and where of course maxLength would be incorrect to use.

This was originally raised when identifiers were represented using slices in the context of a slice that forced the Identifier.value length with an invariant and also had maxLength constraint. It seemed redundant to have invariants to force character length as well as the max length constraint.

This was raised & discussed at a PAWG on [15 Jan 2020](https://confluence.hl7australia.com/display/PA/2020-01-15+Minutes), with the outcome 
> Agreed, however think that a min length and max length would be preferred, as these can be used in user interfaces too, and remove the invariant for the length. (and any other identifiers with this type of restriction)

and later
> identifiers should have a max length if known; useful constraint for UI and databases; must be consistent with other constraints

No further work has been done on this matter.

These questions remain:
- how should the character length of identifier.value be constrained (for those identifiers where it is known)?
- are invariants useful to enforce _exact_ length?
- which Identifier datatype profiles would the above apply to?

**Comment by oridashi** [comment]
PA agenda item

**Comment by robeastwood-agency** [comment]
The maxlength constraint is present in all identifier profiles except for AU Care Agency Employee Identifier.
To be added as maxlength =16
