### ISSUE TITLE
AU Base Organization: consider Organization.contact extension reference for 0..* locations

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#337]
See a core spec enhancement request [FHIR-19726](https://jira.hl7.org/browse/FHIR-19726)
>Organization.contact.address should really be Organization.contact.location as the address structure is a subset of the location model. This would enable consistency and reusing location ID's

To support this, consider an extension on Organization.contact with reference for 0..* locations

**Comment by oridashi** [comment]
PA agenda item

**Comment by brianpos** [comment]
PA 26/2/20 The address on the organization contact is typically used for correspondence and can be PO Boxes, they are not related to service locations.
