### ISSUE TITLE
Change instances of "hl7.com.au" to "hl7.org.au"

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#342]
In the ...\git\au-fhir-base-r4\resources directory there are 39 instances in 21 files of "hl7.com.au" where this should be "hl7.org.au".

It's not a big deal as hl7.com.au re-directs to hl7.org,au, but it would be tidier to have all references to hl7.org.au rather than hl7.com.au.

**Comment by RichardTON** [comment]
hl7.com.au/fhir does not redirect to hl7.org.au/fhir

**Comment by RichardTON** [comment]
The copyright notice also uses .com.au

**Comment by oridashi** [comment]
Copyright notice should be hl7.com.au (that is the corporate entity) - hl7.org.au should be used for all standards artefacts referencing i.e. structurdefinition, codesystem, valueset urls etc.

**Comment by oridashi** [comment]
Quick fix 151420d - full license page is needed (new issue raised)
