### ISSUE TITLE
ig.json forces all SDs produced by the IGPublisher to version 2.1.0

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#346]
Why are all SDs produced by the IGPublisher forced to version 2.1.0?
I would expect that SDs start in the R4 version as v 1.0.0 or (if they appeared in STU3 AU FHIR Base) 2.0.0.

**Comment by oridashi** [comment]
version strategy applied so all resources in the package are labelled with the package version - not maintained individually
