### ISSUE TITLE
r4-au-bodyStructure :: Porting au-bodySite (au-base-stu3) to au-bodyStructure (au-base-r4)

### ISSUE THREAD

**Issue by udaychandrupatla** [hl7au/au-fhir-base#347]
While mapping BodySite.code.coding (au-bodySite {STU3}) to BodyStructure.location (au-bodyStructure {r4}), it has been observed there have been terminology binding change in STU3 au-bodySite from "required" to "extensible" in build versions (http://hl7.org.au/fhir/base/history.shtml)

http://hl7.org.au/fhir/base/2018Oct/StructureDefinition-au-bodysite.html (required) http://hl7.org.au/fhir/base/aubase1/StructureDefinition-au-bodysite.html (extensible)

The queries here are -

1. Is the terminology binding change intentional
2. When doing a pull request for r4 au-bodyStructure profile, which terminology binding to carry over from stu3 au-bodySite

**Comment by udaychandrupatla** [comment]
Since there was a terminology binding change occurred between the below STU3 versions - 
http://hl7.org.au/fhir/base/2018Oct/StructureDefinition-au-bodysite.html (required) http://hl7.org.au/fhir/base/aubase1/StructureDefinition-au-bodysite.html (extensible)

Kindly let me what is the right binding to be used for r4 au-bodyStructure profile?

Regards, 
Uday

**Comment by robeastwood-agency** [comment]
Query whether 'extensible' is appropriate given that it forces coding to only be SNOMED CT. Suggest discussion as to whether SNOMED CT is the only appropriate code system to record body structure. Therefore, consider 'preferred' as an alternative.

**Comment by davidmckillop** [comment]
Other SNOMED binding is AU Base profiles are "(preferred)" and this aligns with HL7 AU design principles of providing guidance and not constraining.
Hence change binding strength from "(extensible)" to "(preferred)".

**Comment by davidmckillop** [comment]
Any further issues relating to the GitHub ticket i.e. bindings, will be dealt with in GitHub #575 as a new value set needs to be developed to resolve the issue of having inactive codes in the HL7 FHIR core value set - raided in [FHIR-29810](https://jira.hl7.org/browse/FHIR-29810).

**Comment by dtr-agency** [comment]
This issue and the other are not fully equivalent. The raising of a new issue is not sufficient to close this. This issue can only be closed by resolution of the concern.
