### ISSUE TITLE
Validation on NPIO value

### ISSUE THREAD

**Issue by oridashi** [hl7au/au-fhir-base#348]
New - AU Base Practitioner Role: identifier:nationalProviderAtOrganisation has the format of "HPI-I@HPI-O", but currently has the constraint of "inv-npio-0: NPIO length is exactly 33 characters" which would allow any 33 characters.  Should there be further constraints such that characters 1-16 should conform to HPI-I, character 17 = "@" and characters 18 to 33 should conform to a HPI-O?

**Comment by robeastwood-agency** [comment]
Suggestion to start with a simple invariant (ie avoiding the heavy processing of 2 Luhn checks), by something like:
- starts with '800361'
- then has 10 digits
- then '@'
- then '800362'
- finishes with 10 digits
sort of like:
```
value.matches('^(800361)([0-9]{10})(@)(800362)([0-9]{10})$')
```

**Comment by dtr-agency** [comment]
@oridashi this looks like it can be closed both the slice and data type have this validation - and we've tested it.

**Comment by robeastwood-agency** [comment]
On the basis of the comment above, closing.
