### ISSUE TITLE
Organization profile - namespace resolution query for future v1.0

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#35]
There are a handful of identifier namespaces in the [organization profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-organisation.html) that are hosted in the hl7.org.au domain, but do not resolve.

It is understood that technically namespaces do not have to resolve, but this query is more for whenever the HL7 Au base IG is being readied for its v1.0 milestone, would it be preferable that they do resolve for v1.0?

The namespaces are:
- http://hl7.org.au/id/abn
- http://hl7.org.au/id/acn
- http://hl7.org.au/id/arbn

**Comment by oridashi** [comment]
placeholders added for all hl7.org.au/id system allocations; descriptions need to be added

**Comment by oridashi** [comment]
flesh out content + clean up needed

**Comment by oridashi** [comment]
adequate content added
