### ISSUE TITLE
Add Diagnostics profiles (port from STU3)

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#351]
The AU Base IG STU3 has the following profiles that would be very useful to have ported to this R4 IG:
- [AU Base Body Site](https://build.fhir.org/ig/hl7au/au-fhir-base-stu3/StructureDefinition-au-bodysite.html)
- [AU Base Diagnostic Report](https://build.fhir.org/ig/hl7au/au-fhir-base-stu3/StructureDefinition-au-diagnosticreport.html)
- [AU Base Specimen](https://build.fhir.org/ig/hl7au/au-fhir-base-stu3/StructureDefinition-au-specimen.html)
- [AU Diagnostic Observation](https://build.fhir.org/ig/hl7au/au-fhir-base-stu3/StructureDefinition-au-diagnosticobservation.html)
- [AU Base Diagnostic Procedure Request](https://build.fhir.org/ig/hl7au/au-fhir-base-stu3/StructureDefinition-au-diagnosticprocedurerequest.html)

**Comment by davidmckillop** [comment]
Merged to au-fhir-base [Add 5 diagnostics profiles (transform from STU3 aubase1.1)](https://github.com/hl7au/au-fhir-base/pull/350) #350
