### ISSUE TITLE
Safetynet on Patient

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#352]
there is a concession card issued by government
but the CN/SN numbers are an additional identifier
that affects your payment claim category on dispensing
needs it's own identifier in the AU base

basically if you or family reach 60 scripts in a year
you get an SN number then pay nothing for rest of year

clincial system has one entry slot for this
will hold either CN or SN
you can onyl hold one at a time

if i have a CN i only pay equivalent of concession card holder
instead of generaly threshold once i reach a certain $ spend on that i go to SN which is free for rest of year

alright we just need to make up some names for things and explain what goes in there... 
Patient.identifier:safetynetNumber
one slice drop the concession/entitlement
consistent format so assume string value with type extension that states concession or entitlement

we will need to allocate a url like http://hl7.org.au/id/safetynet-number for system

**Comment by dionmcm** [comment]
MEDs WG discussion

sounds like a person can have a temporary concession number allocated if they hit the safetynet sometime during a year.

If they already have a concession card, they get a SafetyNet number and medications are free for the rest of the year, at which point the SafetyNet number is no longer valid, however their concession card continues into the next year.

For a general patient with no concession card, if they hit the SafetyNet they get a temporary concession number for the rest of the year and medications are given at the concession rate. This too expires at the end of the calendar year.

Pharmacies are issued a stock of SN and CN cards which they issue when someone hits the SafetyNet.

i.e. if you have a concession card, when you hit SafetyNet you get a card with an SN number. If you do not have a concession card, when you hit SafetyNet you get a card with a CN number.

Coverage resource could be used, but is maybe not appropriate in this case. As an identifier we to model its temporal nature.

**Comment by oridashi** [comment]
see https://fhir.medicationknowledge.com.au Patient - will implement AU Base in line with this as Identifier datatype

**Comment by dt-r** [comment]
Outcome from [2023-09-28 AU Core TDG Agenda/Minutes](https://confluence.hl7.org/pages/viewpage.action?pageId=184920587) is a request for PBS Safety net number to be defined in AU Base enabling a standard defined use in FHIR.

**Comment by brettesler-ext** [comment]
f2f comment - this needs a project to provide information - this is not an identifier rather coverage information - propose this is placed on hold pending an ETP reconciliation project

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
