### ISSUE TITLE
AU Base PractitionerRole : consider PractitionerRole.code slice with ANZSCO codes 

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#353]
`PractionerRole.code` has preferred binding to [Practitioner Role](https://healthterminologies.gov.au/fhir/ValueSet/practitioner-role-1) value set. Please consider adding a slice with binding to [Australian and New Zealand Standard Classification of Occupations](https://healthterminologies.gov.au/fhir/ValueSet/anzsco-1) so that both terminologies are included in the HL7 AU base profile.

**Comment by brianpos** [comment]
Seems reasonable to include as an optional binding.

**Comment by RichardTON** [comment]
PractitionerRole now has a preferred binding to https://healthterminologies.gov.au/fhir/ValueSet/practitioner-role-1 (preferred)

**Comment by dtr-agency** [comment]
We need a long-term strategy for terminology that includes guidance on dealing with alternate preferred terminologies. The solution used here may not be the best.

We need to consider the implications of some of the technical options downstream, especially slicing in relation to derivation. For now, an update to the introductory material to provide a link to this value set is the next best placeholder. A new issue on looking into support for multiple terminologies in a Base profile needs to created.

**Comment by oridashi** [comment]
narrative only - discuss with PAWG if more action is needed

**Comment by oridashi** [comment]
* investigation on multiple valueset binding to element needs investigation see ticket #333 for similar issue
* narrative exists now in PractitionerRole usage notes
