### ISSUE TITLE
AU Base PractitionerRole : consider adding PractitionerRole.identifier HPI-I slice

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#354]
Please consider adding a `PractionerRole.identifier` slice for HPI-I.
Our FHIR models are influenced by CDA where the identifier for both PractitionerRole and Practitioner for an author participation are included in ClinicalDocument/author/assignedAuthor/assignedPerson/ext:asEntityIdentifier and is expected to be an HPI-I in the context of My Health Record.

**Comment by brianpos** [comment]
I think this should remain on Practitioner (the HPI-I uniquely idenfities the prac)
So would prefer not to include into the PracRole also.
We already have the NPIO (HPI-I@HPI-O) and this might cause confusion between the 2.

**Comment by brianpos** [comment]
(Also note that the HPI-O referred to above might be organizational (with flatish structures), but more likely at the location/site HPI-O
