### ISSUE TITLE
AU Base Practitioner Role Profile - metadata changes

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#358]
There are a couple of minor proposals for changes to the [AU Base Practitioner Role Profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html).

1) [StructureDefinition.date](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-practitionerrole.xml#L9) - currently 2017; suggest 2020

2) [StructureDefinition.fhirVersion](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-practitionerrole.xml#L20) - currently "4.0.0"; this should be "4.0.1"

3) [StructureDefinition.description](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-practitionerrole.xml#L18) - suggest remove terms "_administration details_". See #359

**Comment by dtr-agency** [comment]
In progress.
