### ISSUE TITLE
Profile description wording - suggested improvement

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#359]
Most profiles use wording as follows, that includes a variation of the text "This profile defines a xyz administration details structure that ...."

Suggest a simplification to remove the terms "administration details" which probably don't add much (other than to the word count).

See [AU Base PractitionerRole description](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-practitionerrole.xml#L18):
> This profile defines a practitioner role administration details structure that includes core localisation concepts for use in an Australian context.

**Comment by davidmckillop** [comment]
Resolved with PR #472
