### ISSUE TITLE
AU Medicare Provider Number Identifier datatype profile - consider validation on medicareProviderNumber value

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#360]
The [AU Base Practitioner Role Profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html) identifier slice on medicareProviderNumber has a fixed value on system as the namespace http://ns.electronichealth.net.au/id/medicare-provider-number. 

There is no validation on the value of the identifier, however the namespace page defines the format of the identifier, as 
>The format of the value of the identifier is 8 characters, made up of:
> - 6 digits, zero-filled
> - the seventh character (the One Practice Location Value (PLV)) can be alphanumeric excluding I, O, S, Z, and 0 (zero)
> - the eighth character (the check digit) can be one of Y, X, W, T, L, K, J, H, F, B, or A

Consider invariant(s) to validate the format of the value, noting that anecdotally the length of 8 characters may not be that future proof.

**Comment by robeastwood-agency** [comment]
This was reassessed with the shift to this being an Identifier datatype profile - link to AU Medicare Provider Number Identifier datatype profile: [http://hl7.org.au/fhir/StructureDefinition/au-medicareprovidernumber](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicareprovidernumber.html)

Note that this is still applicable.

**Comment by dtr-agency** [comment]
Validation would be significant effort for little value at the profile level. The Agency has assessed that they have no interested in this. Recommend closing.

**Comment by robeastwood-agency** [comment]
Agreed - little value to include. Closing
