### ISSUE TITLE
AU Base Practitioner Role profile - fixed value of NPIO

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#361]
The [AU Base Practitioner Role profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html) identifier slice for National Provider at Organisation Identifier, fixes the value of `PractitionerRole.identifier:nationalProviderAtOrganisation.type.text` as "NPIO"

The text in other identifier slices is the display content of table 0203 and hence should identifier:nationalProviderAtOrganisation.type.text be "National provider at organisation identifier" rather than "NPIO"?

**Comment by udaychandrupatla** [comment]
Pull request https://github.com/hl7au/au-fhir-base/pull/393 created to address this.

**Comment by robeastwood-agency** [comment]
Following PAWG discussion, this ticket is being closed as the change is not wanted.
