### ISSUE TITLE
AU Employee Number Identifier datatype profile - query constraint variations

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#362]
The [AU Base Practitioner Role profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html) identifier slice for employeeNumber has a number of aspects that differ from other slices, which may be intentional, but may also be design issues :
- the name is not ideal as some identifiers may not actually be numbers (and potentially they may not identify employees); suggest "Employee identifier" as a compromise.
- PractitionerRole.identifier:employeeNumber.type.text is 1..1 whereas others are 0..1
- PractitionerRole.identifier:employeeNumber.type.text has a fixedValue of "Employee Number"; this would seem to rule out local labels such as "QLD Health employee number" etc (vs mandating coding.display value)
- PractitionerRole.identifier:employeeNumber.assigner is 1..1; would the system value carry this information
- alternatively, as assigner would have the scoping organisation entity (ABN or HPI-O) then the system value may be redundant
- PractitionerRole.identifier:employeeNumber.assigner.display is 1..1 - also not present elsewhere
- consider improving the accompanying narrative such that the emphasis should be on providing a HPI-O scoped entity rather than a local one

**Comment by robeastwood-agency** [comment]
For PAWG discussion.

**Comment by robeastwood-agency** [comment]
This was reassessed with the shift to this being an Identifier datatype profile - link to AU Employee Number Identifier datatype profile: [http://hl7.org.au/fhir/StructureDefinition/au-employeenumber](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-employeenumber.html)

Note that this is related to (and possibly subsumed) by the expanded scope of ticket #302 ('AU Base Identifier datatype profiles: standardise constraints on type and type.text (and maybe others)')

**Comment by dtr-agency** [comment]
The structural concerns will be handled by #302. 

Narrative improvements in progress build here: [AU Employee Number](http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-176-intro-fixes-pensioner-commonwealth-medicare/StructureDefinition-au-employeenumber.html).
