### ISSUE TITLE
AU Base Practitioner Role profile - how to do out of hours contact

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#363]
Practitioner Role resource has the element `PractitionerRole.telecom` to represent the 
> Contact details that are specific to the role/location/service

We have been looking at various requirements regarding after hours contact numbers and are wondering how this would be managed in the context of the AU Base PractitionerRole profile; specifically how to tag a telecom instance as out of hours.

Eg the [National residential medication chart](https://www.safetyandquality.gov.au/our-work/medication-safety/national-residential-medication-chart)

**Comment by robeastwood-agency** [comment]
The related ticket #458 was extensively discussed at PAWG today, see [minutes](https://confluence.hl7australia.com/display/PA/2020-08-12+Minutes). 

Refer to the comment on #458

**Comment by dtr-agency** [comment]
Draft code system and value set here: https://confluence.hl7australia.com/display/PA/Contact+purpose+terminology

**Comment by dbojicic-agency** [comment]
HL7 AU Base Implementation Guide has been updated to include
- Extension [Contact Purpose](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-contact-purpose.html) on ContactPoint data type, used to represent the purpose for which a contact can be reached, e.g. after hours or billing, and related terminology resources:
- [Contact Purpose Extended](http://terminology.hl7.org.au/ValueSet/contact-purpose) ValueSet and
- [Contact Purpose](http://terminology.hl7.org.au/CodeSystem/contact-purpose) CodeSystem.

Update to the AU Base PractitionerRole to make use of this new extension will be provided shortly by another PR:

AU Base PractitionerRole profile will not reference the extension  directly from StructureDefinition. The extension will be included by guidance only - via a guidance statement on the use of extension on the AU Base PractitionerRole page and a link to the extension page. One or more existing examples will be updated to demonstrate the use of the extension.
