### ISSUE TITLE
AU Base Practitioner Role profile - query FMM level 3

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#364]
The AU Base Practitioner Role profile has a FMM level 3 - which was incremented around May 2019 (looking at the [commit history](https://github.com/hl7au/au-fhir-base/commit/80116914d782be0543d231724da4b900f55e860b#diff-cc746bacb4af43eae7e0f332d0ee8af6)). The description of FMM level 3 reads as more maturity than the current profile has - or this maybe just our impression form the outside.

This also applies to a number of other profiles.

**Comment by dtr-agency** [comment]
Subsumed by https://github.com/hl7au/au-fhir-base/issues/461.
