### ISSUE TITLE
HL7 V2 Table 0203 - Identifier Type (AU Extended) - consider Australianisation of descriptions

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#365]
Having a close look at the [AU Base PractitionerRole profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html), re the Australian Medicare Provider Number identifier slice. The fixedValue of type.code (via pattern) is `UPIN` with system "http://terminology.hl7.org.au/CodeSystem/v2-0203". Then looking at the [V2 Identifier Type - AU Extended valueset](http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-au-hl7v2-0203.html), `UPIN` appears in both of the included codesystems, the international 0203 as well as the AU 0203 extended set. I understand that this is not a issue as the combination of code and codesystem ensures uniqueness. However, is there potential for implementer confusion with 2 `UPIN` entries? 

Then looking at the descriptions in the [AU extended codesystem](http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-hl7v2-0203.html) set, it may be that the associated descriptions could do with some "Australianisation" eg to make this `UPIN` more distinct from the international counterpart; among others.

From our Australian perspective, we all know what is meant by "Department of Veterans' Affairs" or "Medicare assigned prescriber number", but thinking about off-shore vendors entering the Australian market, it may not be so clear.

For example, 
- _Australian Government_ Department of Veterans' Affairs Number
- _Australian_ Medicare assigned prescriber number

Suggest consideration be given to tweaking some of the descriptions associated with the codes to improve clarity.

**Comment by dtr-agency** [comment]
As part of correcting Medicare Prescriber Number to be PBS Prescriber Number the definition associated with the code PRES will be improved in the forthcoming PR for #493.

**Comment by dtr-agency** [comment]
In progress.
