### ISSUE TITLE
Needing a code - HL7 table 0203 code for NATA identifiers & LSPN

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#368]
The [AU Base Location profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-location.html) does not have a Location.identifier.type.coding.code. There isn't a good fit in [HL7 table 0203](http://hl7.org/fhir/R4/v2/0203/index.html) for a NATA number, an option could be the code "XX" - "Organization identifier".
Or create a new code??
See GitHub issue #[335](https://github.com/hl7au/au-fhir-base/issues/335) for details on "Accreditation number vs Site number".

**Comment by udaychandrupatla** [comment]
As per Grahame Grieve's guidance provided at http://www.healthintersections.com.au/?s=NATA "XX" from "2.16.840.1.113883.12.203" codeSystem and "Organization identifier" as displayName is applicable for CDA purposes, if we need to mandate a code and codeSystem in FHIR r4 NATA Identifier, it would be reasonable to use the same code ("XX" - "Organization identifier") instead of reinventing a new code.

**Comment by dtr-agency** [comment]
While XX works for a NATA accreditation number as a generic option, with the obvious negative that this type would be shared by many identifier slices, this is not as obviously acceptable a default option for NATA site. We need to be careful not to conflate a Location identifier (aka a site identifier) and an Organization identifier.

**Comment by davidmckillop** [comment]
In addition to the code issue described above, a NATA identifier data type is being created in #313.

**Comment by davidmckillop** [comment]
Agree with @dtr-agency that "XX" (Organization identifier) is not a suitable for a NATA Site number which is related to the location.  An organisation can can 1 or more NATA site numbers where the site number is specific to a location.  Hence, "XX" is not a good fit for Location.identifier.type.coding.code.  
Suggest creating a new code.

**Comment by dtr-agency** [comment]
@davidmckillop please find or propose a code for NATA Site and for NATA Accreditation.

**Comment by davidmckillop** [comment]
Following a discussion with @oridashi the following codes were selected to be put forward at the next [HL7 AU PA WG on the 26th August 2020](https://confluence.hl7australia.com/display/PA/2020-08-26+Minutes).
| Code     | Display              | Definition | 
| ----------- |-------------------------------| ----------------------| 
| NATAA      | National Association of Testing Authority Accreditation Number     | A unique NATA identifier for an organisation.| 
| NATAS     | National Association of Testing Authority Site Number    | A NATA identifier used for a specific site or location. | 
| LSPN      | Location Specific Practice Numbers    | An identifier used by the Department of Human Services to uniquely identify practice sites that provide diagnostic imaging and radiation oncology services.   | 

Note:  The codes NATAA and NATAS will be used to update the the AU Base Identifier profiles:
- [AU NATA Accreditation Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-nataaccreditationnumber.html)
- [AU NATA Site Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-natasitenumber.html)

LSPN will be used in a new AU Base identifier profile for "AU Location Specific Practice Number" -  refer to #476

**Comment by dtr-agency** [comment]
David McKillop, I have reviewed and the following is my feedback:

1. The code values look good - no changes suggested
2. The display value for LSPN should be singular; please change to "Location Specific Practice Number"
3. Recommend the display value for the two NATA codes takes the current fixed text value - aka NATA Site Number and NATA Accreditation. This is suggested for two reasons: the way this identifier is referred to throughout the material uses the acronym. Also the current use of text is a proxy display value that was only required while we did not have a code - it is suggested in https://github.com/hl7au/au-fhir-base/issues/471 to remove the fixed text so this addition of codes would support that move
4. Suggest more alignment between the Definitions and the wording used in the identifier data type profiles as the definition just describes the real world concept so they should be the same.
5. NATAA definition: A National Association of Testing Authorities (NATA) accreditation number associated with an accredited facility. A NATA accreditation number is associated with an organisation.
6. NATAS definition: A National Association of Testing Authorities (NATA) site number associated with an accredited facility. A NATA site number represents a specific location associated with an accredited facility, i.e. an organisation with a NATA accredication number.
7. LSPN definition: An identifier assigned by the Department of Services to uniquely identify practice sites that provide diagnostic imaging and radiation oncology services.

Response: Above changes excepted with further change to 7.:
"An identifier assigned by Services Australia to uniquely identify practice sites that provide diagnostic imaging and radiation oncology services."
