### ISSUE TITLE
Add support for Pharmacy Approval Number 

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#370]
Add support for a Pharmacy Approval Number via adding a new Identifier data type profile for the pharmacy approval number.

Approval Number or Approved Supplier Number (ASN) is a unique and universal number (within Australia) that identifies a specific pharmacy that is approved to provide prescription medications through the PBS.

**Comment by dbojicic-agency** [comment]
For more information: 
[Supplying Medicines — What Pharmacists Need to Know](http://www.pbs.gov.au/info/healthpro/explanatory-notes/section1/Section_1_3_Explanatory_Notes)

**Comment by dbojicic-agency** [comment]
Proposal for the pharmacyApprovalNumber identifier profile can be found here: https://confluence.hl7australia.com/display/PA/au-fhir-base+-+creation+of+Identifier+datatype+profiles.

**Comment by dtr-agency** [comment]
@dbojicic-agency this identifier type is of interest to SRA. Can you progress with determining the necessary structure, i.e. naming system, value format and rules, assigner, a suitable code etc. Please contact Agency BAs as needed for materials on the issuer and values.

**Comment by dbojicic-agency** [comment]
In progress with @dbojicic-agency .

**Comment by dtr-agency** [comment]
@dbojicic-agency, expect this would be registered in the ns.electronichealth.net.au space, we should combine the request for this as well as LSPN.

Note: in OID-based systems use 1.2.36.174030967.1.3.2.1.

**Comment by dbojicic-agency** [comment]
In review via https://jira.digitalhealth.gov.au/browse/SRAIG-164.

**Comment by oridashi** [comment]
reconcile - and finalise this with pull request

**Comment by oridashi** [comment]
this is good to merge once reviewed by Agency
