### ISSUE TITLE
AU Base Medication Request & AU Base Medication Dispense: add support for CTG annotation 

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#372]
Raised in a [Meds WG meeting](https://confluence.hl7australia.com/display/MED/MED20200303+Meeting); there is a requirement to add support for the CTG annotations for the computer generated prescriptions to the AU Base Medication Request and AU Base Medication Dispense profiles; this would be done as an identifier slice (or a profile). Computer generated CTG prescriptions are annotated with a a CTG alpha-numeric code, e.g. CTG11K.

**Comment by dbojicic-agency** [comment]
More information:
https://www.servicesaustralia.gov.au/organisations/health-professionals/services/medicare/closing-gap-pbs-co-payment-measure#a2
https://www.servicesaustralia.gov.au/organisations/health-professionals/topics/education-guide-closing-gap-pbs-co-payment-measure-supporting-indigenous-health/31811

**Comment by oridashi** [comment]
?? - will refer to Danielle Bancroft -  not sure where this is represented?

**Comment by brettesler-ext** [comment]
f2f comment - this is not serviced by a project suggest is an ETP requirement

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
