### ISSUE TITLE
AU Base Medication Request: add support for Reproductive Technology Accreditation Committee (RTAC) id

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#373]
Update AU Base Medication Request to Include support for RTAC Id. RTAC id identifies the IVF Reproductive Technology Accreditation Committee (RTAC) accredited unit number supplied for section 100 IVF claims.
http://www.pbs.gov.au/info/general/changes-to-certain-s100-programs

**Comment by oridashi** [comment]
see ETP implementation as extension - https://fhir.medicationknowledge.com.au/dev/StructureDefinition-rtacid.html

**Comment by oridashi** [comment]
PAWG voted to not include in scope for Oct 2022 ballot

**Comment by brettesler-ext** [comment]
f2f comment - this is not serviced by a project suggest is an ETP requirement;

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
