### ISSUE TITLE
AU Individual Healthcare Identifier datatype profile - hyperlinks for 2 IHI extensions resolve to STU3 page instead of R4

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#376]
In the [R4 AU Base Patient Profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) list of extensions, the hyperlinks for the 2 IHI extensions both resolve to their STU3 page rather than the R4 ones. 

The links are:
> - Patient.identifier(IHI): IHI Status [1] ==>> hyperlink as the canonical URL of the extension: http://hl7.org.au/fhir/StructureDefinition/ihi-status
> - Patient.identifier(IHI): IHI Record Status [1] ==>> hyperlink as the canonical URL of the extension: http://hl7.org.au/fhir/StructureDefinition/ihi-record-status

Interestingly the canonical URL of both extensions in a browser (outside of the IGs) resolve to the STU3 version.

Is this a redirect issue?

**Comment by robeastwood-agency** [comment]
With the transition to datatype profiles, this [AU Individual Healthcare Identifier profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-ihinumber.html) still demonstrates this issue.

**Comment by oridashi** [comment]
I (Brett) will follow this up

**Comment by RichardTON** [comment]
This is has been resolved. The extensions are no longer used by Patient, they are used in the extension [AU IHI](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-ihi.html) and there the links work just fine.
