### ISSUE TITLE
AU Individual Healthcare Identifier datatype profile - 2 IHI extensions have cardinality of 0..*

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#377]
The [AU Base Patient Profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) extensions for ihi-status and ihi-record-status have cardinality of 0..* in the diff table. 

![image](https://user-images.githubusercontent.com/32148917/77020578-fbb03f80-69cf-11ea-8751-43159cd11b2d.png)

Instead it is likely to be 0..1 instead. 

The way the extensions are linked in the Base Patient profile seem the same as other extensions that are showing up with 0..1 (e.g. Indigenous status). The structure of both extension StructureDefinition files are different to other extensions and its maybe something in there (and Forge does some structural changes).

**Comment by robeastwood-agency** [comment]
With the transition to datatype profiles, this [AU Individual Healthcare Identifier profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-ihinumber.html) still demonstrates this issue.

**Comment by oridashi** [comment]
fixed
