### ISSUE TITLE
Encounter.type binding update

### ISSUE THREAD

**Issue by LB-Agency** [hl7au/au-fhir-base#382]
There is currently no change to the binding for [Encounter.type](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-encounter-definitions.html#Encounter.type) compared with FHIR R4. There is an NCTS published value set available that could be used.

Suggest a preferred binding to https://healthterminologies.gov.au/fhir/ValueSet/encounter-type-1

**Comment by dbojicic-agency** [comment]
This value set resource includes permissible values that can be used to represent different types of health interactions, e.g, medicine review, GP consultation, GP annual check, Exploration of tendon of hand, etc. 
The value set is able to be used in STU3 for Encounter.type; in R4 Encounter.serviceType might be a better fit as type seems to be to be a bit more about how the service is done not what it is.

@brianpos, any thoughts on this?

**Comment by oridashi** [comment]
this terminology is just procedure list; not really suitable I think. Will discuss PAWG but think hold for now.

**Comment by oridashi** [comment]
PAWG discussed - needs more thought - leave on hold

**Comment by dtr-agency** [comment]
Revisited encounter type binding GitHub issue via https://jira.hl7australia.com/browse/FHIRIG-191

Confirmed with @oridashi that this is the appropriate concept tree in SNOMED CT. Recommend move forward with the binding post ballot to not introduce confusion on which parts of this profile are the agreed ballot content.

**Comment by dtr-agency** [comment]
Approved for action with @oridashi,  @davidmckillop please progress this via PR.

**Comment by davidmckillop** [comment]
The valueset  https://healthterminologies.gov.au/fhir/ValueSet/encounter-type-1 has been bound (preferred) to the [Encounter.type](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-encounter-definitions.html#Encounter.type) element.
