### ISSUE TITLE
Medical Record Number Identifier profile is missing important contextual information

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#385]
The recently added [Identifier profile for Medical Record Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicalrecordnumber.html) has only this narrative in its intro page:
>This identifier profile defines a Medical Record Number (e.g. ABN scoped, HPI-O scoped) in an Australian context.

To someone unfamiliar to these concepts, this could possibly be misinterpreted to be a single nation-wide MRN and that the only options are to be ABN scoped or HPI-O scoped.

The text should be expanded to clarify the intent is to represent a multitude of organisation's local identifiers, which may be done using  uses their own local system identifier namespace. But if that is not available then an organisation can add their HPI-O or ABN to construct a legal globally unique identifier system for their local identifiers.

Some candidate content (from which the above has been plagiarised) can be found here: https://github.com/AuDigitalHealth/ci-fhir-stu3/wiki/Frequently-Asked-Questions

**Comment by dtr-agency** [comment]
In progress build here: [AU Medical Record Number](http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-176-intro-fixes-pensioner-commonwealth-medicare/StructureDefinition-au-medicalrecordnumber.html)
