### ISSUE TITLE
Medicare card number Identifier datatype profile - narrative improvements to case

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#394]
The recent work on the [Medicare card number identifier profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicarecardnumber.html) (via #369 & #387) has highlighted that there is still some work to be done:

### 1) update the case of the entity to be "Medicare card number" (rather than title case)
This is apparent via the Services Australia website (see [here](https://www.servicesaustralia.gov.au/organisations/health-professionals/subjects/independent-review-health-providers-access-medicare-card-numbers) and [here](https://www.servicesaustralia.gov.au/organisations/health-professionals/services/medicare/hpos/services/find-patient))

This should be updated in the new identifier profile as well as the Medicare number slices in [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient-definitions.html#Patient.identifier:medicareNumber) and [Base RelatedPerson](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-relatedperson-definitions.html#RelatedPerson.identifier:medicareNumber) (so that artefacts are in sync)

### 2) update the profiles.md 
- with this above wording/case
- fix the hyperlink

Note that this point is already the subject of PR #392

**Comment by robeastwood-agency** [comment]
Reassessed with the transition to Identifier datatype profiles.

#### 1) The dataype profile
- the profile narrative (intro.md) still has some incorrect case for the identifier name which needs to be fixed
- the StructureDefinition file also has some corrections needed in various elements (short, definition, description)

#### 2) profiles.md
- is fixed

**Comment by dtr-agency** [comment]
In progress build here: [AU Medicare Card Number](http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-176-intro-fixes-pensioner-commonwealth-medicare/StructureDefinition-au-medicarecardnumber.html)
