### ISSUE TITLE
MedicationStatement.statusReason - consider adding terminology binding

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#395]
`MedicationStatement.statusReason` captures the reason for the current state of the MedicationStatement (e.g. completed, not-taken etc). 
Consider adding a terminology binding to value set specific to this new R4 element, that includes values from the [STU3 MedicationStatement.reasonNotTaken](http://hl7.org.au/fhir/aubase1.1/StructureDefinition-au-medicationstatement.html) [Medication Reason Not Taken](https://healthterminologies.gov.au/fhir/ValueSet/medication-reason-not-taken-1) value set and has extra values to cater for other statuses.

**Comment by oridashi** [comment]
agree - confirm in WG

**Comment by dbojicic-agency** [comment]
Confirmed in Medications WG [meeting 22/04/2020](https://confluence.hl7australia.com/display/MED/MED20200414+Meeting).
To be addressed via internal NCTS request FTR-948.

**Comment by oridashi** [comment]
this is not done - review with WG to add in this

consider retirement of long-term extension and use status reason in this valueset 710814002 to represent long term use...

**Comment by dbojicic-agency** [comment]
No known requirement at this stage, to be raised when there is a clear requirement.
