### ISSUE TITLE
How to record information that a medicine item is packed in a dose administration aid?

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#397]
In discussion with Medication WG, see meeting notes [here](https://confluence.hl7australia.com/display/MED/MED20200414+Meeting), Agency BAs and other stakeholders, and related to [How to record information that a medicine list contains medicine items packed in a dose administration aid? #320](https://github.com/hl7au/au-fhir-base/issues/320),  the need to record information that a medicine item is included in a dose administration aid (DAA) on the item level has been identified. 
Please consider adding a provision for this in the HL7 AU Base content.

**Comment by oridashi** [comment]
MED WG decision not to include DAA at list level in AU Base - agency modelling only

**Comment by oridashi** [comment]
this is part of packaging - need some usage guidance - will discuss

**Comment by oridashi** [comment]
pharmacy shared medicines list; medicines review  
- desire to indicate the DAA at the items level
- consider multiple DAA
- perhaps type of DAA
List as a DAA  - perhaps for planned/managed administration to individual and use Medication modelling for manufactured

**Comment by oridashi** [comment]
currently held - Agency to implement this in their scope
