### ISSUE TITLE
How to record the form of a dose administration aid a medicine item is packed in?

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#398]
This is related to [How to record information that a medicine item is packed in a dose administration aid? #397](https://github.com/hl7au/au-fhir-base/issues/397).
During recent discussion about a requirement to record information that a medicine item is packed in a DAA on the item level with the Agency BAs, it was suggested that an option to include a description of a DAA an item is packed in (e.g. sachets, blister pack) would be helpful.
Please consider adding this option to HL7 AU Base content.

**Comment by oridashi** [comment]
MED WG decision not to include DAA at list level in AU Base - agency modelling only

**Comment by oridashi** [comment]
this is to be discussed

**Comment by oridashi** [comment]
agency will model for their scope; marked as held

**Comment by brettesler-ext** [comment]
f2f comment - this item is not serviced by a project - propose to close pending specific request

**Comment by hl7auadmin** [comment]
eVote: this is not serviced by a project; suggest log in Jira and place on hold; close this issue

**Comment by brettesler-ext** [comment]
transferred to HL7 Jira https://jira.hl7.org/browse/FHIR-46308
