### ISSUE TITLE
Reporting Pathology Terminology (RCPA)

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#399]
The Royal College of Pathologists of Australasia (RCPA) have selected department specific terminology sets e.g. Chemical Pathology Reference Set, and Immunopathy Reference Sets.  These reference sets are to be converted into value sets with an overarching value set that is a union of these.  

When these value sets become available they will need to be bound to Observation.code in [AU Diagnostic Observation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnostic-observation.html).

**Comment by dtr-agency** [comment]
@davidmckillop - what is the status of this now?

**Comment by davidmckillop** [comment]
The following NCTS value sets have been from the RCPA reporting value sets:
- [ValueSet : RCPA - SPIA Chemical Pathology Terminology Reference Set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-chemical-pathology-refset-3?ui:source=search);
- [ValueSet : RCPA - SPIA Haematology Terminology Reference Set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-haematology-refset-3?ui:source=search);
- [ValueSet : RCPA - SPIA Immunopathology Terminology Reference Set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-immunopathology-refset-3?ui:source=search);
- [ValueSet : RCPA - SPIA Microbiology Serology Molecular Pathology Terminology Reference Set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-microbiology-serology-molecular-refset-3?ui:source=search);
Which are all combined into the  value set:
- [ValueSet : RCPA SPIA Pathology Reporting](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-pathology-reporting-1?ui:source=search)

This enables flexibility for those discipline specific laboratories e.g. Microbiology only lab, that may only need the specific discipline value set; yet allows the majority of laboratories who report on across all disciplines to use the combined value set.

The following guidance needs to be considered to be added to [AU Base Diagnostic Report](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnosticreport.html):
"_a pathology diagnostic report code is preferred to be a member of  [ValueSet : RCPA SPIA Pathology Reporting](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-pathology-reporting-1?ui:source=search) if the pathology laboratory reports from all pathology disciplines; however if the pathology laboratory is a discipline specific laboratory then it could use the appropriate discipline specific value set:
- [ValueSet : RCPA - SPIA Chemical Pathology Terminology Reference Set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-chemical-pathology-refset-3?ui:source=search);
- [ValueSet : RCPA - SPIA Haematology Terminology Reference Set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-haematology-refset-3?ui:source=search);
- [ValueSet : RCPA - SPIA Immunopathology Terminology Reference Set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-immunopathology-refset-3?ui:source=search);
- [ValueSet : RCPA - SPIA Microbiology Serology Molecular Pathology Terminology Reference Set](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/spia-microbiology-serology-molecular-refset-3?ui:source=search)._"

**Comment by davidmckillop** [comment]
E-mail reply from Vanessa Brown to questions raised above:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/DAVID~1.MCK/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/DAVID~1.MCK/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/DAVID~1.MCK/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/DAVID~1.MCK/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-AU link="#0563C1" vlink="#954F72" style='tab-interval:36.0pt;
word-wrap:break-word'>


<p class=MsoNormal>Hi David, <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Thanks for your email and providing the Github link for
me.&nbsp; <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<ol style='margin-top:0cm' start=1 type=1>
 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo1'><span
     style='mso-fareast-font-family:"Times New Roman"'>No, you haven’t missed
     anything.&nbsp; With respect to RCPA’s SPIA terminology mapping, a
     decision was made by the initial PUTS Project Steering Group in 2011 to
     adopt SNOMED CT for test requesting and LOINC for results reporting (and
     UCUM for representation of units).&nbsp; For this reason, the resulting of
     ‘panel’ terms has never been undertaken.&nbsp; I’m certain Michael, and
     perhaps Graham or Ken, would be able to provide you with all of the
     background on this decision, but I think you’re on the money with your
     assumption re algorithms. <o:p></o:p></span></li>
 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo1'><span
     style='mso-fareast-font-family:"Times New Roman"'>You are correct and I
     would think there was a reason why the individual reporting components for
     Micro were not included in the discipline-specific terminology reference
     set, but I don’t know myself. &nbsp;I could definitely include it in an
     updated version, but I would prefer to liaise with Michael before I
     undertook this task. <o:p></o:p></span></li>
 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo1'><span
     style='mso-fareast-font-family:"Times New Roman"'>The Cytopathology Report
     Information Model has been updated and is available via the PITUS website <a
     href="https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.rcpa.edu.au%2FLibrary%2FPractising-Pathology%2FPTIS%2FAPUTS-Downloads&amp;data=04%7C01%7Cdavid.mckillop%40digitalhealth.gov.au%7Cb2de4692014640f7c8a008d9489296c6%7C49c6971ed0164e1ab04195533ede53a1%7C0%7C0%7C637620616743144601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=fL4ilYLbjphvjVVs%2Fr391UuR6R6yhwfGCcAUFZlKAoU%3D&amp;reserved=0">https://www.rcpa.edu.au/Library/Practising-Pathology/PTIS/APUTS-Downloads</a>.&nbsp;
     Again, I don’t have the background as to why AP or Cyto terminology was
     not developed as per the other disciplines.&nbsp; Hopefully once all the
     outstanding LOINC and SNOMED CT terminology has been developed for the
     five Structured Pathology Reporting of Cancer protocols, the updated FHIR
     spreadsheets will provide a significant amount of terminology information
     for anyone undertaking this mapping work. <o:p></o:p></span></li>
</ol>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



I’ll keep   this email should funding approval for a new PITUS-related project eventuate.          Cheers,    VJC            ** The PITUS 18-20 Project is now   complete.  Should you wish to contact the College regarding PITUS or   SPIA, please email either pitus@rcpa.edu.au or Vanessa White, PMO Manager   vanessaw@rcpa.edu.au.   **        Vanessa Cameron    Senior Project Officer: PITUS 18-20      Pathology Information, Terminology   and Units Standardisation
--
website https://www.rcpa.edu.au/Library/Practising-Pathology/PTIS
The Royal College of Pathologists   of Australasia\|207 Albion Street, Surry Hills NSW 2010, Australia



<p class=MsoNormal><span lang=EN style='color:white;mso-ansi-language:EN;
mso-fareast-language:EN-AU'><![if !vml]><img border=0 width=135 height=41
src="file:///C:/Users/DAVID~1.MCK/AppData/Local/Temp/msohtmlclip1/01/clip_image002.gif"
style='height:.427in;width:1.406in' v:shapes="Picture_x0020_15"><![endif]></span><span
lang=EN-GB style='mso-ansi-language:EN-GB;mso-fareast-language:EN-AU'><o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-GB style='mso-ansi-language:EN-GB;mso-fareast-language:
EN-AU'><o:p>&nbsp;</o:p></span></p>


</body>

</html>
