### ISSUE TITLE
SNOMED CT AU Requesting Pathology Terminology

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#400]
The Royal College of Pathologists of Australasia (RCPA) have selected SNOMED-CT terminology to be used in requesting and reporting. 

When this value set become available it will need to be bound to:
1)  A pathology slice in [AU Base Diagnostic Report](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnosticreport.html).code; and 
2) A pathology slice in [AU Diagnostic Service Request](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnostic-servicerequest.html).code.

**Comment by dtr-agency** [comment]
@davidmckillop, I think this is a duplicate of #399 but with the wrong name

**Comment by davidmckillop** [comment]
Agree - that this is a duplicate/combination of #399 and #401 and can be closed.  #399 and #401 will remain active.
