### ISSUE TITLE
SNOMED CT AU Other Diagnostics Requesting Reporting terminology

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#402]
Looking to support a ValueSet resource whose permissible values represent types of diagnostic tests that are not categorised as either a pathology test nor a diagnostic imaging test. Common examples of these tests are:
- cardiology field - ECG, echo cardiogram, angiocardiography
- neurology field - EEG, EMG, evoked potentials, nerve conduction tests
- gastroenterology field - endoscopy, colonoscopy
- respiratory field - pulmonary function tests, 
- audiology - hearing tests
- sleep studies

These types of tests are those that are not done by either pathology or imaging providers, and are usually done by specialist providers (ie cardiologists, neurologists etc). And apart from the common tests above, it is expected that the relevant providers would have many more specialised tests that they would perform.

When this value set become available it will need to be bound to:

- A slice in AU Base Diagnostic Report.code
- A slice in AU Diagnostic Service Request.code
- A slice in AU Diagnostic Observation.code

**Comment by dtr-agency** [comment]
The value set will be defined using a SNOMED reference set.

The SNOMED CT-AU reference set is in development by the terminology team at the Agency and will be published in a forthcoming release of SNOMED CT-AU. 

Once the reference set is published this value set will be completed and made available. The expected canonical URL is: https://healthterminologies.gov.au/fhir/ValueSet/specialist-and-other-diagnostic-investigations-1

**Comment by davidmckillop** [comment]
The value set https://healthterminologies.gov.au/fhir/ValueSet/evaluation-procedure-1 have been bound to code with extensible binding.  This value set needs to be validated for it's usability for the other diagnostic reports.

**Comment by davidmckillop** [comment]
As the value set has been created the ticket can be closed.  The validation of the value set for use for other diagnostics will be done when more stakeholder input is provided with potential other diagnostic requests examples that need to be accommodated.

**Comment by dtr-agency** [comment]
The value set has been added into the introductory material of the following profiles:
* [AU Diagnostic Service Request]([http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnostic-servicerequest.html)
* [AU Diagnostic Observation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnostic-observation.html)
* [AU Base Diagnostic Report](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-diagnosticreport.html)
