### ISSUE TITLE
AU Base BodyStructure: bodyStructure - terminology binding

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#405]
This element should be bound to https://healthterminologies.gov.au/fhir/ValueSet/body-site-1 (extensible) instead of Binding: SNOMEDCTBodyStructures (example).

**Comment by robeastwood-agency** [comment]
@davidmckillop - would you mind checking whether this ticket can be closed. It looks like the change has been made.

**Comment by davidmckillop** [comment]
This issue has been resolved in AU Base BodyStructure i.e. the binding to BodyStructure.location is now:
Body site
Binding: https://healthterminologies.gov.au/fhir/ValueSet/body-site-1 (extensible)
