### ISSUE TITLE
AU Base ImagingStudy

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#408]
A new "AU Base ImagingStudy" is required to add to the existing diagnostic profiles.
This profile will build on [ImagingStudy](http://hl7.org/fhir/R4/imagingstudy.html).
Stakeholder input will be required to determine the required AU Base ImagingStudy constraints eg it is expected to support localised terminology and identifiers.

**Comment by davidmckillop** [comment]
The following imaging specific profiles have been created in AU Base:
- [AU Base Diagnostic Imaging Report](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-imagingreport.html) 
- [AU Base Diagnostic Imaging Result](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-imagingresult.html)

No further discussion has taken place with diagnostic imaging stakeholders to determine their requirements for a AU Base Imaging Study built on [ImagingStudy](http://hl7.org/fhir/R4/imagingstudy.html).

Park this issue until there is forthcoming requirements from the diagnostic imaging community.

**Comment by brettesler-ext** [comment]
f2f comment - this is not serviced by a project - propose to close this ticket until further specific input

**Comment by hl7auadmin** [comment]
eVote: this requires a specific imaging reports / records project; propose close

**Comment by brettesler-ext** [comment]
Closed as no longer relevant https://confluence.hl7.org/display/HAFWG/2024-04-10+FHIRWG+Meeting+Minutes
