### ISSUE TITLE
Base BodyStructure profile: morphology - terminology

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#409]
Need to investigate if a SNOMED CT AU ref set / value set is more appropriate than the current biding to SNOMEDCTMorphologicAbnormalities (example) in AU Base Body Structure  in the HL7 AU Base Implementation Guide.

**Comment by robeastwood-agency** [comment]
@LB-Agency has done some investigation on the default [SNOMED CT Morphologic Abnormalities](http://hl7.org/fhir/valueset-bodystructure-code.html) reference set and suggests that it does provide good coverage as it is. 
Therefore, suggest that the binding strength be updated to preferred.

**Comment by davidmckillop** [comment]
This issue is now resolved with the merge i.e. BodyStructure.morphology binding is now:
Kind of Structure
Binding: SNOMEDCTMorphologicAbnormalities (preferred)
