### ISSUE TITLE
AU Base Diagnostic Report - incorrect cardinality on performer

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#411]
The cardinality on AU Base DiagnosticReport.performer is currently 0..1 which is constrained from the derived HL7 International DiagnsoticReport.performer cardinality of 0..*.

We would like the cardinality constraint removed in AU Base DiagnosticReport.performer so that it then becomes 0..*.

**Comment by robeastwood-agency** [comment]
Commenced work on this change

**Comment by robeastwood-agency** [comment]
A pull request has been created addressing this issue - #414

**Comment by davidmckillop** [comment]
Issue resolved in merge from pull request #414
