### ISSUE TITLE
Old STU3 au-specimen profile (from /hold folder) should be removed 

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#412]
The R4 current build has an [AU Base Specimen profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-specimen.html), with its structureDefinition xml in the resources folder as is the usual. Its canonical URL is `http://hl7.org.au/fhir/StructureDefinition/au-specimen`.

The folder `./resources/hold` has the pre-R4-port STU3 version of the AU Base Specimen profile (see [here](https://github.com/hl7au/au-fhir-base/blob/master/resources/hold/au-specimen.xml)). This also has the same canonical URL as the official R4 profile.

Up until now that has not had any consequence - until we tried to derive from the AU Base Specimen profile using Forge. We do so with a link to a local copy of HL7 AU au-fhir-base repository. But, as there were 2 StructureDefinition files with the same canonical URL, Forge refused to derive, until I deleted my local copy of the STU3 variation. 

Given that this profile has been successfully ported to R4, the old STU3 variant in the "hold" folder can be deleted. 

We can progress this via a PR.

**Comment by oridashi** [comment]
done

**Comment by robeastwood-agency** [comment]
This ticket has been addressed via recent commits.
