### ISSUE TITLE
V2 0074 table support

### ISSUE THREAD

**Issue by oridashi** [hl7au/au-fhir-base#415]
Code system see: https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.12.74 and 4 Observation Reporting#4ObservationReporting-table0074
Create a codesystem for AU codes as per V2 spec
Allocate an OID for that codesystem
AU Valueset combining these
Will add OID to HL7 AU OID Registry as a shadow V2 table 
BE: raise a ticket on AU base

**Comment by oridashi** [comment]
OID added
CodeSystem and ValueSet not drafted

**Comment by dtr-agency** [comment]
The Agency is tackling this as part of the diagnostic work stream with the Agency terminology team.

**Comment by davidmckillop** [comment]
FYI - NCTS value set created 2020: [ValueSet : Pathology Diagnostic Service Category](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/pathology-diagnostic-service-category-1?ui:source=search).

Feedback from imaging people is that table 0074 is not a good fit for imaging and for the specialist and other diagnostics that is not well accommodated by HL7 Table 0074 - refer to ValueSet - Diagnostic Imaging category terminology for DiagnosticReport[ #55](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/55).  
Hence work is going on to develop value sets for imaging and specialists and other diagnostics - 
 refer to ValueSet – Service Section – support exchange and categorisation of Diagnostic Reports [#112](https://github.com/AuDigitalHealth/ci-fhir-r4/issues/112).

@oridashi is happy to have content referred to NCTS content which allows extensions and change which is tracked. 

@oridashi suggested the best options would be to have value sets for:
1) pathology - done
2) imaging
3) specialist and other diagnostics
4) a value set combining all of 1-3 above.
