### ISSUE TITLE
AU Base Patient profile - consider extension for birth plurality

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#417]
The [patient resource](http://hl7.org/fhir/patient.html) contains an element for multipleBirth - as a choice of 
- multipleBirthBoolean (yes/no) 
- multipleBirthInteger (eg '2' to indicate 2nd born)

However, there is no means to record the total number of births from one pregnancy - eg 2nd of **4**

Clinical and jurisdiction feedback indicate that this is a useful data point to collect, to facilitate identification.

This was discussed at the PAWG 2 years ago (see [here](https://confluence.hl7australia.com/display/PA/2018-01-17+Minutes) and [here](https://confluence.hl7australia.com/display/PA/2018-01-31+Minutes)), but subsequently dropped off the agenda.

As there are no available core extensions for this property, suggest consider creating an extension either using a simple integer value, or a CodeableConcept bound to a representation of the [AIHW birth plurality code set](https://meteor.aihw.gov.au/content/index.phtml/itemId/695308).

**Comment by oridashi** [comment]
WG is okay with this concept - but would prefer to have an integer value in an extension for Patient rather than coding; we would suggest raising a ticket with international to address this as a core extension (preferred) before making an Australian profile - unless urgent.

**Comment by oridashi** [comment]
ticket has been raised at international for WGM resolution - will wait for response

**Comment by oridashi** [comment]
approved at internation PA WG closed here

**Comment by robeastwood-agency** [comment]
**Closing the loop** - the core spec ticket [FHIR-27807](https://jira.hl7.org/browse/FHIR-27807) has recently been applied to R5 build with a new extension [patient-multipleBirthTotal](http://build.fhir.org/extension-patient-multiplebirthtotal.html)
