### ISSUE TITLE
Patient.contact - consider definitions (ie slices) for various use cases

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#418]
There are various scenarios regarding a patient contacts that may warrant explicit modelling within the AU Base Patient profile. 

For example, see the Australian National Child Digital Health Implementation Guide's [NCDHC Child Health Baby Patient Profile](https://build.fhir.org/ig/hl7au/au-fhir-childhealth/StructureDefinition-ncdhc-patient-baby.html), where there are a number of slices on contact such as:
- contactFederalAgency
- contactStateAgency

In the context of managing Children in Care, it would be worthwhile explicitly identifying the types of involved agencies.

**Comment by oridashi** [comment]
This needs review by CHWG to address specific need here; the coding is broad categorisation rather than explictly defining a use.  Not sure if this is about guardianship or other relationships. Follow up with Shovan.

**Comment by dtr-agency** [comment]
@robeastwood-agency - are what we looking at here broad considerations? or is this issue about considering children in care? The issue description and suggestion are tilted heavily towards only looking at agencies?

**Comment by dtr-agency** [comment]
We also need to provide a means for emergency contact, next of kin etc.

**Comment by robeastwood-agency** [comment]
The related ticket #458 was extensively discussed at PAWG today, see [minutes](https://confluence.hl7australia.com/display/PA/2020-08-12+Minutes). 

Refer to the comment on #458

**Comment by oridashi** [comment]
refer this to CHWG to allow them to make NCTS request for additions to http://terminology.hl7.org/ValueSet/contactentity-type and use extensionhttps://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4//ValueSet-contact-purpose.html

**Comment by oridashi** [comment]
work done
