### ISSUE TITLE
AU Base Patient - add better contact.relationship binding

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#419]
The [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) profile does not constrain the base resource binding on [Patient.contact.relationship](http://hl7.org/fhir/patient-definitions.html#Patient.contact.relationship) from the default extensible binding of [Patient Contact Relationship](http://hl7.org/fhir/valueset-patient-contactrelationship.html). The default v2-0131 codesystem is missing some options that would be useful to represent; such as 
- carer
- nominated representative
- guardian 

To support these additional concepts, the NCTS has developed (and published) a valueset that extends the values in the above v2-0131 codesystem. 
See https://healthterminologies.gov.au/fhir/ValueSet/contact-relationship-type-1

Looking to have this considered for inclusion in the AU Base Patient profile.

The additional concepts (from SNOMED CT) are:
- 133932002: Carer
- 1072531000168103: Nominated representative
- 394619001: Guardian 
- 1155871000168103: Kinship carer

**Comment by oridashi** [comment]
Discussed in PA WG:  Create a new valueset including v2-0131 + contact-relationship-type-1 and reference in AU Base Patient profile with extensible binding. Will progress.

**Comment by dtr-agency** [comment]
Note that contact-relationship-1 is already a value set that includes v2-0131 + the additional codes, i.e. it is defined as:
```
compose": {
    "include": [
      {
        "system": "http://snomed.info/sct",
        "concept": [
          {
            "code": "133932002"
          },
          {
            "code": "1072531000168103"
          },
          {
            "code": "394619001"
          },
          {
            "code": "1155871000168103"
          }
        ]
      },
      {
        "valueSet": [
          "http://hl7.org/fhir/ValueSet/v2-0131"
        ]
      }
    ]
  }
```

**Comment by dtr-agency** [comment]
ValueSet published: https://healthterminologies.gov.au/fhir/ValueSet/contact-relationship-type-3
PR forthcoming.
