### ISSUE TITLE
Add drug schedule

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#42]
https://en.wikipedia.org/wiki/Standard_for_the_Uniform_Scheduling_of_Medicines_and_Poisons TGA schedule needs to be added

**Comment by oridashi** [comment]
drug definition content only

**Comment by oridashi** [comment]
see https://fhir.medicationknowledge.com.au/dev/StructureDefinition-schedule-number.html

**Comment by oridashi** [comment]
this can be determined from drug database so is not required for ETP or summary; have put back on hold

**Comment by brettesler-ext** [comment]
f2f discussion: propose to hold pending ETP reconciliation

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
