### ISSUE TITLE
Pensioner Concession Card Number, Commonwealth Seniors Health Card Number identifiers - support for DVA issued healthcare cards?

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#427]
The following Identifier data types(referenced in AU Base Patient)  read as though they only support these cards as centrelink customer reference numbers (issued by Centrelink):

- Pensioner Concession Card Number 
- Commonwealth Seniors Health Card Number

DVA (Department of Veterans' Affairs) also issues Pensioner Concession Cards and Commonwealth Seniors Health Cards. According to the DVA website a person can only receive one card, either from DVA or Centrelink.

The identifier slices may be excluding the sending of DVA issued Pensioner Concession Cards and Commonwealth Seniors Health Cards identifiers... or forcing the wrong namespace to include them.

A DVA-issued card includes an individual's state-based DVA File number as well as a Unique Identifier Number (UIN) which is used for the Centrelink Concession electronic System (CCeS) to confirm concessions by most government agencies and utility providers.

Queries:
1. Is it sufficient to just make clear that the slices (or data type profiles) for Pensioner Concession Card Number and Commonwealth Seniors Health Card Number support the DVA issued cards but that the UIN must be recorded?
_UPDATE: Yes, this is sufficient to clarify that this is CRN with entitlement information_
2. If someone wants to indicate their DVA File No. as means of identification, can they use the DVA Number slice / profile where the card that number is published on is a Pensioner Concession Card Number or Commonwealth Seniors Health Card Number and not just a Gold, White, or Orange card?
_UPDATE: No, at this point Commonwealth Seniors and Pensioner Concession cards need to be sent with CRN._

See
* https://www.dva.gov.au/health-and-treatment/veteran-healthcare-cards/commonwealth-seniors-health-card
* https://www.dva.gov.au/health-and-treatment/veteran-healthcare-cards/pensioner-concession-card

**Comment by oridashi** [comment]
Lilac card is no longer in use - retained only for historical records 1987-1996
https://www.dva.gov.au/sites/default/files/files/consultation%20and%20grants/reports/ch19_22.pdf

HL7 AU 203 Table add
DVAU - DVA unspecified coding

**Comment by dtr-agency** [comment]
In progress build here: [AU Pensioner Concession Card Number](http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-176-intro-fixes-pensioner-commonwealth-medicare/StructureDefinition-au-pensionerconcessioncardnumber.html) and [AU Commonwealth Seniors Health Card Number](http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-176-intro-fixes-pensioner-commonwealth-medicare/StructureDefinition-au-cwlthseniorshealthcardnumber.html)
