### ISSUE TITLE
Identifier Data Type :: State issued Seniors Card

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#428]
Is there value in an identifier data type profile is made available that defines a state-issued Seniors Card?

Likely this would involve the setting of a meaningful type, and how to define a state assigner. Namespace would be state-specific and thus not set in the profile unless agreement was reached with the jurisdictions.

See:
* https://info.australia.gov.au/information-and-services/benefits-and-payments/older-australians/seniors-card

**Comment by oridashi** [comment]
discussed at PAWG - needs more details and examples to proceed; and work out use cases

**Comment by brettesler-ext** [comment]
f2f comment - volunteers to progress?
