### ISSUE TITLE
Identifier data type profiles - define the mechanism for reference / inclusion in AU Base profiles of resources

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#429]
# Feature description
We are looking to move to a robust and appropriate means of supporting identifiers in AU Base that serves the purposes of:
* providing national level agreement on an identifier, e.g. medicare provider number, that sufficiently describes a well formed identifier
* makes available a mechanism for the programmatic validation of an instance of an identifier if desired - but does not force conformance 
* enables implementers and modellers to make their own rules, i.e. profiling, about how to support these identifiers that meets the national agreement and supports specific implementation needs
* provides sufficient guidance on how and when to use the identifier definitions, e.g. an ABN is associated with an organisation

See background in #313

**Comment by dtr-agency** [comment]
# Solution options
We need to assess the options for referencing / including identifier data type profiles in AU Base profiles of resources e.g. [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) and [AU Base Practitioner](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitioner.html).

_NOTE: This decision will set a precedent to be applied to other data type profiles, e.g. how will [AU Base Address](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-address.html) be referenced / included in [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) and [AU Base Practitioner](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitioner.html)._

Options considered (in order of my preference):
1. Inclusion by guidance only - no direct reference in an AU Base StructureDefinition
2. Inclusion by adding as a set of allowed types on the identifier element (in addition to the base Identifier type)
3. Inclusion by slicing on the identifier element and defining a slice for each identifier we decide is relevant to the base resource profile
4. Inclusion by invariant

## 1. Inclusion by guidance only - no direct reference in an AU Base StructureDefinition
#### How
...

#### Pros
...

#### Cons
...

## 2. Inclusion by adding as a set of allowed types on the identifier element (in addition to the base Identifier type)
#### How
...

#### Pros
...

#### Cons
...

## 3. Inclusion by slicing on the identifier element and defining a slice for each identifier we decide is relevant to the base resource profile
#### How
...

#### Pros
...

#### Cons
...

## 4. Inclusion by invariant
#### How
...

#### Pros
...

#### Cons
...

**Comment by dtr-agency** [comment]
# Summary of solution options against desired features
All options should include the addition of content to [Guidance](file:///C:/work/git/au-fhir-base-r4/output/guidance.html) in the [HL7 AU Base implementation guide](file:///C:/work/git/au-fhir-base-r4/output/index.html) on using HL7 AU Base materials including derivation of AU Base resource profiles, and usage of data type profiles and extensions.

| Feature | Guidance only | Allowed types | Slices | Invariants |
| :---         |     :---:      |    :---: |  :---:      |    :---: |
| providing national level agreement on an identifier, e.g. medicare provider number, that sufficiently describes a well formed identifier   | Y   | Y   | Y     | Y   |
| makes available a mechanism for the programmatic validation of an instance of an identifier if desired - but does not force conformance  | Y   | Y   | N     |N   |
| enables implementers and modellers to make their own rules, i.e. profiling, about how to support these identifiers that meets the national agreement and supports specific implementation needs  | Y   | Y   | N     | N   |
| provides sufficient guidance on how and when to use the identifier definitions, e.g. an ABN is associated with an organisation   | Y   | Y   | Y   |  Y   |

**Comment by dbojicic-agency** [comment]
Some Zulip chats that discuss slicing: 
[Slicing non-repeating elements to define a choice](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Slicing.20non-repeating.20elements.20to.20define.20a.20choice)
[does re-slicing require a <slicing>](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/does.20re-slicing.20require.20a.20.3Cslicing.3E.3F)
[Slicing references to profiles](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Slicing.20references.20to.20profiles)
[slicing vs more profiles](https://chat.fhir.org/#narrow/stream/179177-conformance/topic/slicing.20vs.20more.20profiles)

**Comment by dtr-agency** [comment]
Decision taken at PA WG See [29 July 2020 Minutes](https://confluence.hl7australia.com/display/PA/29+July+2020+Minutes).

@dtr-agency will submit step 1 PR this week (move to replace inline slices with inclusion of data type profiles as Allowed Choices. ). To be implemented in:
- AU Base Healthcare Service
- AU Base Patient
- AU Base Practitioner
- AU Base Practitioner Role
- AU Base Related Person
- AU Base Location
- AU Base Organization

**Comment by robeastwood-agency** [comment]
With the excellent work detailed above, the agreement at [PAWG 29 Jul 2020](https://confluence.hl7australia.com/display/PA/2020-07-29+Minutes) and the follow up merged pull request (#459) - this issue can be closed.

**Comment by dtr-agency** [comment]
@robeastwood-agency - only step 1 has been completed; there is another step being progressed.

**Comment by mcguirek** [comment]
All aspects of this issue as reported appear to be resolved, so I believe this can be closed.
