### ISSUE TITLE
PAI-O Identifier - The example value provided 

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#432]
The example value of the PAI-O provided below is a test value and not a production value. 
https://github.com/hl7au/au-fhir-base/blob/6a4576a4228598467649516b208c06290dd05833/resources/au-organization.xml#L251

- The production value is in the format 8003640001xxxxxz, while the test value is the format 8003640011xxxxxz

This will also be applicable to the upcoming PAI-O identifier profile. 

So the question is do we want to change it to a production value?
Thanks.

**Comment by dtr-agency** [comment]
After chat with Brett; we don't think this will cause confusion. Decision to make no changes unless an issue arises.
