### ISSUE TITLE
Original Pharmacy Approval Number

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#44]
approval number recorded for prescription (RPBS, PBS)

**Comment by oridashi** [comment]
https://fhir.medicationknowledge.com.au/dev/StructureDefinition-original-pharmacy-approval-number.html original as part of request; 
where is the the pharmacy approval number for the current dispense?

**Comment by oridashi** [comment]
ready to draft

**Comment by oridashi** [comment]
PAWG voted to not include in scope for Oct 2022 ballot

**Comment by brettesler-ext** [comment]
f2f discussion: propose to hold pending ETP reconciliation

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
