### ISSUE TITLE
Contracted Service Provider (CSP) Registration Number - Luhn check invariant 

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#446]
Contracted Service Provider (CSP) Registration Number:
Do you think it will be appropriate to add the Luhn check invariant in the corresponding slice/datatype profile?

**Comment by robeastwood-agency** [comment]
Link to the CSP datatype profile: [http://hl7.org.au/fhir/StructureDefinition/au-cspregistrationnumber](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-cspregistrationnumber.html)

**Comment by dtr-agency** [comment]
Yes we should add Luhn check, and also add a code.
Propose adding to [HL7 V2 Table 0203 - Identifier Type (AU Extended)](http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-hl7v2-0203.html):
 | Code | Display | Definition |
| --- | --- | --- |
| CSPRN  | Contracted Service Provider Registration Number | A Contracted Service Provider (CSP) Registration Number is issued to organisations that participate in the My Health Record as a CSP. |

**Comment by dtr-agency** [comment]
In progress: http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-178-introduce-code-luhn-check-for-csp-registration-number/
