### ISSUE TITLE
Prescription Authority Number

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#45]
Authority and streamlined authority number for prescription

**Comment by oridashi** [comment]
ask Brian P - about MedicationRequest.identifier slice for authority numbers; not visible

**Comment by oridashi** [comment]
PAWG voted to not include in scope for Oct 2022 ballot

**Comment by brettesler-ext** [comment]
f2f discussion: propose to hold pending ETP reconciliation

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
