### ISSUE TITLE
Optional elements with a fixed value should use meaningWhenMissing

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#457]
Optional elements with a fixed value should use [meaningWhenMissing](http://hl7.org/fhir/R4/elementdefinition-definitions.html#ElementDefinition.meaningWhenMissing)
See https://chat.fhir.org/#narrow/stream/179177-conformance/topic/fixed.2Fpattern.20on.20min.20.3D.200/near/204867435

Examples include
* au-address
* lots of identifiers

**Comment by dtr-agency** [comment]
@RichardTON, I agree but query if this should always be set by AU Base? If there is an agreed definition for very specific profiles then sure. And to that end can you please propose the changes you recommend.

**Comment by RichardTON** [comment]
After a discussion Kieron McGuire, this is not only a bad idea, but impossible, as meaningWhenMissing cannot be set in a profile.
