### ISSUE TITLE
Review Maturity levels prior to ballot

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#461]
As per discussion with @oridashi the FMM levels need to be reviewed before ballot.

**Comment by dtr-agency** [comment]
Covers off https://github.com/hl7au/au-fhir-base/issues/364

**Comment by oridashi** [comment]
will do this as a general PAWG review

**Comment by dtr-agency** [comment]
Completed during [PA WG 07/07/2021](https://confluence.hl7australia.com/display/PA/2021-07-07+Minutes).
