### ISSUE TITLE
Australian College Fellowship slice for AU Base Practitioner.qualification

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#463]
Although there isn't a published codesystem or value set for the qualifications from the Australian Specialist Medical Colleges, there is a list of Specialist Colleges on the [Australian Medical Council Ltd](https://www.amc.org.au/accreditation-and-recognition/assessment-accreditation-specialist-medical-programs-assessment-accreditation-specialist-medical-programs/specialist-medical-colleges/) website.
It is understood that the fellowship qualifications issued by each college do not change eg. FRCPA from the RCPA, FRACP from the RACP, etc, so it would be useful to have:
a)  A definitive list of Australian Colleges - this would become the details for Practitioner.qualification.issuer
b) A definitive list of the qualifications issued by the college where the code would be the abbreviation of the fellowship e.g. FRACP, FRACP, etc. 
Will need to discuss with terminology people, including @LB-Agency, to determine viability and to progress.

**Comment by oridashi** [comment]
look at extending https://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4//ValueSet-au-hl7v2-0360.html  as HL7 Australia set - needs a bit of work - discuss with PA WG whether to attempt or put on hold for ballot

**Comment by oridashi** [comment]
PAWG Agreed  : to use  https://www.amc.org.au/accreditation-and-recognition/assessment-accreditation-specialist-medical-programs-assessment-accreditation-specialist-medical-programs/specialist-medical-colleges/ as the source for extra codes for https://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4//ValueSet-au-hl7v2-0360.html  content - current BE has volunteered to do this - review by Agency

**Comment by brettesler-ext** [comment]
already agreed - allocated to @brettesler-ext - new source location https://www.amc.org.au/accredited-organisations/assessment-and-accreditation-of-specialist-medical-programs/specialist-medical-colleges/

**Comment by brettesler-ext** [comment]
Moved to Jira [FHIR-46324](https://jira.hl7.org/browse/FHIR-46324)
