### ISSUE TITLE
Consider extension for Address GNAF ID

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#464]
The [Geocoded National Address File](https://psma.com.au/product/gnaf/) (GNAF) is the Australian standard for street addresses and includes an identifier for each listed street address.  It is proposed to introduce a GNAF Identifier data type and an extension on the Address data type for the inclusion of this identifier.

The Service Registration Assistant (SRA) Release 1 IG has such a data type and extension.  It is proposed to extend AU Base in a substantially similar manner. Refer: 
- https://sra.digitalhealth.gov.au/fhir/StructureDefinition-sra-address.html
- https://sra.digitalhealth.gov.au/fhir/StructureDefinition-sra-address-identifier-ext.html
- https://sra.digitalhealth.gov.au/fhir/StructureDefinition-sra-gnaf-identifier.html

**Comment by robeastwood-agency** [comment]
On PAWG agenda for 12 Aug 2020.

**Comment by dtr-agency** [comment]
I think this looks quite useful to agree at the AU Base level and could see the use for this across Agency specifications.

**Comment by robeastwood-agency** [comment]
This was discussed at PAWG today, see [minutes](https://confluence.hl7australia.com/display/PA/2020-08-12+Minutes). 

The outcome was
- agreement to introduce this into the HL7 AU au-fhir-base
- not to use the full identifier datatype structure but instead have the extension on AU base Address using the extension url and a string value
- a demonstration build to be developed by the Agency team and presented at the next PAWG for ratification

**Comment by dtr-agency** [comment]
Recent PA working group discussion resulted in a position to move to supporting a GNAF address identifier as a specific extension of type string on Address. Further consideration of address identifier data type needs has noted interest in supporting further identifiers on address. 

Want to re-examine this position on address identifiers as the recent decision is not the best fit for those requirements:
* it is preferred to support more than one identifier on Address (suggesting extension to add 0..* identifier to AU Base Address)
* both GNAF and Aus Post DPID identifiers are targeted for SRA and Agency... there may be others
the preference is to support both as 'identifiers' (suggesting data type profile for each)

**Comment by oridashi** [comment]
https://jira.hl7.org/browse/FHIR-28950 raised as a ticket

**Comment by mcguirek** [comment]
As this has been implmented in https://github.com/hl7au/au-fhir-base/pull/571, suggest this issue be closed.

**Comment by robeastwood-agency** [comment]
This has been implemented see above.
And is available here: http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-gnafidentifier.html
