### ISSUE TITLE
AU Assertion of No Relevant Finding - Observation.value slicing QA error

### ISSUE THREAD

**Issue by LB-Agency** [hl7au/au-fhir-base#467]
QA error reporting:
Profile http://hl7.org/fhir/StructureDefinition/ElementDefinition, Element 'StructureDefinition.differential.element[4].slicing.rules': minimum required = 1, but only found 0

Mandatory rules element missing from slicing.

**Comment by robeastwood-agency** [comment]
A PR is underway to address this issue
