### ISSUE TITLE
Need to create identifier profile for "Location Specific Practice Numbers (LSPN)"

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#476]
A [Location Specific Practice Numbers](https://www1.health.gov.au/internet/main/publishing.nsf/Content/AA062A120E052817CA257E65002535FC/$File/Fact%20Sheet%20-%20LSPN%20%20wcag.pdf)  is used by the Department of Human Services to uniquely identify practice sites that provide diagnostic imaging and radiation oncology services. Registered sites and bases for mobile equipment are allocated an LSPN.

It is appropriate that an identifier profile be created for LSPNs.

**Comment by dtr-agency** [comment]
Given this is a Services Australia identifier the namespace should be registered as part of http://ns.electronichealth.net.au/browse-identifiers.html. I'll kick off registering this and getting an OID.

**Comment by dtr-agency** [comment]
Note: LSPNs are in the format of digits, and have been assigned in an increasing integer pattern starting from 1. Can use https://www2.medicareaustralia.gov.au/pext/pdsPortal/pub/lspnSearchResults.faces to see various LSPNs.

**Comment by dtr-agency** [comment]
In progress: http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-172-create-hl7-au-identifier-data-type-profile-lspn/StructureDefinition-au-locationspecificpracticenumber.html
