### ISSUE TITLE
Handling address identifiers in AU Base - extension for each or one identifier extension

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#478]
Recent PA working group discussion resulted in a position to move to supporting a GNAF address identifier as a specific extension of type string on Address. See https://github.com/hl7au/au-fhir-base/issues/464.

Further consideration of address identifier data type needs has noted interest in supporting further identifiers on address. 

Want to re-examine this position on address identifiers as the recent decision is not the best fit for those requirements:
* it is preferred to support more than one identifier on Address (suggesting extension to add 0..* identifier to AU Base Address)
* both GNAF and Aus Post DPID identifiers are targeted for SRA and Agency... there may be others
* the preference is to support both as 'identifiers' (suggesting data type profile for each)

**Comment by dtr-agency** [comment]
# Solution options
Solution options considered for handling common address identifiers :
1. Each identifier as an extension of type string for that identifier type 
2. Each identifier as an extension of type Identifier for that identifier type 
3. A single Address identifier extension of type Identifier, uses data type profiles to define common address identifiers

**Comment by dtr-agency** [comment]
#### Rough proposal for a single identifier extension for address with common identifiers defined via identifier data type profiles (G-NAF & Aus Post Delivery Point Identifier):

1. Add to AU Base Address a HL7 AU extension for address identifier as 0..* 
2. HL7 AU Address Identifier extension of type identifier; 
    - valueIdentifier types to include a G-NAF Identifier data type profile and a AU Post Delivery Point Identifier profile
    - add a code for Address Identifier to [HL7 V2 Table 0203 - Identifier Type (AU Extended)](http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-hl7v2-0203.html)
3. G-NAF Identifier data type profile to include 
    - HL7 AU identifier namespace for G-NAF identifiers
    - add a specific code for this national address identifier to [HL7 V2 Table 0203 - Identifier Type (AU Extended)](http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-hl7v2-0203.html)
    - validation rules: a G-NAF can be a maximum of 15 characters
4. Delivery Point Identifier data type profile to include:
    - HL7 AU identifier namespace for AU Post DPID identifier
    - add a specific code for this national address identifier to [HL7 V2 Table 0203 - Identifier Type (AU Extended)](http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-hl7v2-0203.html)
    - validation rules: a DPID must be 8 digits

**Comment by dtr-agency** [comment]
Discussed at recent PA WG (See [2020-09-09 Minutes](https://confluence.hl7australia.com/display/PA/2020-09-09+Minutes)). Outcomes:
* Propose to international option 2 in issue #478 to include an Identifier type extension on Address  (to support at least DPID,G-NAF identifiers locally) with BE to action ticket for Address identifier at international; for WGM 
* Wait on international response prior to determining implementation option for AU Base

**Comment by oridashi** [comment]
https://jira.hl7.org/browse/FHIR-28950 raised as a ticket

**Comment by mcguirek** [comment]
As this has been implmented in https://github.com/hl7au/au-fhir-base/pull/571, suggest this issue be closed.

**Comment by dtr-agency** [comment]
The implementation of the PR differs substantially from design proposal - no updated design material can be found in HL7 AU JIRA, GitHub, or confluence.
