### ISSUE TITLE
AU Base MedicationRequest examples - QA errors

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#482]
[AU Base Medication Request](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationrequest.html) examples
* [medicationrequest-example0.xml](http://build.fhir.org/ig/hl7au/au-fhir-base/MedicationRequest-medicationrequest-example0.html),
* [medicationrequest-example1.xml](http://build.fhir.org/ig/hl7au/au-fhir-base/MedicationRequest-medicationrequest-example1.html) and
* [medicationrequest-example2.xml](http://build.fhir.org/ig/hl7au/au-fhir-base/MedicationRequest-medicationrequest-example2.html)

have QA errors reported due to normative changes including terminology changes between STU3 and R4; the issues are related to:

* undefined elements 'agent', 'onBehalfOf', 'doseQuantity', and 'allowed'
* unknown Code System 'http://hl7.org/fhir/v3/orderableDrugForm'
* not resolving URL value 'http://hl7.org/fhir/v3/orderableDrugForm' 
* missing 'MedicationRequest.substitution.allowed[x]'

**Comment by RichardTON** [comment]
Remaining QA errors are not in the examples. For example broken slicing in the profile affects all 3 examples (Element matches more than one slice) is broken, broken slicing in au-dosage affects example1 (Internal error: Could not match discriminator)
