### ISSUE TITLE
QA error - Missing jurisdiction declaration

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#484]
QA error `The resource must declare its jurisdiction to match the package id (hl7.fhir.au.base, jurisdiction = urn:iso:std:iso:3166#AU) (for FSH: 'jurisdiction: urn:iso:std:iso:3166#AU "null"')`

is reported against many profiles (Medications profiles,etc). 

The error is due to missing StructureDefinition.jurisdiction declaration:

```
<jurisdiction>
    <coding>
      <code value="AU"/>
      <system value="urn:iso:std:iso:3166"/>
    </coding>
  </jurisdiction>

**Comment by dtr-agency** [comment]
@dbojicic-agency - please fix. Though note that system should be before code.

**Comment by dbojicic-agency** [comment]
Thanks @dtr-agency, yes - the correct code is:
``` 
<jurisdiction>
    <coding>
      <system value="urn:iso:std:iso:3166"/>
      <code value="AU"/>
    </coding>
  </jurisdiction>

**Comment by dbojicic-agency** [comment]
In progress.
