### ISSUE TITLE
QA warning on Observation example norelevantfinding-example1.xml - display value spelling

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#491]
The example has this warning in the QA report:
```
Internal error: 
The display "No previous immunizations" is not a valid display for the code {http://snomed.info/sct}401179006
 - should be one of ["No previous immunisations","No previous vaccinations"] (from http://tx.fhir.org/r4)
```

Propose to adjust spelling to align with the SNOMED SCT AU spelling.

**Comment by robeastwood-agency** [comment]
A PR is underway

**Comment by dtr-agency** [comment]
I think we should consider grouping issues or not logging these as issues on the GitHub - this is going to get out of control if this level of content is tracked separately.
