### ISSUE TITLE
au-organization example improvements

### ISSUE THREAD

**Issue by udaychandrupatla** [hl7au/au-fhir-base#495]
The examples referenced for au-organization (e.g. Organisation.type) represent more HealthcareService rather than organisation, need to re look at them and update.

- Organisation with HPI-O
- Albion Hospital with Australian Business Number
- Devonport Family Medicine Clinic with Australian Business Number
- ACME Pathology with NATA Number, ARBN, ABN, ACN, HPI-O, PAI-O and CSP

**Comment by dtr-agency** [comment]
This issue is to be addressed within the next month or closed.
