### ISSUE TITLE
HCS - Extension for Languages spoken at Service

### ISSUE THREAD

**Issue by jaco-olivier** [hl7au/au-fhir-base#50]
**Extension** - au-communication
To provide support for outstanding aspects noted in Tracker: https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=15722 

Definition as implemented at this time: https://build.fhir.demo.nhsd.com.au/StructureDefinition-au-communication.html
Profile Usage Reference: https://build.fhir.demo.nhsd.com.au/StructureDefinition-nhsd-healthcareservice.html

**Comment by oridashi** [comment]
extension done - need some examples

**Comment by oridashi** [comment]
need examples + add to extensions page

**Comment by oridashi** [comment]
[bdd193f] completed
