### ISSUE TITLE
review all identifiers + telecom for examples

### ISSUE THREAD

**Issue by oridashi** [hl7au/au-fhir-base#503]
review and use good example instance data across IG; e.g. example.org ; example HPIO; not actual phone numbers

**Comment by dtr-agency** [comment]
PractitionerRole examples 0 through to 4 have been reviewed and fixed via https://github.com/hl7au/au-fhir-base/pull/520

The other examples are still a to do.

**Comment by RichardTON** [comment]
PR #530 includes this work for PractitionerRole's examples

**Comment by oridashi** [comment]
complete
