### ISSUE TITLE
Profiles au-practitioner, au-organization should have status = active

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#509]
Profiles labeled as FMM3, such as au-patient, au-practitionerrole, au-healthcareservice, au-location, au-relatedperson, have status = active, while
au-practitioner, au-organization have status = draft
There seems no reason for the difference
I suggest that all FMM3 profiles should be active.

**Comment by dtr-agency** [comment]
@RichardTON please fix.

**Comment by RichardTON** [comment]
@oridashi Any comments Brett?

**Comment by oridashi** [comment]
agree these should be all be status active

**Comment by RichardTON** [comment]
PR #512
