### ISSUE TITLE
au-medicareprovidernumber has incorrect link in introduction

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#513]
In the introduction for au-medicareprovidernumber a link is wrong.
In _This identifier profile defines a Medicare Provider Number[1] [2] in an Australian context._ the 2nd footnote goes to METeOR for medicare card not for medicare provider.

**Comment by dtr-agency** [comment]
This is already in progress via another ticket.

**Comment by dtr-agency** [comment]
There is a forthcoming pullrequest actioning issues in the intro.md of a number of data type profiles including this one.

**Comment by dtr-agency** [comment]
In progress build here: [AU Medicare Provider Number](http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-176-intro-fixes-pensioner-commonwealth-medicare/StructureDefinition-au-medicareprovidernumber.html)
