### ISSUE TITLE
AU Base Medication Dispense - normative defects

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#534]
The two identifier slice forces failure: it is not possible to satisfy the slice. There is a required binding to a value set, however the fixed code is not a member of that value set - and cardinality constraints allow only one code with one coding.

Required change to identifier:localDispenseIdentifier needs to do one or more of:
* remove the binding
* remove the coding cardinality constraints (too controlled anyway to not allow for translations)
* update to the correct R4 normative code system instead of the legacy STU3 system

**Comment by dbojicic-agency** [comment]
PR with a fix for this issue is forthcoming.

As agreed with @oridashi, identifier:localDispenseIdentifier slice will be replaced with [AU Local Dispense Identifier](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-localdispenseidentifier.html).

**Comment by dbojicic-agency** [comment]
In internal review with @dtr-agency.

**Comment by dbojicic-agency** [comment]
Review completed via internal pull request 146.
