### ISSUE TITLE
Problems with 6 hyperlinked examples

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#536]
There are 6 hyperlinks to examples on profile pages that are:
- not listed in the ig.xml; the consequence of this is that the links give 404 errors
- then raising numerous QA errors when these example are added into the ig.xml

The examples are:
- ~~[AllergyIntolerance/allergyintolerance-example1](https://github.com/hl7au/au-fhir-base/blob/master/examples/allergyintolerance-example1.xml) - on profile page [AU Base Allergy Intolerance](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-allergyintolerance.html), example "Self-reported allergy to eggs".~~  **Fixed via** #566
- [Composition/composition-different-authors](https://github.com/hl7au/au-fhir-base/blob/master/examples/composition-different-authors.xml) - on profile page [AU Base Composition](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-composition.html), example "Composition with some sections having a different section author to the composition author"
- [Composition/example0](https://github.com/hl7au/au-fhir-base/blob/master/examples/composition-example0.xml) - on profile page [AU Base Composition](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-composition.html), example "Patient’s preference upon death"
- [Immunization/immunization-example0](https://github.com/hl7au/au-fhir-base/blob/master/examples/immunization-example0.xml) - on profile page [AU Base Immunisation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-immunization.html), example "Non-administration of varicella-zoster live vaccine due to refusal"
- [Immunization/immunization-example1](https://github.com/hl7au/au-fhir-base/blob/master/examples/immunization-example1.xml) - on profile page [AU Base Immunisation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-immunization.html), example "Administration of a vaccine - record compliant with Australian Immunisation Register (AIR)"
- [Immunization/immunization-example2](https://github.com/hl7au/au-fhir-base/blob/master/examples/immunization-example2.xml) - on profile page [AU Base Immunisation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-immunization.html), example "Administration of a vaccine with administering provider and protocol"

The examples need to be added into the ig.xml and have their respective errors fixed.

**Comment by robeastwood-agency** [comment]
Point 1 re AllergyIntolerance/allergyintolerance-example1, has been fixed via #566 

All others are still an issue

**Comment by robeastwood-agency** [comment]
All of the errors in the examples (once processed by in the IG) are hangovers from the STU3 port. We are currently working on the 2 Composition examples, and then following that, the 3 Immunization examples (which have the most to do).

**Comment by jaymeemurdoch** [comment]
Pull request #606 is addressing the following composition examples only:

- Composition/composition-different-authors - on profile page AU Base Composition, example "Composition with some sections having a different section author to the composition author"

- Composition/example0 - on profile page AU Base Composition, example "Patient’s preference upon death"

Immunization examples will be addressed separately.

**Comment by jaymeemurdoch** [comment]
Currently working on immunization examples.

**Comment by jaymeemurdoch** [comment]
Outline of actions:

**Example 0**
* notGiven & explanation.reasonNotGiven removed (STU3) and replaced with status & statusReason (R4). Status also amended as per changed allowable values.
* date (STU3) replaced with occurenceDateTime
* practitoner.role and practitioner.actor (STU3) replaced with performer.function and performer.actor (R4). Referenced CodeSystem also amended to R4 version. 

**Example 1:** 
* Remove notGiven (STU3) as not required in R4.
* date (STU3) replaced with occurenceDateTime (R4). 

**Example 2:**
* Remove notGiven (STU3) as not required in R4.
* date (STU3) replaced with occurenceDateTime (R4). 
* practitoner.role and practitioner.actor (STU3) replaced with performer.function and performer.actor (R4).  Referenced CodeSystem also amended to R4 version.
* vaccinationProtocol.doseSequence and vaccinationProtocol.targetDisease removed (STU3) and replaced with protocolApplied.targetDisease and protocolApplied.doseNumberPositiveInt (R4).

**IG**
* Added the 3 examples to IG.

**Comment by jaymeemurdoch** [comment]
Confirming immunization examples have already been included in ig.xml and QA errors resolved. This issue can now be resolved.

**Comment by robeastwood-agency** [comment]
Closing issue as per above comment by @jaymeemurdoch
