### ISSUE TITLE
AU ETP Vendor Identifier - name & url state 'vendor identifier' but this is a 'prescription identifier'

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#544]
The title, id, url need to clarify this. It reads as an identifier for a vendor.

Probably more 'ETP Vendor Assigned Identifier' or 'ETP Vendor Assigned Prescription Identifier'. Consider the canonical url:
> http://hl7.org.au/fhir/StructureDefinition/au-etpvendorprescriptionidentifier

**Comment by dtr-agency** [comment]
Discussed and will edit to become ETP Prescription Identifier - id, title, name, url & intro.md.

**Comment by robeastwood-agency** [comment]
This is underway in a forthcoming PR

**Comment by dtr-agency** [comment]
Closed by https://github.com/hl7au/au-fhir-base/pull/549
