### ISSUE TITLE
Establish a value set for coded ethnicity

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#559]
### The issue
To support exchanging ethnicity data it is preferred to have a single, agreed, well-defined terminology adopted for use and available as at least preferred in AU Base materials (See also #598). 

Some obstacles to this:
- there is no currently adopted, or widely agreed, national terminology for ethnicity in healthcare in Australia. 
- there is no suitable national terminology available for adoption as-is
- what is being used across Australia by each jurisdiction and different vendor is fragmented and not available for adoption

### Terms and definitions
The terms and definitions from the ABS material are adopted for use.

**Ethnicity** 
Ethnicity refers to the shared identity or similarity of a group of people on the basis of one or more distinguishing characteristics. Ethnicity includes ATSI (Aboriginal and Torres Strait Islander) groups. [ABS Australian Standard Classification of Cultural and Ethnic Groups (ASCCEG) 2019](https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/2019). 

**Ethnic Identity**
Identification with an ethnicity
The information structure will support exchange of "one or more ethnicities with which a person identifies".

NOTE: Ethnicity is applicable to individuals, groups of individuals, and as a characteristic of some other type of concept such as a service or a device or a role.

#### No obvious suitable terminology available as-is
There doesn’t look to be suitable terminology for ethnicity in the Australian healthcare context at a national level that is ready to go and fit for purpose. 

SNOMED CT has a value for ethnic group (372148003); the available concepts and grouping are not suited to Australia, e.g. no concept for Torres Strait Islander, and a single concept for Australian Aboriginal is grouped with South Asian AND/OR Australian aborigine. Too coarse-grained for supporting delivery of targeted healthcare and services.

Things that might be mistaken for suitable terminologies include:
* The ABS's [Australian Standard Classification of Cultural and Ethnic Groups (ASCCEG)](https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/2019) which is a classification, not a terminology. As a classification it includes terms that are not suitable for a terminology, such as 1599 Polynesian, nec (nec='not elsewhere classified'). There are 300 odd entries, majority are too coarse-grained for supporting a healthcare context, e.g. only two entries for Australian indigenous groups.
* The ABS's [ASCCEG coding index](https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/2019#index-for-coding-responses), maps 1000 commonly used terms for ethnicity to terms in the ASCCEG. It includes alternative names, synonyms and misspelt terms. Some terms aren’t aligned to the terms used by members of the groups they are intended to identify and it is not fine-grained enough.

**Comment by oridashi** [comment]
Preferred terminology is Coding with a terminology is preferred, where possible.
Value set: ABS 1249.0 - Australian Standard Classification of Cultural and Ethnic Groups (ASCCEG), 2019.

**Comment by oridashi** [comment]
PAWG - LB : will follow up to get on backlog

**Comment by oridashi** [comment]
PAWG - RE to follow up with LB

**Comment by robeastwood-agency** [comment]
A backlog ticket has been created by LB in the internal NCTS ticketing system.

**Comment by RichardTON** [comment]
# ** Work in Progress**

# Proposed solution

The value set is used for coding ethnicity in an Australian context. Note that there are cases where coding ethnicity is not appropriate. See discussion in #598. 

Initially binding to the value set from Ethnicity Code will be "example". 

A preferred value set needs to be developed by a group able to engage in wide consultation with jurisdictions and industry.

Add to HL7 AU/NCTS a value set Ethnicity to identify appropriate codes for ethnicity in an Australian context. This will be an example value set until one good enough to be preferred can be developed.

## ValueSet: Ethnicity
Item|value 
-|-
Defining URL|http://terminology.hl7.org.au/ValueSet/ethnicity
Name|Ethnicity
Definition| Values used to encode ethnicity in an Australian context.
Logical Definition| All values from [Australian Standard Classification of Cultural and Ethnic Groups (ASCCEG)](https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/2019).

**Comment by RichardTON** [comment]
The way AU Base currently forces all resource versions to be 2.1.0 gives an incorrect version for the proposed code system resource.

**Comment by brettesler-ext** [comment]
see other issue discussion required: https://github.com/hl7au/au-fhir-base/issues/598

**Comment by brettesler-ext** [comment]
Added to Jira [FHIR-46325](https://jira.hl7.org/browse/FHIR-46325)
