### ISSUE TITLE
Gender Identity - consider using core extension

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#560]
[Gender Identity](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-gender-identity.html) has no binding to a value set

**Comment by robeastwood-agency** [comment]
Also noticed that there is a core extension for gender identity ([genderIdentity](http://hl7.org/fhir/extension-patient-genderidentity.html)) which does have a valueset binding, albeit 'example' but looks worthwhile nonetheless. And the patient resource page does include narrative recommending the use of this extension 
> Gender Identity - an indication from the patient about what gender they consider themselves to be. This can influence how the patient prefers to be addressed by care providers and other individuals. The standard genderIdentity extension may be used to communicate this property. This extension is appropriate when the gender identity is openly known.

I suggest that this core extension be a preferred approach over the local one, unless there is a good reason not to that I'm missing.

**Comment by oridashi** [comment]
core extension is now used - local extension removed
