### ISSUE TITLE
No redirection and Incorrect redirection 

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#561]
The following links from http://build.fhir.org/ig/hl7au/au-fhir-base/ have redirection issues

- http://hl7.org.au/fhir/StructureDefinition/au-patient --- Redirects to http://hl7.org.au/fhir/aubase1/StructureDefinition-au-patient.html
- http://hl7.org.au/fhir/StructureDefinition/au-practitioner --- Redirects to http://hl7.org.au/fhir/aubase1/StructureDefinition-au-practitioner.html
- http://hl7.org.au/fhir/StructureDefinition/au-practitionerrole --- Redirects to http://hl7.org.au/fhir/aubase1/StructureDefinition-au-practitionerrole.html
- http://hl7.org.au/fhir/StructureDefinition/au-healthcareservice --- Redirects to http://hl7.org.au/fhir/aubase1/StructureDefinition-au-healthcareservice.html
- http://hl7.org.au/fhir/StructureDefinition/au-bodyheight --- Redirects to http://hl7.org.au/fhir/aubase1/StructureDefinition-au-bodyheight.html
- http://hl7.org.au/fhir/StructureDefinition/au-bodyweight --- Redirects to http://hl7.org.au/fhir/aubase1/StructureDefinition-au-bodyweight.html
- http://hl7.org.au/fhir/StructureDefinition/au-headcircum --- Redirects to http://hl7.org.au/fhir/aubase1/StructureDefinition-au-headcircum.html
- etc. (as not all links were tested) 

and the following  --- Redirects to (404 Not Found)

- http://hl7.org.au/fhir/StructureDefinition/date-of-arrival 
- http://hl7.org.au/fhir/StructureDefinition/ethnicity
- http://hl7.org.au/fhir/StructureDefinition/au-bloodpressure
- http://hl7.org.au/fhir/StructureDefinition/au-bmi
- http://hl7.org.au/fhir/StructureDefinition/au-bodytemp
- http://hl7.org.au/fhir/StructureDefinition/au-heartrate
- http://hl7.org.au/fhir/StructureDefinition/au-resprate
- http://hl7.org.au/fhir/StructureDefinition/au-oxygensat
- http://hl7.org.au/fhir/StructureDefinition/au-vitalspanel
- etc. (as not all links were tested) 

These are verified as problem as on 19 Jan 2022.

**Comment by brettesler-ext** [comment]
f2f comment - publishing issue; propose logged to HL7 AU technical issue and closed

**Comment by brettesler-ext** [comment]
Closed as no longer relevant https://confluence.hl7.org/display/HAFWG/2024-04-10+FHIRWG+Meeting+Minutes
