### ISSUE TITLE
Support for mobile, remote and virtual healthcare services

### ISSUE THREAD

**Issue by mcguirek** [hl7au/au-fhir-base#574]
Not all healthcare services are delivered in a fixed location.  Some healthcare services are mobile and others are delivered remotely by phone, video or online.  Guidance is required as to how to represent mobile, remote or virtual healthcare services in directories and other uses.  It is proposed to include guidance in the AU Base FHIR Implementation Guide (http://build.fhir.org/ig/hl7au/au-fhir-base/index.html).  Since many directories must conform to the AU PD FHIR Implementation Guide (http://build.fhir.org/ig/hl7au/au-fhir-pd/index.html) any guidance should be able to be followed in a manner that conforms to AU PD.

The current constraints in AU Base are as follows:
•	A HealthcareService may reference zero or more Locations

The current constraints in AU PD are as follows:
•	A HealthcareService must reference exactly one Location
•	A Location must have exactly one Address

The NHSD FHIR IG defines a local codesystem to use in location.physicalType to include Home Visit and Virtual as physical location types:
https://build.fhir.nhsd.healthdirect.org.au/CodeSystem-au-location-physicalType.html
Whilst it could be argued that these are more like modes or methods of delivery, rather than physical location types, there is no element in HealthcareService to store this information (other than the general-purpose characteristic element), and even if there was, we would still need to put something in the Location since AU PD mandates it.

It is proposed to:
1.	Extend the valueset for location.physicalType with the following code:
•	vi (virtual) – to indicate the delivery location has no physical type, but the service is delivered virtually by phone, video, or online
2.	Provide guidance that mobile or remote HealthcareServices should:
a.	Reference a Location that:
–	Has a physicalType of “si (site)” for mobile services delivered at workplaces, schools, libraries, etc, “ho (house)” for mobile services delivered in the home, or “vi (virtual)” for services delivered by phone/video/internet.
–	Has a mode of “kind” – to indicate this location is not a specific instance of physical location, but a kind of physical location
–	Has a name reflective of the mobile, remote or virtual nature of the service location
–	Has no address, or, if an address is mandated, then an address.text that reflects the mobile, remote or virtual nature of the service location.
b.	Reference one or more coverageAreas that define where the service is available.  coverageAreas should have a location.physicalType of “area”.

**Comment by mcguirek** [comment]
Proposal agreed at PAWG 17 December 2020 (https://confluence.hl7australia.com/display/PA/2020-12-16+Minutes) subject to:
- consider whether physicalType='ho' would be better represented as type='PTRES' and physicalType='si' as type='MOBL'
- confirmed that physicalType='vi' for all telephone or online service locations
- confirmed that mode='kind' for all mobile and virtual service locations
- include examples for:
	- services that can be delivered in the home (be that a house, apartment, unit or residential facility)

It was also agreed to relax cardinality of location.address in PD to 0..1.  Consider constraint in PD that address must be present unless location.mode='kind'.

**Comment by oridashi** [comment]
suggest we look at adding a code to http://hl7.org/fhir/R4/v3/ServiceDeliveryLocationRoleType/vs.html as Location.type to represent virtual explicitly - making it easier to search for this type of service rather than a combination of type and physicalType  - alternatively somehow add virtual and mobile to the HealthcareService level to enable search for that type of service (not clear on how that could be done)

**Comment by mcguirek** [comment]
The new valueset with code 'VI' has been created and bound to location.type, but the location usage guidance still needs updating to reflect this.

**Comment by oridashi** [comment]
complete
