### ISSUE TITLE
Extension date-of-arrival.definition

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#577]
The definition for this extension is much too narrow given the extension's definition. The more specific use case of year of arrival has mistakenly been copied into the extension definition. Please correct to be:
> The date an individual (born outside of Australia) first arrived in Australia, from another country, with the intention of living in Australia for one year or more. This date is captured once for a person and is not subsequently updated with subsequent arrivals.

**Comment by oridashi** [comment]
complete
