### ISSUE TITLE
Contact purpose valueset URL not resolving 

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#583]
The HL7 AU based  terminology for Contact Purpose Extended, has the following canonical URL
http://terminology.hl7.org.au/ValueSet/contact-purpose

The URL though is not resolving when used in other specs that reference this ValueSet by its URL.

The build.fhir end point is 
http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-contact-purpose.html

**Comment by oridashi** [comment]
will roll up into infrastructure QA checks - all http://terminology.hl7.org.au links are broken

**Comment by brettesler-ext** [comment]
f2f comment - publishing issue; propose logged to HL7 AU technical issue and closed

**Comment by hl7auadmin** [comment]
this is correct - removing from block vote - tx.hl7.org.au is to be configured to have an alias terminology.hl7.org.au to support this - transferring to Jira ticket

**Comment by dt-r** [comment]
@robeastwood-agency, this issue is resolved. Please reopen if this is still a problem for you.
