### ISSUE TITLE
HL7 AU Profiles : Grammar error HL7 AU profile page

### ISSUE THREAD

**Issue by udaychandrupatla** [hl7au/au-fhir-base#588]
The HL7 AU profile pages have a grammar error, "as a active" which is incorrect.
e.g.
It should be changed 
**from**
This profile was published on Tue Jul 21 00:00:00 AEST 2020 as **a** active by Health Level Seven Australia (Patient Administration WG).
**to**
This profile was published on Tue Jul 21 00:00:00 AEST 2020 as active by Health Level Seven Australia (Patient Administration WG).

**Comment by RichardTON** [comment]
This is a problem with the IG template.

**Comment by davidmckillop** [comment]
This issue has been resolved with the move to the template IG Publication process in Nov 2022.  
The text "This profile was published on Tue Jul 21 00:00:00 AEST 2020 as a active by Health Level Seven Australia (Patient Administration WG)." is no longer present.
