### ISSUE TITLE
Develop AU value set for Observation.category

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#589]
The current FHIR Core value set for Observation.category is [observation-category](http://hl7.org/fhir/valueset-observation-category.html) with [preferred](http://hl7.org/fhir/terminologies.html#preferred) binding. This value set is used in US Core profiles e.g.  [us-core-observation-lab](http://hl7.org/fhir/us/core/StructureDefinition-us-core-observation-lab.html) and other internationally standardised profiles e.g. [vitalsigns](http://hl7.org/fhir/vitalsigns.html).
It may be useful to not only categorise observations based on their broader grouping as designated in codesystem observation-category e.g. imaging, laboratory and procedure, but also according to their sub-domains of the broader group.  For example, for pathology include the domains of Anatomical Pathology, Checmical Pathology, Cytogenetics, Genetics, Haematology, Immunology and Microbiology.  Similarly, imaging would contain the appropriate sub-domains (yet to be agreed upon) and there would also exist the domains for Audiology, Cardiology, Gastroenterology, Neurology, Ophthalmology, Orthopaedics, Respiratory, Speech Pathology and Urology.  

This would enable specification to include a broader category and a relevant domain to facilitate discoverability and searching.

Questions:
1)  Are the current values in [observation-category](http://hl7.org/fhir/valueset-observation-category.html) suitable for AU?
2) What additional values would be useful in the AU context?

**Comment by dtr-agency** [comment]
I can't see how there could be any meaningful AU value set for Observation.category - an Observation is a hugely broad scope and is unlikely to be relevant as just 'AU' localisation. What are you really asking for here?

**Comment by davidmckillop** [comment]
Closing this ticket as it is and potentially investigate other options that would be better suited for AU level.
