### ISSUE TITLE
Develop AU Value set for BodyStructure.locationQualifier

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#593]
The current FHIR Core value set for [BodyStructure](http://hl7.org/fhir/R4/bodystructure.html).locationQualifier is [BodystructureLocationQualifier](http://hl7.org/fhir/R4/valueset-bodystructure-relative-location.html) with [example](http://hl7.org/fhir/R4/terminologies.html#example) binding.
This value set is limited and it would be useful to have a more defined value set for [AU BodyStructure.locationQualifier](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-bodystructure.html) that was agreed to by stakeholders that accommodated the potential use cases.

**Comment by dtr-agency** [comment]
@davidmckillop please propose your value set suggestion and provide information on what is inadequate about the example set.

**Comment by davidmckillop** [comment]
Any further issues relating to this GitHub ticket i.e. bindings, content, will be dealt with in GitHub #575 as a new value set needs to be developed to resolve the issue of having inactive codes in the HL7 FHIR core value set - raised in FHIR-29810.
