### ISSUE TITLE
Patient has broken links

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#594]
The following links in AU Base Patient (http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient) are broken
- Patient: [Birth Place](http://hl7.org/fhir/StructureDefinition/birthPlace) (Core Extension) - returns message Internal Error - unknown id birthPlace (from crstructuredefinition.asp) .
- Patient: [Date of Arrival in Australia](http://hl7.org.au/fhir/StructureDefinition/date-of-arrival) - returns 404
- Patient: [Ethnicity](http://hl7.org.au/fhir/StructureDefinition/ethnicity) - returns 404

**Comment by robeastwood-agency** [comment]
### Re point 1 - Birthplace
the url in the md file is wrong: currently it is http://hl7.org/fhir/StructureDefinition/birthPlace

Should be http://hl7.org/fhir/StructureDefinition/patient-birthPlace

We'll do a PR fix for this bit

**Comment by RichardTON** [comment]
Links such as Date of Arrival in Australia and Ethnicity do not have redirects in place. The others with redirects, e.g. Indigenous Status go to the AU Base 1 version. They should go to same IG. This is because the .md file uses the canolical URI instead of a relative url to the relevant page. e.g. it uses "http://hl7.org.au/fhir/StructureDefinition/indigenous-status" when it should use "StructureDefinition-indigenous-status.html"

**Comment by RichardTON** [comment]
Pull request with relative links is forthcomming.

**Comment by robeastwood-agency** [comment]
This is addressed via PR #611
