### ISSUE TITLE
Standardise the structure of extensions

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#595]
**Problem**
AU Base extensions follow two patterns when they should all follow one or the other. And neither is what HL7 Core does.

**Background**
The definition of [extension](https://build.fhir.org/extensibility.html#extension) includes 
> ext-1 Rule Must have either extensions or value[x], not both extension.exists() != value.exists()

Many core extensions explicitly make extension.extension 0..0 when extension.value is of interest (e.g. [Anonymized](https://build.fhir.org/extension-auditevent-anonymized.html)). Others make extension.value 0..0 when extension.extension is of interest (e.g. [oauth-uris](https://build.fhir.org/extension-oauth-uris.html)).

This is redundant, but does make the cardinality more obvious. See[ Zulip thread](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/ext-1/near/243477539). However it is more work to do, test and maintain.

In AU Base 24 out of 31 extensions do not make this explicit. 
1 makes extension explicitly 0..0 when there is a value
- [Indigenous Status](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-indigenous-status.html)

6 make value explicitly 0..0 when there is an extension, but they do not make extension 0..0 when there is a value. They half follow Core. A sign that this is hard to get right.
- [AHPRA Profession Details](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-ahpraprofession-details.html)
- [AHPRA Registration Details](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-ahpraregistration-details.html)
- [Receiving Application](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-receivingapplication.html)
- [Receiving Facility](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-receivingfacility.html)
- [Assigning Authority](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-assigningauthority.html)
- [Identifier Routability](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-identifier-routability.html)

All AU Base extensions should follow the one pattern, either follow the 24 with no redundant expression of cardinality or follow Core with full redundant expression of cardinality.

**Comment by RichardTON** [comment]
Should it be usable in Person?

**Comment by robeastwood-agency** [comment]
This has been raised as a ballot comment see [FHIRIG-174](https://jira.hl7australia.com/browse/FHIRIG-174).

Regarding the decision as to including or removing the cardinality constraint, @oridashi has added the comment 
>Remove redundant cardinality 0..0 as not longer required R4.
> Agency will raise PR for technical issue

Therefore, being addressed as part of the ballot fixes.

**Comment by robeastwood-agency** [comment]
This has been addressed via PR #680
