### ISSUE TITLE
Update Patient.link description and short to use clearer R5 one

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#597]
The description of [R4 Patient.link](http://hl7.org/fhir/R4/patient-definitions.html#Patient.link) is 'Link to another patient resource that concerns the same actual patient.' 
Despite the description, this can include a RelatedPerson. See [FHIR-23009](https://jira.hl7.org/browse/FHIR-23009) and [FHIR-32874](https://jira.hl7.org/browse/FHIR-32874). 
This is being clarified in R5. 
Use the proposed R5 text 'Link to a Patient or RelatedPerson resource that concerns the same actual person' in AU Base R4

**Comment by RichardTON** [comment]
Pull request withnew text is forthcomming.

**Comment by robeastwood-agency** [comment]
This is addressed via PR #611
