### ISSUE TITLE
Enhance Ethnicity extension to better support health care provision

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#598]
### The issue
To support collecting and sharing ethnicity data. The current ethnicity extension in AU Base is a starting point but it needs maturation to be adopted for use. 
-	current extension context is limited to Patient only – should at least be extended to Group 
-	to support targeted provision of culturally appropriate healthcare services - How is that matched to services, providers, etc? need to close the loop on advertising support 
-	need to address how a complex narrative statement of ethnic identity can be provided
-	see #559 relating to terminology for ethnicity
-	need to clarify the concept and its definition – is this ethnicity or is it in particular ethnic identity – how does this extension lines up with CALD data sets?
-	needs work on the scope of use, boundaries, guidance

**Ethnicity** 
Ethnicity refers to the shared identity or similarity of a group of people on the basis of one or more distinguishing characteristics. Ethnicity includes ATSI (Aboriginal and Torres Strait Islander) groups. [ABS Australian Standard Classification of Cultural and Ethnic Groups (ASCCEG) 2019](https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/2019). 

**Ethnic Identity**
Identification with an ethnicity
The information structure will support exchange of "one or more ethnicities with which a person identifies".

**Ancestry**
Ancestry describes the ethnic origin or cultural heritage to which a person identifies and/or to which a person's forebears are/were attached. [Ancestry Standard](https://www.abs.gov.au/statistics/standards/ancestry-standard/2014-version-21)

NOTE: Ancestry is included only for context – this extension is NOT ancestry. 

### Additional Context
[US Core Ethnicity Extension](https://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-ethnicity.html)) specifically supports US regulations with two levels of granularity specifically - it's not applicable in an AU context.

The Primary Care Data Quality Foundations Clinical Content Working Group identified ethnicity as being of value, but complex and needing more work. They identified various branches of ethnicity: administrative ethnicity, ethnic identity, ethnic group, country of birth, language, religion.

**Comment by RichardTON** [comment]
This choice is made by a Victorian Government agency, see [Data collection standards - Culturally and linguistically diverse communities](https://www.vic.gov.au/victorian-family-violence-data-collection-framework/data-collection-standards-culturally-and#cultural-background-and-ethnicity)

**Comment by RichardTON** [comment]
It also needs some useful usage notes.

**Comment by RichardTON** [comment]
**# Work in Progress**

# Proposed solution

Add to HL7 AU the extensions Ethnicity String and Ethnicity Code to represent ethnicity in an Australian context.

Provide guidance that in a resource all of the relevant ethnicity information should be represented as a narrative string or as a set of codings, that neither of them is, for the purposes of the resource, incomplete. This simplifies use of the resource. Often a resource will use only text or codings. 

Explicitly include both extensions in AU Base Patient and mention them as available in the documentation for the other relevant profiles, e.g. AU Base Practitioner.

This proposal assumes that most systems will exchange ethnicity as text or exchange ethnicity as code, and few will exchange ethnicity as both text and code. The extra extension Ethnicity is only appropriate if it is common for systems to exchange both forms of information. If it is not common, it should not be added to HL7 AU Base.

## Extension: Ethnicity String

This extension applies to the Patient, Group, Practitioner and RelatedPerson resources and defines ethnicity represented as text.
> Ethnicity is the shared identity or similarity of a group of people on the basis of one or more distinguishing characteristics. These characteristics include:
> * A long shared history, the memory of which is kept alive.
> * A cultural tradition, including family and social customs, sometimes religiously based.
> * A common geographic origin.
> * A common language (but not necessarily limited to that group).
> * A common literature (written or oral).
> * A common religion.
> * Being a minority (often with a sense of being oppressed).
> * Being racially conspicuous.
>
> Source : [Australian Standard Classification of Cultural and Ethnic Groups (ASCCEG)](https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/2019), accessed 9 June 2021.

### Usage notes

Ethnicity subsumes ethnic identity and ancestry. It is synonymous with some (but not all) uses of nationality. It includes Australian indigenous groups and sub-groups.

This may be long or short and may include many distinct or overlapping ethnicities. This also suitable for fine-grained and unclassified expressions of ethnicity.

There is another extension suitable for use when ethnicity is codable.
|Name| |Card.|Type|Description & Constraints|
|-------|-|------|-----|----------------------------|
|Extension| |0..1|Extension|Ethnicity as string|
| |url|1..1|uri|"http://hl7.org.au/fhir/StructureDefinition/ethnicitystring"|
| |value[x]:valueString|1..1|string|Value of extension|

## Extension: Ethnicity Code

This extension applies to the Patient, Group, HealthcareService, Practitioner and RelatedPerson resources and defines ethnicity represented as codes.
> Ethnicity is the shared identity or similarity of a group of people on the basis of one or more distinguishing characteristics. These characteristics include:
> * A long shared history, the memory of which is kept alive.
> * A cultural tradition, including family and social customs, sometimes religiously based.
> * A common geographic origin.
> * A common language (but not necessarily limited to that group).
> * A common literature (written or oral).
> * A common religion.
> * Being a minority (often with a sense of being oppressed).
> * Being racially conspicuous.
>
> Source : [Australian Standard Classification of Cultural and Ethnic Groups (ASCCEG)](https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/2019), accessed 9 June 2021.

### Usage notes

Ethnicity subsumes ethnic identity and ancestry. It is synonymous with some (but not all) uses of nationality. It includes Australian indigenous groups and sub-groups.

This concept can contribute to matching patients with culturally appropriate persons, groups and services. Such matching needs to be nuanced.

There is another extension suitable for use when ethnicity cannot be coded.

In the first draft the value domain is all values from Australian Standard Classification of Cultural and Ethnic Groups (ASCCEG). This should be expanded to include many values from the ASCCEG coding index.
|Name| |Card.|Type|Description & Constraints|
|-------|-|------|----|-----------------------------|
|Extension| |0..1|Extension|Coded ethnicity|
| |url|1..1|uri|"http://hl7.org.au/fhir/StructureDefinition/ethnicitycode"|
| |value[x]:valueCodeableConcept|1..1|CodeableConcept|Value of extension|
|||||*Binding:* (unbound) (example): All values from Australian Standard Classification of Cultural and Ethnic Groups.|

**Comment by RichardTON** [comment]
Comments on proposed solution

If the proposal's assumption that most systems will exchange ethnicity as text or exchange ethnicity as code, and few will exchange ethnicity as both text and code is wrong, an extra extension Ethnicity that includes both string and codeable concept values may be appropriate. 

One plausible source of additions to the Ethnicity value set is the [ASCCEG coding index](https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/2019#index-for-coding-responses).

**Comment by brettesler-ext** [comment]
F2F comment - needs discussion on state of this and whether this needs multiple categories to be introduced; discuss what are next plans for this item.

**Comment by hl7auadmin** [comment]
eVote: no specific proposal propose creating ticket and placing on hold

**Comment by brettesler-ext** [comment]
moved to HL7 Jira [FHIR-46307](https://jira.hl7.org/browse/FHIR-46307)
