### ISSUE TITLE
Patient needs more work to use Core's Gender Identity extension 

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#599]
[AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) uses the [FHIR Core Gender Identity extension](http://hl7.org/fhir/R4/extension-patient-genderidentity.html).
As AU Base Patient uses this, Patient needs to provide usage notes to clarify Gender Identity's usage in an Australian context and a preferred binding, rather than the example binding.

**Comment by robeastwood-agency** [comment]
On balance given the likely extent of work required, particularly on the options for terminology, it was decided with @oridashi (Brett) to remove this extension for now. This has been done in PR #611 (see commit 2ba705ca89d18e3d7fc879a4ce81b27598715d5a) and includes the added informative text:
> The core extension [Gender Identity](http://hl7.org/fhir/R4/extension-patient-genderidentity.html) is not yet supported in AU Base Patient as the terminology is considered inappropriate for use in Australia.

**Comment by dtr-agency** [comment]
Related ballot feedback 
https://jira.hl7australia.com/browse/FHIRIG-186 Gender identity should be added to StructureDefinition-au-patient

http://hl7.org.au/fhir/2021Aug/StructureDefinition-au-patient.html

A data element to capture the patient's gender identity should be added.

It is suggested that this be addressed through addition of an CodeableConcept extension and extensibly binding it to a new (HL7 AU maintained) value set. This value set should select codes from an HL7 AU maintained code system (also to be added) which includes codes aligned with the Australian Bureau of Statistics (ABS) Standard for Sex, Gender, Variations of Sex Characteristics and Sexual Orientation Variables (https://www.abs.gov.au/statistics/standards/standard-sex-gender-variations-sex-characteristics-and-sexual-orientation-variables/latest-release) values for gender identity i.e. Male, Female, Non-binary, Different Term, Prefer Not To Answer, Not stated or inadequately described.

If appropriate the HL7 International gender-identity extension (https://www.hl7.org/fhir/extension-patient-genderidentity.html) could be considered for adoption.
Reporter:Reuben Daniels
Email:reuben@saludax.com

https://jira.hl7australia.com/browse/FHIRIG-187 Gender should be added to StructureDefinition-au-relatedperson
http://hl7.org.au/fhir/2021Aug/StructureDefinition-au-relatedperson.html

Similar comment as for FHIRIG-186. The same suggested extension, value set and code system proposed may be reused.
Reporter:Reuben Daniels
Email:reuben@saludax.com

**Comment by dtr-agency** [comment]
Outcome from meeting on Gender Identity 11 AUG 2022 to discuss proposals documented on https://confluence.hl7australia.com/display/PA/Gender+Identity is documented here https://confluence.hl7australia.com/pages/viewpage.action?pageId=116461176:
* add support for core extension patient gender identity to AU Base Patient
* wait on adding support for gender identity extension to other resource types - intend to pre-adopt R5 extension when it is published
* terminology for gender identity will be supported by a baseline set bound as extensible with addition concepts to be added to the set when national adoption is agreed:

Initial value set to consist of 

code | display | system
-- | -- | -- 
446151000124109 | Identifies as male gender |   http://snomed.info/sct
446141000124107 | Identifies as female gender |  http://snomed.info/sct
33791000087105 | Identifies as nonbinary gender |  http://snomed.info/sct
unknown | Unknown | http://terminology.hl7.org/CodeSystem/data-absent-reason
asked-declined | Asked But Declined | http://terminology.hl7.org/CodeSystem/data-absent-reason

**Comment by dtr-agency** [comment]
This is a core extension with it's own definition so implementing behaviour supporting extensible binding will need to be done with this in mind. 

Options include in AU Base Patient add the core genderIdentity extension and:
1. add an invariant on the Patient element to trigger the same behaviour as an extensible binding
2. define an AU Gender Identity extension and on AU Base Patient place an invariant that required genderIdentity to conform to that AU Gender Identity extension
3. Decompose the extension:genderIdentity slice to value[x] / valueCodableConcept and constrain by binding

Invariant on Patient
```
<constraint>
        <key value="inv-pat-1" />
        <severity value="warning" />
        <human value="Gender identity SHALL be a member of the Gender Identity Response value set if any of the codes within that value set can apply" />
        <expression value="extension('http://hl7.org/fhir/StructureDefinition/patient-genderIdentity').empty() or extension('http://hl7.org/fhir/StructureDefinition/patient-genderIdentity').valueCodeableConcept.memberOf('https://healthterminologies.gov.au/fhir/ValueSet/gender-identity-response-1')" />
        <source value="http://hl7.org.au/fhir/StructureDefinition/au-patient" />
</constraint>
```

Decompose the extension:genderIdentity slice to value[x] / valueCodableConcept
```
<element id="Patient.extension:genderIdentity.valueCodeableConcept">
      <path value="Patient.extension.valueCodeableConcept" />
      <type>
        <code value="CodeableConcept" />
      </type>
      <binding>
        <strength value="extensible" />
        <valueSet value="https://healthterminologies.gov.au/fhir/ValueSet/gender-identity-response-1" />
      </binding>
</element>
```

To ways to implement equivalent behavioural support for the binding noting that either way the example binding gets rendered in views (Diff, Snapshot etc.) and there doesn't appear to be a way to turn that off for at least the Diff.

**Comment by dtr-agency** [comment]
The binding option is preferred, the extension:genderIdentity slice has been decomposed to value[x] / valueCodableConcept to add a binding.

**Comment by dtr-agency** [comment]
PR forthcoming - content reviewed and okayed by @oridashi and @davidmckillop.
