### ISSUE TITLE
Definition of Date of Arrival in Australia root element is wrong

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#600]
In [Date of Arrival in Australia](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-date-of-arrival.html) the definition of Extension is out of step with the rest of the profile. It refers to year instead of date.

Replace
> The year of arrival in Australia from the Australian Bureau of Statics (ABS) and the Australian Institute of Health and Wealfare (AIHW). The year a person first arrived in Australia, from another country, with the intention of living in Australia for one year or more.

with the short with a terminal period.
> The date a person first arrived in Australia, from another country, with the intention of living in Australia for one year or more.

**Comment by RichardTON** [comment]
Pull request with new text is forthcomming.

**Comment by robeastwood-agency** [comment]
This is addressed via PR #611
