### ISSUE TITLE
AU Base Medication Request - fix normative defects with mandatory slices and slicing declaration

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#601]
AU Base Medication Request needs refactoring

1. Make two MedicationRequest.medication slices (medicationCodeableConcept and medicationReference) slices optional. Both slices are mandatory currently which forces failure as it is not possible to satisfy the slice.
2. Remove erroneous  Slices for additionalInstruction from MedicationRequest.dosageIntstruction

Additionally, tweak examples to fix defects that came out of STU3 to R4 conversion, and make styling and content fixes in intro.md

**Comment by RichardTON** [comment]
Pull request with change is forthcomming.

**Comment by dbojicic-agency** [comment]
PR coming shortly.

**Comment by dbojicic-agency** [comment]
In review with @dtr-agency.
