### ISSUE TITLE
Patient should include guidance on boundaries and relationships

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#602]
Proposal
#### Boundaries and Relationships
Other attributes, ostensibly considered to be demographic in nature, are better represented in other resources rather than directly part of the Patient. These attributes include:
* a patient’s biological sex - this is a testable observation about a biological property of a patient, and as such should be represented using an [AU Sex Assigned At Birth](StructureDefinition-au-sexassignedatbirth.html) profile.
* a patient’s pregnancy status - this is a transient clinical statement better represented using the [Condition](http://hl7.org/fhir/R4/condition.html) resource
* various social determinants of health (such as housing status, employment status or socio-economic background) - these patient attributes are better tracked using a combination of other resources such as [Observation](http://hl7.org/fhir/R4/observation.html), [Condition](http://hl7.org/fhir/R4/condition.html) or [Flag](http://hl7.org/fhir/R4/flag.html)

**Comment by robeastwood-agency** [comment]
This was considered to be added into the PR [Improvements to AU Base Patient and associated artifacts](https://github.com/hl7au/au-fhir-base/pull/611) (#611), but it was decided against inclusion as it was preferred to roll this into similar (future) changes to other profiles

**Comment by brettesler-ext** [comment]
F2F comment - propose close 
sex/gender concepts wrt gender harmony project have been further developed in FHIRWG supersedes this
pregnancy status is perhaps in eRequest CDI consideration and will be initially addressed there
SDOH have not been address and require specific project ownership

**Comment by RichardTON** [comment]
While the proposed text is now out of date, the basic problem remains, a range of information that superficially seems to be demographic does not belong in Patient. Guidance on this should be included in a scope statement for Patient to support implementers that are ahead of AU Base and AUCore.

**Comment by hl7auadmin** [comment]
eVote: some of the specific items have progressed to TDG work; a ballot comment with proposed additional narrative is recommended; propose close

**Comment by brettesler-ext** [comment]
Closed as no longer relevant https://confluence.hl7.org/display/HAFWG/2024-04-10+FHIRWG+Meeting+Minutes
