### ISSUE TITLE
Location Physical Type - AU Extended value set incorrectly defined, it should extend core set

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#609]
### ValueSet
Logical Definition (CLD) currently contains only a single code from the AU extension code system for this concept:
- Include all codes defined in http://terminology.hl7.org.au/CodeSystem/location-physical-type

The correct Logical Definition (CLD) is:
Include all codes defined in http://terminology.hl7.org.au/CodeSystem/location-physical-type
Import all the codes that are contained in http://terminology.hl7.org/CodeSystem/location-physical-type

Other informative fixes to bring it into line with other AU Base material will be necessary e.g. title.

### CodeSystem
Informative fixes to bring it into line with other AU Base material necessary e.g. title.

**Comment by dtr-agency** [comment]
@oridashi the value set and code system are missing OIDs. Please add to https://confluence.hl7australia.com/display/AFR/HL7+AU+OID+Registry.

**Comment by dtr-agency** [comment]
PR with @robeastwood-agency for review and test.

**Comment by dtr-agency** [comment]
Agreed on AU terminology resource conventions with @oridashi. [wiki](https://github.com/hl7au/au-fhir-base/wiki) will eventually have this documented. Update to PR in progress.

**Comment by robeastwood-agency** [comment]
In review
