### ISSUE TITLE
V2 Degree/License/Certificate - AU Extended value set incorrectly defined, it should extend core set

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#610]
### ValueSet
Logical Definition (CLD) currently contains only two codes from the AU extension code system for this concept:
- Include all codes defined in http://terminology.hl7.org.au/CodeSystem/v2-0360

The correct Logical Definition (CLD) is:
- Include all codes defined in http://terminology.hl7.org.au/CodeSystem/v2-0360
- Import all the codes that are contained in http://terminology.hl7.org/ValueSet/v2-2.7-0360

The value set URL is incorrect - not in the R4 namespace for hl7au terminology, also not consistent with format that code system and value set have same id & url where the namespace is used to differentiate.

**Comment by dtr-agency** [comment]
@oridashi the value set and code system are missing OIDs for the following (aligned value set url to be consistent with pattern for au extension):
* http://hl7.org.au/fhir/ValueSet/v2-2.7-0360
* http://terminology.hl7.org.au/CodeSystem/v2-0360

Please add to https://confluence.hl7australia.com/display/AFR/HL7+AU+OID+Registry.

**Comment by dtr-agency** [comment]
PR in progress

**Comment by robeastwood-agency** [comment]
In review

**Comment by dtr-agency** [comment]
Agreed on AU terminology resource conventions with @oridashi. [wiki](https://github.com/hl7au/au-fhir-base/wiki) will eventually have this documented. Update to PR in progress.
