### ISSUE TITLE
AU Encounter - refactor to remove slicing; move v3 Act Encounter Code value set into terminology namespace

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#634]
AU Encounter resources to be refactored:

1. Encounter StructureDefinition: replace dischargeDisposition slicing with extensible binding
1. Apply terminology conventions to v3 Act Encounter Code value set:
   1. move into terminology namespace 
   1. correct title, name, id, url

Agreed on AU terminology resource conventions with @oridashi. [wiki](https://github.com/hl7au/au-fhir-base/wiki) now has this documented.
Base terminology to be 'extended' sourced from [HL7 Terminology 2.1.0 - Publication](https://terminology.hl7.org/2.1.0/index.html).

**Comment by dtr-agency** [comment]
PR in progress

**Comment by davidmckillop** [comment]
Changes made to remove slicing and other changes including tidying of profile.md and au-encounter-intro.md.  All good 👍
