### ISSUE TITLE
HL7 AU Terminologies without OIDs & R4 ValueSets need NEW OIDs 

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#641]
## NEW OIDs required

The following HL7 AU code systems need **NEW** OIDs registered on the [HL7 AU OID Registry](https://confluence.hl7australia.com/display/AFR/HL7+AU+OID+Registry):

- Location Type (Physical) AU http://terminology.hl7.org.au/CodeSystem/location-physical-type
- Location Type AU http://terminology.hl7.org.au/CodeSystem/location-type
- Act Code AU http://terminology.hl7.org.au/CodeSystem/v3-ActCode
- Medicine Item Change http://terminology.hl7.org.au/fhir/CodeSystem/medicine-item-change
- HL7 V2 Table 0203 AU http://terminology.hl7.org.au/CodeSystem/v2-0203
- Medication Type http://terminology.hl7.org.au/CodeSystem/medication-type
- Service Provision Conditions Australian Concepts http://terminology.hl7.org.au/CodeSystem/service-provision-conditions

The following HL7 AU value sets need **NEW** OIDs registered on the [HL7 AU OID Registry](https://confluence.hl7australia.com/display/AFR/HL7+AU+OID+Registry):

- AU Time Zone http://terminology.hl7.org.au/ValueSet/au-timezone
- Medicine Item Change http://terminology.hl7.org.au/fhir/ValueSet/medicine-item-change
- ServiceDeliveryLocationRoleType - AU Extended http://terminology.hl7.org.au/ValueSet/v3-ServiceDeliveryLocationRoleType-extended
- Location Type (Physical) - AU Extended http://terminology.hl7.org.au/ValueSet/location-physical-type-extended
- Order Identifier Type http://terminology.hl7.org.au/ValueSet/order-identifier-type
- Accession Number Type http://terminology.hl7.org.au/ValueSet/accession-number-type
- DVA Entitlement http://terminology.hl7.org.au/ValueSet/dva-entitlement
- Medication Type http://terminology.hl7.org.au/ValueSet/medication-type
- AMT Medicinal Product and Substances http://terminology.hl7.org.au/ValueSet/amt-mp-codes
- MIMS Terminology http://terminology.hl7.org.au/ValueSet/mims
- PBS Medicines Item Codes http://terminology.hl7.org.au/ValueSet/pbs-item
- Service Provision Conditions Australian Concepts http://terminology.hl7.org.au/ValueSet/service-provision-conditions
- Medication Type http://terminology.hl7.org.au/CodeSystem/medication-type
- V2 Identifier Type - AU Extended http://terminology.org.au/ValueSet/au-hl7v2-0203
- Act Encounter Code http://terminology.hl7.org.au/ValueSet/v3-ActEncounterCode

**Comment by oridashi** [comment]
updated OID registry https://confluence.hl7australia.com/display/AFR/HL7+AU+OID+Registry please reviuew
ValueSet URL issues noted in issue #644

**Comment by dtr-agency** [comment]
@dbojicic-agency in progress with PR.
