### ISSUE TITLE
valueset url not consistent

### ISSUE THREAD

**Issue by oridashi** [hl7au/au-fhir-base#644]
http://terminology.hl7.org.au/ValueSet/au-v2-0203
on
http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-au-v2-0203.html
ageed to be like 0443

http://terminology.hl7.org.au/ValueSet/au-v2-0203-extended 
--

ALSO 'au-' not appearing on id on 0360 valueset

ALSO
some have /fhir/Valueset some have /Valueset (which is correct)

ALSO - some are in the terminology.hl7.org space some in the aubase cannonical http://hl7.org.au/fhir - need to discuss.... 
http://hl7.org.au/fhir/ValueSet/snomed-healthcareservice-specialties 
http://hl7.org.au/fhir/ValueSet/snomed-practitioner-specialties
 incorrect base terminology.hl7.org needed

**Comment by dtr-agency** [comment]
http://hl7.org.au/fhir/ValueSet/snomed-healthcareservice-specialties
http://hl7.org.au/fhir/ValueSet/snomed-practitioner-specialties

aren't used by anything.

**Comment by dbojicic-agency** [comment]
In progress with @dbojicic-agency , fixes will be included in the forthcoming PR.
