### ISSUE TITLE
Regex for unsignedInt type is incorrect

### ISSUE THREAD

**Issue by chrisbednarski** [hl7au/au-fhir-base#649]
The documented regex pattern for `unsignedInt` of `[0]|([1-9][0-9]*)` allows unexpected values and returns matches for numbers with decimal points

http://hl7.org/fhir/R4/datatypes.html#unsignedInt

unexpected matching examples
```
012
2.5
```

I suggest changing the regex pattern to 
`^0$|^[1-9][0-9]*$`

**Comment by RichardTON** [comment]
Good question. Chasing an answer in Zulip at https://chat.fhir.org/#narrow/stream/179165-committers/topic/Regexs.20for.20data.20type.20definitions.20don't.20have.20start.20or.20end

**Comment by RichardTON** [comment]
The [Datatypes](http://hl7.org/fhir/R4/datatypes.html) spec includes

> The regexes should be qualified with start of string and end of string anchors based on the regex implementation used (e.g. caret '^' and dollar-sign '$' for JavaScript, POSIX, XML and XPath; '\A' and '\Z' for .NET, Java, Python and others; please verify these definitions with the regex implementation used).

No changed needed.
