### ISSUE TITLE
Identifier Data Type :: Residential Aged Care Service Identifier (RACS ID)

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#657]
Create an Identifier data type profile for residential aged care service identifiers.

A residential aged care service identifier, commonly known as RACS ID or RACF ID, is assigned by the Department of Health to a residential aged care service subsidised by the Australian Government.

Also add a new value to the [IdentifierType AU](http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-v2-0203.html) code system and create examples.

RACS IDs are relevant identifiers for HealthcareService. They are not relevant to other resources.

**Comment by RichardTON** [comment]
### What it is
Residential aged care service identifiers are assigned by the Department of Health to residential aged care services subsidised by the Australian Government.
They are commonly known as RACS Ids. They are also known as RACF Ids (from residential aged care service facility identifier), though they are assigned to a service and not a facility.
An organisation may provide more than one residential aged care service.

### Context
RACS Ids are used when claiming for medications supplied in a residential aged care facility. Though they may be called RACF Ids. See [Fred](https://webhelp.fred.com.au/freddispense/popups/nursing-home-popup-3.htm), [minfos](https://help.minfos.com.au/support/solutions/articles/51000041652-add-racf-id-to-a-nursing-home), [PBS](https://www.pbs.gov.au/info/news/2020/07/changes-to-pbs-online-claiming-for-residential-aged-care) and [Department of Health](https://www.safetyandquality.gov.au/sites/default/files/migrated/Supply-and-PBS-claiming-from-a-medication-chart-in-residential-aged-care-facilities-Fact-Sheet1.pdf).
They are used when identifying a RACS with government. See [DSS](https://www.dss.gov.au/sites/default/files/documents/12_2014/att_i_app_to_transfer_places_other_than_provisionally_allocated_places_to_another_provider.pdf) and [Aged Care Quality and Safety Commission](https://www.agedcarequality.gov.au/providers/assessment-processes/accreditation-fees).
They may be used when searching for a RACS. See [Aged Care Quality and Safety Commission](https://www.agedcarequality.gov.au/reports). Note that the commission also oversees non-residential aged care services.
Services Australia suggests (but does not say) that RACF ID and RACS ID are synonyms see the RACF entries in [reason codes](https://www.servicesaustralia.gov.au/organisations/health-professionals/services/medicare/pbs-pharmacists/claiming/pbs-reason-and-rejection-codes).

**Comment by dtr-agency** [comment]
@RichardTON please include the proposed resource context. What resources is this applicable to?

**Comment by RichardTON** [comment]
Guidance on applicable resources added above.

**Comment by RichardTON** [comment]
### Proposed design

  |   |   |  
-- | -- | -- | -- 
Identifier |   |   | Residential Aged Care Service Identifier (RACS Id)
  | type | 1..1 | Pattern Value `<valueCodeableConcept xmlns="http://hl7.org/fhir">  <coding>    <system value="http://terminology.hl7.org.au/CodeSystem/v2-0203"/>    <code value="RACSI"/>  </coding></valueCodeableConcept>`
  | system | 1..1 | Fixed Value: http://ns.electronichealth.net.au/id/residential-aged-care-service-id
  | value | 1..1 | RACS ID Example: 0009
