### ISSUE TITLE
AU Gestational Age Profile is not listed on profiles.md

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#661]
The profile [AU Gestational Age](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-gestationalage.xml) is being generated, as it is included in the [ig.xml](https://github.com/hl7au/au-fhir-base/blob/master/resources/ig.xml#L652-L658) and [ig.json](https://github.com/hl7au/au-fhir-base/blob/master/ig.json#L404-L407), but it is not listed in the profiles.md.

Link to generated profile page in the build: https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-gestationalage.html

Issues with its metadata will be addressed as part of a forthcoming PR to fix a number of metadata fixes across a handful of profiles.

The normative structure of this profile has not yet been assessed.

This was discussed with @dbojicic-agency and @oridashi - with the conclusion to create this ticket and proceed to do a PR to have this profile listed in the profiles.md in the Pregnancy Related Profiles section.

**Comment by dbojicic-agency** [comment]
In progress via #667.

**Comment by dtr-agency** [comment]
As this will be progressed via 667 this is now closed.
