### ISSUE TITLE
AU Base Substance - bring the profile across from AU Base IG (STU3)

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#662]
The [AU Base IG STU3](http://hl7.org.au/fhir/aubase1.1/index.html) has the [AU Base Substance](http://hl7.org.au/fhir/aubase1.1/StructureDefinition-au-substance.html)  profile that has not been ported into the R4 implementation guide. 
Please bring the profile across.

**Comment by dbojicic-agency** [comment]
In progress with @dbojicic-agency.

**Comment by dbojicic-agency** [comment]
In internal review with @robeastwood-agency.

**Comment by robeastwood-agency** [comment]
Internal review (and testing) complete; all good
