### ISSUE TITLE
Passport Identifier

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#663]
Australian Passport Identifier on Patient.identitifer
- issue date
- expiry date
- issuing entity
International Passport

**Comment by robeastwood-agency** [comment]
FWIW - I have just stumbled across the following NamingSystem for Passport Numbers Namespace for Australia, defined by the core HL7 Terminology IG: http://terminology.hl7.org/NamingSystem/passportNumNS-AUS.

It defines the following 2 identifiers:
* OID: 2.16.840.1.113883.4.330.36
* URI: http://hl7.org/fhir/sid/passport-AUS

**Comment by brettesler-ext** [comment]
F2F comment - discuss proceed or close?

**Comment by hl7auadmin** [comment]
eVote: proposer to withdraw no specific use case; propose close

**Comment by brettesler-ext** [comment]
Closed as no longer relevant https://confluence.hl7.org/display/HAFWG/2024-04-10+FHIRWG+Meeting+Minutes
