### ISSUE TITLE
Drivers Licence

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#664]
Drivers Licence - Australian State Issued
discuss system URL

**Comment by brettesler-ext** [comment]
F2F comment - discuss proceed or close

**Comment by hl7auadmin** [comment]
eVote: no specific use case for this;  raiser proposes withdrawal; Propose Close

**Comment by brettesler-ext** [comment]
Closed as no longer relevant https://confluence.hl7.org/display/HAFWG/2024-04-10+FHIRWG+Meeting+Minutes
