### ISSUE TITLE
Example 'Downunder Hospital' representations use different HPI-Os

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#666]
In the set of examples, the HPI-O of the Downunder Hospital in [organization-example0.xml](http://build.fhir.org/ig/hl7au/au-fhir-base/Organization-example0.html) is 
```
8003621566684455
```
There are a number of references / uses of the Downunder Hospital, most of which use the above HPI-O value. However the following example instances use a different HPI-O value:

#### bundle-9309d080-4e97-11e9-8647-d663bd873d93.xml
- has 2 instances of 8003621566684455
- and 1 of 8003627500000328 (see [line 551](https://github.com/hl7au/au-fhir-base/blob/master/examples/bundle-9309d080-4e97-11e9-8647-d663bd873d93.xml#L551))

#### medicationrequest-example0.xml
- LPN as HPI-O scoped uses 8003627500000328 for Downunder Hospital ([line 24](https://github.com/hl7au/au-fhir-base/blob/master/examples/medicationrequest-example0.xml#L24))

#### medicationrequest-example1.xml
* LPN as HPI-O scoped uses 8003627500000328 for Downunder Hospital ([line 24](https://github.com/hl7au/au-fhir-base/blob/master/examples/medicationrequest-example1.xml#L24))

#### medicationrequest-example2.xml
- LPN as HPI-O scoped uses 8003627500000328 for Downunder Hospital ([line 32](https://github.com/hl7au/au-fhir-base/blob/master/examples/medicationrequest-example2.xml#L32))

Therefore, under the premise that the Organization record is the source of truth, the respective HPI-O values in the above examples should be changed to `8003621566684455`

**Comment by dtr-agency** [comment]
This could be fixed in the same PR as https://github.com/hl7au/au-fhir-base/issues/667

**Comment by dbojicic-agency** [comment]
In progress with @dbojicic-agency.

**Comment by dbojicic-agency** [comment]
In review with @RichardTON.

**Comment by RichardTON** [comment]
All places that mention Downunder Hospital with an HPI-O use the requested value: 8003621566684455
