### ISSUE TITLE
QA issues across the IG (collector)

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#667]
### 1) [AU Local Prescription Identifier profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-localprescriptionidentifier.html) intro page is missing an example
The intro for the [AU Local Prescription Identifier profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-localprescriptionidentifier.html) lists 2 MedicationRequest examples - [medicationrequest-example0](http://build.fhir.org/ig/hl7au/au-fhir-base/MedicationRequest-medicationrequest-example0.html) and [medicationrequest-example1](http://build.fhir.org/ig/hl7au/au-fhir-base/MedicationRequest-medicationrequest-example1.html).

A third MedicationRequest example - [medicationrequest-example2](http://build.fhir.org/ig/hl7au/au-fhir-base/MedicationRequest-medicationrequest-example2.html) - also has a Local Prescription Identifier, and therefore should also be listed on the intro page. Elsewhere this example has the hyperlink text of "_Prescription for Reaptan_"

### 2) [AU Base Medication Administration profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationadministration.html)
There are 2 metadata issues:
- StructureDefinition.id is missing - should be "au-medicationadministration"
- [StructureDefinition.title](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-medicationadministration.xml#L6) is "AUBaseMedicationAdministration" but should be "AU Base Medication Administration"

### 3) [AU Gestational Age profile](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-gestationalage.html)
A number of issues:
- not listed in profiles.md, but it is being generated via ig.xml etc (see separate github issue #661)
- StructureDefinition.version  is missing
- StructureDefinition.date is missing
- StructureDefinition.description is missing
- StructureDefinition.publisher and StructureDefinition.contact are out of order; they should be between status and jurisdiction (no errors on QA report about this as the IG publisher corrects element mis-ordering on the input file _before_ it examines for problems)

### 4) [AU Biological Sex Assigned at Birth profile](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-sexassignedatbirth.html)
- StructureDefinition.date is missing

### 5) [AU Base Smoking Status Profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-smokingstatus.html)
- au-smokingstatus-intro.md - remove the first paragraph sentence "_It is compatible for use with the International Patient Summmry implementation guide_". It is redundant as it is also present in the usage notes.

**Comment by dtr-agency** [comment]
6. PractitionerRole-example1 has the wrong telecom and should be for Steve Smith at Albion Hospital

**Comment by robeastwood-agency** [comment]
### 7) terminology.md typo
" _value sets ar made to_ " should be " _value sets **are** made to_ "

See [line 16](https://github.com/hl7au/au-fhir-base/blob/master/pages/_includes/terminology.md?plain=1#L16)

**Comment by robeastwood-agency** [comment]
9. AU Address profile - incorrect content for Address Identifier profile

**Comment by dbojicic-agency** [comment]
In progress with @dbojicic-agency.

**Comment by dbojicic-agency** [comment]
In review with @RichardTON.

**Comment by dbojicic-agency** [comment]
In internal review with @RichardTON.

**Comment by RichardTON** [comment]
### 9) Terminology page says "used" but lists "defined"
The [Terminoligy](http://build.fhir.org/ig/hl7au/au-fhir-base/terminology.html) page twice includes the text "used in this implementation guide." but the value sets and code systems listed are just the ones **defined** in the IG. For example [Australian Indigenous Status](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/australian-indigenous-status-1) value set is used in [Australian Indigenous Status](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-indigenous-status.html) extension but not mentioned here.

Change the text to "defined in this implementation guide."

**Comment by dtr-agency** [comment]
11. AU Medicine List. flag Medicine item change
12. The profile AU Gestational Age is being generated, as it is included in the ig.xml and ig.json, but it is not listed in the profiles.md. Link to generated profile page in the build: https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-gestationalage.html (migrated from #661)
13. Metadata issues on Gestational age. This was discussed with @dbojicic-agency and @oridashi - with the conclusion to create this ticket and proceed to do a PR to have this profile listed in the profiles.md in the Pregnancy Related Profiles section. (#661)

**Comment by dtr-agency** [comment]
16. there are still markdown pages from STU3 content that was initially migrated and didn't get deleted when we cleaned 
up the structure definitions e.g. section-author-intro.md. Need to clean this up.

**Comment by dtr-agency** [comment]
17. summary.md files are not used and not to be maintained - some are mistakenly being update e.g. au-medicationrequest-summary.md because at one point they were made current. Go through and replace all the content with a note that these files are maintained solely for IG Publisher and are not maintained.

**Comment by davidmckillop** [comment]
18.  The introduced AU Base short of "Approving practitioner" for performer:approvedBy.actor is NOT a good fit for the referenced content of "reference(Practitioner | PractitionerRole | Organization)" i.e. "Approving practitioner" is not a good fit for "Organization", and suggest that the AU Base short of "Approving practitioner" is deleted, so that the default short of "Administering performer" applies.

**Comment by robeastwood-agency** [comment]
19. typo in AU Diagnostic Imaging Report profile [short name for DiagnosticReport.code](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-imagingreport.xml#L86)
> Diagnostic imaging **exmaination** or study

**Comment by udaychandrupatla** [comment]
20. Link in AU Medicare Provider Number which resolves to [services Australia](https://www.servicesaustralia.gov.au/organisations/health-professionals/services/medicare/medicare-benefits-health-professionals/apply-medicare-provider-number/about-medicare-provider-numbers) does not resolve.

**Comment by davidmckillop** [comment]
21. In "extensions.md" remove line "Minimum Interval Between Repeats [FMM 1] - minimum allowed dispensing interval".
Note: this was missed in a conflict resolution from PR #688 .

**Comment by davidmckillop** [comment]
21. The profile au-medicationadministration is listed as having "No extensions are available for this profile.", but in the extension "Medication Type" is used.
Need to add "MedicationStatement.medication.coding: Medication Type" to the "Extensions used in this profile:" for au-medicationadministration.

**Comment by robeastwood-agency** [comment]
22. Hyperlink text for [medicationrequest-example2](https://github.com/hl7au/au-fhir-base/blob/master/examples/medicationrequest-example2.xml) is "_Prescription for Reaptan_" in all but 2 intro files.

The following 2 intro files have a different hyperlink text "[Prescription with brand name text](https://github.com/hl7au/au-fhir-base/blob/master/pages/_includes/medication-brand-name-intro.md?plain=1#L13)" and "[Prescription with generic name text](https://github.com/hl7au/au-fhir-base/blob/master/pages/_includes/medication-generic-name-intro.md?plain=1#L15)"

Update to "Prescription for Reaptan" for consistency

**Comment by robeastwood-agency** [comment]
23. AU Gestational Age - [title value](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-gestationalage.xml#L6) typo

`<title value="AU Gestional Age"/>` should be `<title value="AU Gestational Age"/>`

**Comment by davidmckillop** [comment]
24. 13. Contained example uses contained resource ids that are not good practice (i.e. uuids) need to fix: practitioner-example4

**Comment by davidmckillop** [comment]
25.  Typo: au-composition 
Conversion Note:  ".... andRelated ... "  should be "... and Related ..."

**Comment by robeastwood-agency** [comment]
26. Profile au-residentialagedcareserviceidentifier is missing the element StructureDefinition.date 
- add as today 
- increment patch number on StructureDefinition.version

**Comment by davidmckillop** [comment]
27.  AU Base Immunisation: performer:approvedBy.actor review of "short" #692 issue 
28.  was raised at [HL7 AU PA WG on 2/3/2022](https://confluence.hl7australia.com/display/PA/2022-03-02+Minutes) with the outcome being to change the short from "Approving practitioner" to "Approver".

**Comment by davidmckillop** [comment]
28.  Need to add the following content to "au-medicationrequest-intro.md":
Conversion
NOTE: AU Base on STU3 included the extension Minimum Interval Between Repeats which is now no longer required as direct R4 support is available."

**Comment by dtr-agency** [comment]
@davidmckillop remove ballot issues from this QA collector. This isn't a workflow story.
