### ISSUE TITLE
Enhancement - "Report Copies to" extension for ServiceRequest

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#670]
There isn't an equivalent place in FHIR to list the "Report Copies to" that are included in a request.
There is an extension [Information Recipient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-information-recipient.html) which is associated with Composition to list the "Report Copies" when the report is being distributed, but there isn't an equivalent extension to list the "Report Copies" on the request.
Need to create a "Report Copies to" extension for ServiceRequest to accommodate this functionality.

**Comment by angusmillar** [comment]
Genie Software and Sonic Pathology Austrlia are working on a FHIR Ordering project. 
 
One aspect of this project is that we do not want to lose functionality found in the current HL7 V2 ORM ordering today. Furthermore, we will be converting FHIR orders back into HL7 ORM Messages internally to feed them into our existing backend orders processes. 
 
Sonic have an 95% working FHIR to HL7 V2 ORM conversion working based on a set of FHIR resources representing a group of Pathology orders, primarily focuses around the ServiceRequest resource. In doing so, we found that most data elements are provided in the Base R4 FHIR resource profiles given all your hard work on the AU Base R2 extensions and Australianisations. Well done, guys!
 
However, one key concept stands out as missing. That is, 'Copy To' doctors.
 
Found in the [HL7AUSD-STD-OO-ADRM-2021.1](https://confluence.hl7australia.com/display/OOADRM20211/Australian+Diagnostics+and+Referral+Messaging+-+Localisation+of+HL7+Version+2.4) HL7 V2 specification in [Section 4.4.1.28 OBR-28 Result copies to (XCN) 00260](https://confluence.hl7australia.com/display/OOADRM20211/4+Observation+Reporting#id-4ObservationReporting-4.4.1.28OBR-28Resultcopiesto(XCN)00260) it is defined as: "This field is the people who are to receive copies of the results." Furthermore, in the Observation Ordering section [5.5 Australian usage notes](https://confluence.hl7australia.com/display/OOADRM20211/5+Observation+Ordering#id-5ObservationOrdering-5.5Australianusagenotes), it states, in the 4th last sentence:  "Desired Copy Doctors for the result should be transmitted using OBR-28 Result Copies To in the order."
 
While defined in the Australian HL7 V2 specification the same concept appear to be missing in both international R4 FHIR specification and the Australian AU Base R2 profiles. While there is an AU Base R2 extension on the Composition resource named [information-recipient](http://hl7.org.au/fhir/2021Aug/StructureDefinition-information-recipient.html); this extension is close.  Yet, it is not the correct concept. It represents 'this' Composition (Document) has or will be sent to a set of recipients. If we were to use this around a ServiceRequest (Order), it would imply that a copy of the order is sent to the recipients, which is not our intent. Instead, we want a concept that instructs the order’s performer to send copies of the outcome (Pathology Reports) to a set of recipients. We are also not intended to use a composition resource.

Their are currently no firm completion dates for our project although at best guess we expect to be looking at production use in the first to second quarter of next year, 2022.

**Comment by davidmckillop** [comment]
HL7 AU O&O supported the reqeust ot have a "Report Copies to" extension for ServiceRequest (ordering) -  refer to the resolution at the meeting held 14th December 2021 [here](https://confluence.hl7australia.com/display/OO/2021-12-14+Meeting+Notes).

**Comment by angusmillar** [comment]
Hi Guys, any progress on this extention request for 'Copy to' doctors?
I had a look at the most current 'Continuous Integration Build R4' for AU Base R4 and I don't see anything.
I'm now at the stage of writing the code so I really need some indication as to what the externtion will look like, what its URL might be.
Has there been any progress, are there any blockers?

**Comment by gonatf** [comment]
Just to put my 2c of support into this.  While in future we may be able to use other means to achieve the copy-to semantics, for now we'll need this extension to be backward compatible into the v2 universe.

andy

**Comment by dtr-agency** [comment]
Agreed to go in as DRAFT 0 only - not in ballot scope but available for comment.

**Comment by angusmillar** [comment]
I've lately been eyeing off the CommunicationRequest resource as a possibility for this concept. Though it is a very verbose way of achieving the goal.
