### ISSUE TITLE
Home page has inconsistent copyright symbols for instances of "FHIR"

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#675]
The home page of the [AU Base 2 Australian Base Implementation Guide](http://build.fhir.org/ig/hl7au/au-fhir-base/index.html) has 14 instances of the term "FHIR" in general text with inconsistent use of copyright and trademark symbols. For instance:
- 4 instances of “FHIR ®©” scatted throughout (with superscripted symbols)
- 10 instances of just “FHIR” interspersed amongst the others

The inconsistency needs to be fixed but it is unclear what the correct usage should be.

The FHIR spec itself and prominent implementation guides (like US Core) seem the have the pattern of:
-	the home page has " FHIR®" as the first instance, and thereafter has just "FHIR"
-	subsequent pages have only "FHIR"

The R4 spec page on [License and Legal Terms](http://hl7.org/fhir/license.html) has nothing specific about implementation guides, but states this:
> You can use the trademarks "FHIR" and the logo to refer the FHIR specification itself.

> When referencing the FHIR® standard in a website, document, presentation, or otherwise, please in a place of prominence refer to it as the "HL7® FHIR® standard". In subsequent uses, please refer to it as the "FHIR® standard" or "FHIR®", using the ® symbol as often as is practical, at least once on each page of printed matter, generally in connection with the first or dominant usage.

**Comment by oridashi** [comment]
we have met the requirements as per https://build.fhir.org/license.html
so closing
