### ISSUE TITLE
AU Base Encounter.serviceType binding

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#684]
From HL7 Australian Base FHIR Implementation Guide ballot content found at http://hl7.org.au/fhir/2021Aug, feedback https://jira.hl7australia.com/browse/FHIRIG-191

http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-encounter.html

May I request clarification for the following bindings?:

Service Type is 'example' binding but not bounded with https://healthterminologies.gov.au/fhir/ValueSet/service-type-1 as preferred?
Reporter:Shovan Roy
Email:shovan.roy.fhir@gmail.com

**Comment by dtr-agency** [comment]
Approved for action with @oridashi,  @davidmckillop please progress this via PR.

**Comment by davidmckillop** [comment]
The valueset https://healthterminologies.gov.au/fhir/ValueSet/service-type-1 has been bound (preferred) to Encounter.serviceType element.
