### ISSUE TITLE
Vital sign profiles - URLs either do not resolve or resolve incorrectly

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#685]
These HL7 AU vital sign profile canonical URLs do not resolve to their respective profile pages (ie return 404 errors):

-  http://hl7.org.au/fhir/StructureDefinition/au-bloodpressure
-  http://hl7.org.au/fhir/StructureDefinition/au-bmi
-  http://hl7.org.au/fhir/StructureDefinition/au-bodytemp
-  http://hl7.org.au/fhir/StructureDefinition/au-heartrate
-  http://hl7.org.au/fhir/StructureDefinition/au-resprate
-  http://hl7.org.au/fhir/StructureDefinition/au-oxygensat
-  http://hl7.org.au/fhir/StructureDefinition/au-vitalspanel

These HL7 AU vital sign profile canonical URLs _do_ resolve but to their STU3 AU Base 1 counterpart, rather than the R4 AU Base 2 version:
- http://hl7.org.au/fhir/StructureDefinition/au-bodyheight
- http://hl7.org.au/fhir/StructureDefinition/au-bodyweight
- http://hl7.org.au/fhir/StructureDefinition/au-headcircum

**Comment by dtr-agency** [comment]
This is a variation of https://github.com/hl7au/au-fhir-base/issues/561.

**Comment by robeastwood-agency** [comment]
Closing, as content has been moved into an existing ticket #561
