### ISSUE TITLE
PBS CodeSystem - warning about being unknown even when present

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#686]
A forthcoming MedicationAdministration example (against [AU Base Medication Administration](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationadministration.html)) has a use of a PBS code (the first among the example set). As a result, the QA report issues this warning:
> Code System URI 'http://pbs.gov.au/code/item' is unknown so the code cannot be validated

Note that:
* the PBS Item Codes ValueSet that is bound to `MedicationAdministration.medication[x]:medicationCodeableConcept.coding:pbs` is present in HL7AU: [http://terminology.hl7.org.au/ValueSet/pbs-item](http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-pbs-item.html)
* and the corresponding PBS Item Codes CodeSystem is also present in HL7AU: with canonical URL as http://pbs.gov.au/code/item and resolvable end point: http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-pbs-item-external.html
* the PBS Item Codes `CodeSystem.content` value is set to ["not-present"](https://github.com/hl7au/au-fhir-base/blob/master/resources/codesystem-pbs-item-external.xml#L28)

**Queries**: 
* is it appropriate to have a warning that the CodeSystem is "unknown" when it clearly exists in this IG?
* would a different warning (ie from the IG Publisher) be more appropriate when a CodeSystem declares that its content is not present?
* is there something incorrect in the CodeSystem?

Note that this also affects the [MIMS CodeSystem](http://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-mims-external.html) which also declares its content as not present.

**Comment by oridashi** [comment]
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/QA.20Codesystem.20Information.20notice.20query talks about this behaviour; is currently how IGPublisher shows the issue whether not content or no no valueset having the same message.
