### ISSUE TITLE
AU Base Immunisation: performer:approvedBy.actor review of "short"

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#692]
The introduced AU Base short of "Approving practitioner" for performer:approvedBy.actor is NOT a good fit for the referenced content of "reference(Practitioner | PractitionerRole | Organization)" i.e. "Approving practitioner" is not a good fit for "Organization", and suggest that the AU Base short of "Approving practitioner" is deleted, so that the default short of "Administering performer" applies.

**Comment by dtr-agency** [comment]
@davidmckillop address in QA collector if okayed by @oridashi

**Comment by davidmckillop** [comment]
Issue raised at [HL7 AU PA WG on 2/3/2022](https://confluence.hl7australia.com/display/PA/2022-03-02+Minutes) with the outcome being to change the short from "Approving practitioner" to "Approver".

**Comment by dtr-agency** [comment]
@davidmckillop this isn't a QA issue - do not mention it in #667 that isn't a PR number it is an issue number.

**Comment by robeastwood-agency** [comment]
A fix for this coming via a forthcoming PR

**Comment by davidmckillop** [comment]
Fixed by PR #702
