### ISSUE TITLE
Add guidance on Observation.category to child health and pregnancy profiles

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#699]
Observation.category can be used to support finding observations. Vital signs profiles provide such guidance. Something similar would be useful for child health and pregnancy observations.

**Item 1**
Add guidance on use of Observation.category to child health and pregnancy profiles of Observation in HL7 AU.

Only limited guidance can be provided as the values and use of Observation.category is contended in [Zulip and by the OOWG](https://chat.fhir.org/#narrow/stream/179256-Orders-and-Observation-WG/topic/Signs.20and.20Symptoms/near/274157411)

Relevant profiles are:

- [AU Estimated Date of Delivery](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-estimateddateofdelivery.html) - this may be determined by an examination, by imaging, or by a calculation from an interview. This complexity is not yet ready for guidance.
- [AU Gravidity](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-gravidity.html) - this may be determined by an interview, there is no suitable code in [Observation Category Codes](http://hl7.org/fhir/R4/valueset-observation-category.html) for this. See comment below.
- [AU Last Menstrual Period](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-lastmenstrualperiod.html) - ditto
- [AU Parity](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-parity.html) - ditto
- [AU Smoking Status](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-smokingstatus.html) - [social-history](http://hl7.org/fhir/R4/codesystem-observation-category.html#observation-category-social-history) 

~~**Item 2**
It might be worth having a new category code: obstetric-history~~
It will take much time to get agreement on any such category. Removed from this issue.

**Comment by RichardTON** [comment]
Made them required.

**Comment by dtr-agency** [comment]
@RichardTON request to add to sex assigned as birth and assertion of no relevant finding.

Don't necessarily agree that category it to be mandatory.

**Comment by RichardTON** [comment]
The categories should be optional.
This is hard. 
- Slicing Category by value:coding.system and coding.code prevents any instance of category that matches a slice from having alternate codings.
- I am unable to get slicing by pattern:$this to work
- Using an invariant can test for an instance of category with the expected value while allowing alternate codings, but it will throw an error or warning and is not much use as guidance.

**Comment by RichardTON** [comment]
The preferred values of Observation.categories in Core are contested in Zulip.
It is unclear what code from [Observation Category Codes](http://hl7.org/fhir/R4/valueset-observation-category.html) is suitable for observations that are based on an interview. The name of [survey](http://hl7.org/fhir/R4/codesystem-observation-category.html#observation-category-survey) suggests that it is OK for a questionnaire, but its examples suggest otherwise. But it does not seem suited to an interview. Even [exam](http://hl7.org/fhir/R4/codesystem-observation-category.html#observation-category-exam) seems unsuited.

**Comment by RichardTON** [comment]
Add guidance that the category social-history is relevant to smoking-status. Add no other guidance.

**Comment by RichardTON** [comment]
Category for 
- sex assigned at birth - [exam](http://hl7.org/fhir/R4/codesystem-observation-category.html#observation-category-exam) is a reasonable fit
- assertion of no relevant finding - no good fit in [Observation Category Codes](http://hl7.org/fhir/R4/valueset-observation-category.html)

**Comment by dtr-agency** [comment]
@RichardTON - this appears to have stalled. Please progress or close.

**Comment by RichardTON** [comment]
Progress - https://chat.fhir.org/#narrow/stream/179256-Orders-and-Observation-WG/topic/Use.20of.20Observation.2Ecategory/near/277834955

**Comment by brettesler-ext** [comment]
F2F comment - content was transferred to AU Core - as specific clinical content - propose create new ticket in AU core Jira and close this ticket

**Comment by hl7auadmin** [comment]
eVote: this is now being completely reviewed and actioned by the AU Core TDG business; Propose close.

**Comment by brettesler-ext** [comment]
Closed as no longer relevant https://confluence.hl7.org/display/HAFWG/2024-04-10+FHIRWG+Meeting+Minutes
