### ISSUE TITLE
Feature - Add the Luhn Check for identifier.value for IHI, HPI-I, HPI-O, PAI-D, PAI-R, PAI-O etc.

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#7]
This is in relation to the invariant(s)/constraint(s) for the Luhn algorithm check in the applicable identifiers like IHI, HPI-I, HPI-O, PAI-D, PAI-R, PAI-O etc. 

Attached are a few files related to the Luhn Check FHIRpath constraint.
[Device.identifier.value.txt](https://github.com/hl7au/au-fhir-base/files/1361644/Device.identifier.value.txt)
[value_1.txt](https://github.com/hl7au/au-fhir-base/files/1361646/value_1.txt)
[value_2.txt](https://github.com/hl7au/au-fhir-base/files/1361645/value_2.txt)
[value_3.txt](https://github.com/hl7au/au-fhir-base/files/1361650/value_3.txt)

So my main queries here are::

1) Is it safe to add the constraint that -- the identifier.value SHALL be an exactly 16 digit number? 
The current constraint is that -- it shall be a 16 character string; which can be replaced by the above constraint in case there are no issues in doing so. 

2) The FHIRpath for the Luhn check has been tested with the “FhirPathTester” as given in the “Device.identifier.value.txt” file. It was tested against the Device resource.
The modified version as given in the “value_1.txt, value_2.txt, value_3.txt” files could not be tested but is not giving any error when added in the profile using Forge. 

Please suggest if it is a good idea to include this constraint and if yes then can the expression be tested by you or someone else for veracity.

**Comment by robeastwood-agency** [comment]
Discussion at the HL7 AU Patient Admin Working Group today ([miniutes](http://confluence.hl7australia.com/display/PA/2017-10-11+Minutes)), @brianpos proposed that the Luhn check be added as a custom function to the FHIRpath specification. The Luhn check is used in a number of identifiers and therefore would have broad applicability.

**Comment by davidmckillop** [comment]
There is now a pull request for Luhn check for device. #10

**Comment by oridashi** [comment]
done - added in at the identifier.value level
