### ISSUE TITLE
5 Pregnancy Related Profiles - various issues to be considered / addressed

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#700]
The 5 Pregnancy Related Profiles, all of draft 0, are 
* [AU Estimated Date of Delivery](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-estimateddateofdelivery.html)
* [AU Gestational Age](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-gestationalage.html)
* [AU Gravidity](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-gravidity.html)
* [AU Last Menstrual Period](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-lastmenstrualperiod.html)
* [AU Parity](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-parity.html)

Various issues to be addressed:

### 1) AU Parity and AU Gravidity - consider valueInteger instead of valueQuantity
The [AU Parity]() and [AU Gravidity]() profiles both have Observation.value[x] as valueQuantity with
* an invariant on valueQuantity.value to prohibit a decimal point, as it is of datatype decimal
* a fixed value for the mandatory valueQuantity.system, as "http://unitsofmeasure.org"
* a fixed value for the mandatory valueQuantity.code as "1" so that the value is count of 1's
* valueQuantity.value is optional, allowing no value to be added along with the mandatory system and code

There may be a principle underlying this approach in that count observations should be valued using quantity, but in the absence of that, consideration should be given to simplifying the value[x] to instead be valueInteger. 

The invariant could be dropped (unless it was desirable to rule out negative integers)

### 2) Standardise allowed effective[x] type
Other Observation profiles limit their Observation.effective[x] type to be datetime - see [AU Smoking Status](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-smokingstatus.html) and [AU Biological Sex Assigned at Birth](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-sexassignedatbirth.html). The 5 pregnancy related profiles include different options inconsistently, and in the absence of a good reason, consideration should be given to be limited to effectiveDateTime. Currently they are:
* [AU Estimated Date of Delivery](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-estimateddateofdelivery.html) - has effectiveDateTime and effectiveInstant
* [AU Gestational Age](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-gestationalage.html) - has effectiveDateTime and effectiveInstant
* [AU Gravidity](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-gravidity.html) - has effectiveDateTime and effectivePeriod
* [AU Last Menstrual Period](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-lastmenstrualperiod.html) - has effectiveDateTime and effectivePeriod
* [AU Parity](https://github.com/hl7au/au-fhir-base/issues/StructureDefinition-au-parity.html) - has effectiveDateTime and effectivePeriod

### 3) AU Gestational Age - incorrect slice on Observation.code.coding
This profile has a constraint on slice being at the incorrect level at Observation.code.coding. The constraint should be applied at the Observation.code level i.e. (system=”http://snomed.info/sct” and code=”57036006”). See explanation for identical issue (ballot comment) for AU Estimated Date of Delivery [FHIRIG-161](https://jira.hl7australia.com/browse/FHIRIG-161). 

Identical fixes for the other 4 pregnancy related profiles is in HL7 AU build.

**Comment by dtr-agency** [comment]
This is a redundant set of issues now. Will close this and as issues are identified or changes are to be made for each profile we can raise a new issue.
