### ISSUE TITLE
Extension Medication Type context has entries for ValueSet and CodeSystem

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#703]
The extension [Medication Type](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-medication-type.html) has the expected StructureDefinition.context values related to various medication profiles. 

However it does also contain 4 context entries for ValueSet and CodeSystem, which look unnecessary and potentially incorrect. See lines https://github.com/hl7au/au-fhir-base/blob/master/resources/structuredefinition-medication-type.xml#L54-L69

Without knowing the background to how this extension came about, and specifically the lines linked above, I am raising here for consideration of appropriateness, rather than simply offering line deletions in another PR.

I'm told that this zulip thread has related background: https://chat.fhir.org/#narrow/stream/179173-australia/topic/concept.20type.20extension

**Comment by dtr-agency** [comment]
@oridashi please reply on this - this will need to be addressed in the ballot.

**Comment by oridashi** [comment]
this is a use for defining a classification for code systems/valueset expansion
1) more guidance on this is needed in narrative to expain this use
2) consideration is needed on being able to enable ValueSet definitions to add medication type extensions at that level (based on CodeSystems that do not have medication type defined)

**Comment by robeastwood-agency** [comment]
Raised HL7AU ballot 4.1.0 ticket: [FHIRIG-238](https://jira.hl7australia.com/browse/FHIRIG-238)

**Comment by dt-r** [comment]
Narrative was added via https://github.com/hl7au/au-fhir-base/commit/25f3324edbaf9dbf566422ea58ae84e82ae32081.

Please review.

**Comment by robeastwood-agency** [comment]
Closing with no change required.
