### ISSUE TITLE
Rendered IG - no longer displaying xml, json or turtle views

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#704]
All profile and example pages in the rendered IG have tabs to display the xml, json and turtle views of the respective artifacts. Up until recently, the tabs operated as expected (see an example patient xml in the **Aug 2021 snapshot** build: http://hl7.org.au/fhir/2021Aug/Patient-example2.xml.html). This also allows to display of json and turtle as expected.

The current build however has the same tab headings, but clicking on them no longer shows their respective xml/json/turtle views. See the same patient example xml tab view: http://build.fhir.org/ig/hl7au/au-fhir-base/Patient-example2.xml.html

This occurs for both examples, structure definitions (profiles and extensions), CodeSystems and ValueSets within the IG. 

The likely (but unconfirmed) point at which this change occurred was this commit (2a0c50f3ecd5e23ee2bd7ebb56df6f0ab5ab3419) to the legacy json rendering template files that was necessary to resolve a failure to build issue reported at that time. Therefore, if this is the cause, then it is not as simple as reverting this commit, but something related to the changes within the commit.

**Comment by dtr-agency** [comment]
This issue is mentioned in https://github.com/hl7au/au-fhir-base/issues/673.

**Comment by dtr-agency** [comment]
Fixed https://github.com/hl7au/au-fhir-base/commit/71dc6b153113ad3ca790e024496fb7cf45215262
