### ISSUE TITLE
Remove unused markdown files copied from old STU3 IG

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#705]
With the transition from the [old STU3 HL7AU repository](https://github.com/hl7au/au-fhir-base-stu3) to this R4 repository, a number of profile markdown files were copied across but can now be removed (in order to clean up the repository). None of the files are used in the generated R4 IG and can safely be removed. 

They are markdown files (in the folder [/pages/_includes](https://github.com/hl7au/au-fhir-base/tree/master/pages/_includes)) for these artefacts:
- associated-practitionerrole (extension)
- attester-related-party (extension)
- au-device (profile) - _note that there may be future interest in such a profile_
- au-endpoint (profile) - _note that there may be future interest in such a profile_
- au-immunizationrecommendation (profile)
- au-observation-age (profile)
- author-role (extension)
- base-composition-v1 (profile)
- category-additional (extension)
- composition-author-role (extension)
- encounter-destination-organisation (extension)
- encounter-origin-organisation (extension)
- healthcareservice-communication (extension)
- healthcareservice-eligibility-detail (extension)
- list-source-role (extension)
- medication-administration-witness (extension)
- medication-strength-text (extension)
- minimum-interval-between-repeats (extension)
- pbs-sponsor (profile)
- pbs-sponsor-organisation (profile)
- performer-party (extension)
- profile (early profiles file)
- recorder (extension)
- section-author (extension)
- shs-v1 (profile)

The files include "<`id`>-intro.md", "<`id`>-summary.md", "<`id`>-search.md" and "<`id`>-watermark.md".

**Comment by dtr-agency** [comment]
Not all of the above fall into that category - they aren't used now but they may be in future. There is need to clean up the underlying repository this should not be targeted to unused markdown files copied from old STU3 IG.

**Comment by dtr-agency** [comment]
Done.
