### ISSUE TITLE
Extension: IHI Verified - better align name/url/id with allowed dateTime value

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#706]
[Extension: IHI Verified](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-ihi-verified.html) is specifically to "_represent the date/time that the Individual Healthcare Identifier (IHI) was verified with HI Services._".

The profile's id, URL imply boolean or code, not date, and are therefore misleading. The title is good however.

Requesting consideration of updating these values to be in line with the intended purpose.

**Comment by robeastwood-agency** [comment]
On agenda for forthcoming HL7AU Patient Admin WG: https://confluence.hl7australia.com/display/PA/2022-03-16+Minutes

**Comment by dtr-agency** [comment]
Propose ihi-verified extension would be better with url ihi-verified-date to clarify the type of information
