### ISSUE TITLE
AU Base Medication Request profile - needs clarification of purpose

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#707]
The [AU Base Medication Request profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicationrequest.html) has aspects indicating that it is a "base" profile and others indicating that it is specifically for prescription. Therefore, its purpose needs clarification with consequential updates made to various parts of the profile to align.

Note that a medication request does not have to be a prescription - see the [core spec MedicationRequest resource](http://hl7.org/fhir/medicationrequest.html):
> The resource is called "MedicationRequest" rather than "MedicationPrescription" or "MedicationOrder" to generalize the use across inpatient and outpatient settings, including care plans, etc., and to harmonize with workflow patterns.

and 
> It also includes orders for over-the-counter medications (e.g. Aspirin), total parenteral nutrition and diet/ vitamin supplements.

Aspects of the profile indicating a "base" profile:
- the [name](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-medicationrequest.xml#L6) "AUBaseMedicationRequest"
-  the [title](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-medicationrequest.xml#L7) "AU Base Medication Request"
- supporting content in intro file

Aspects of the profile indicating a prescription:
- the [description value](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-medicationrequest.xml#L19): "...for use as a prescription in ..."
- [root element short](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-medicationrequest.xml#L37): "A prescription for a ..."
- [root element definition](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-medicationrequest.xml#L38): "Prescription of medication"
- [short name of medicationReference](https://github.com/hl7au/au-fhir-base/blob/master/resources/au-medicationrequest.xml#L190): "Prescribed Medication"
- supporting content in intro file

**Comment by dtr-agency** [comment]
AU Base Medication Request is a base profile, if a prescription profile is desired a new profile with appropriate canonical url and set of rules should be created though I am not aware at the moment of a stakeholder request for an HL7 AU Prescription profile.
