### ISSUE TITLE
Inconsistent status wrt FMM level

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#708]
[FHIRIG-155](https://jira.hl7australia.com/browse/FHIRIG-155) is reviewing FMM Level 1 and FMM level 2 artifacts to determine if they are ready for use and hence have a status = "active".

However, there are some inconsistencies in the Draft 0 profiles and the FMM 3 profiles with respect to their status.
These are:
Draft 0 profiles with status = "active" 
- structuredefinition-medication-strength
- structuredefinition-ethnicity
(where all other Draft 0 artifacts have status = "draft")

FMM level 3 profile with status = "draft"
-  structuredefinition-encryption-certificate-pem-x509
(where all other FMM 3 artifacts have status = "active")

Should all Draft 0 artifacts have a status ="draft" and should all FMM 3 artifacts have a status = "active"?

**Comment by dtr-agency** [comment]
FHIRIG-155 is a query on understanding how the levels progress. The necessary actions for that ballot ticket will be handled as part of ballot.

@davidmckillop - draft 0 profiles cannot be considered active - these are typos. Please direct the query on the FMM 3 with status of draft to the working group that owns that extension to confirm it's appropriate status.

**Comment by davidmckillop** [comment]
Discussed with @oridashi and the proposal is for:
Draft 0, FMM1 & FMM2 to have a status = draft.
FMM 3 and beyond to have status = active.

**Comment by dtr-agency** [comment]
So the outcome is that there is clean up to do in status on the three structure definitions. This will need to be completed for ballot.  
@oridashi or @davidmckillop will either of you pick this up?
