### ISSUE TITLE
AHPRA extensions and content

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#736]
Review extensions and Practitioner.qualification usage - this is primarily a concern of PCA project and may take out of AU Base / simplify this.

**Comment by oridashi** [comment]
PAWG agreed to keep this in ballot; will assume negative votes will be received and at least more description and explanation needed.

**Comment by dt-r** [comment]
New issue submited to JIRA. 
[FHIRIG-240](https://jira.hl7australia.com/browse/FHIRIG-240)
**Why are Ahpra registration details and Ahpra profession details mutually exclusive concepts?**
Why are Ahpra registration details and Ahpra profession details mutually exclusive? Or at least entirely separate qualification concepts?

AU Base Practitioner is enforcing this constraint but it is unclear to me why a single qualification instance with both extensions present is undesirable and are not two different dimensions of information given the definition of data elements.

The result is either that you never supply registration and profession details or there are two instances of a qualification with same identifier but each have different extensions.

Reporter:Danielle Tavares-Rixon
Email:danielle.tavares-rixon@csiro.au

**Comment by dt-r** [comment]
Briefly discussed at PAWG:
1. not in scope of ballot for 4.1.0
2. the extensions shouldn't be mutually exclusive
3. @oridashi to advise PCA project, and write up brief response
4. PR to be submitted when PCA has been advised

**Comment by brettesler-ext** [comment]
F2F comment - this needs some content development with respect to explaining all concepts completely in the specification

**Comment by brettesler-ext** [comment]
Moved to Jira https://jira.hl7.org/browse/FHIR-46327
