### ISSUE TITLE
Inherited extensible bindings are misrepresented in profiles

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#737]
There is a problem with the use of extensible bindings in AU Base.

When an element has an extensible binding to a value set, conformant instances must include a value from that value set if one is appropriate. [R4's description of extensible](http://hl7.org/fhir/R4/terminologies.html#extensible) includes

> If there is at least one applicable concept in the extensibly-bound value set with a meaning which includes but is more general than the meaning that is intended to be represented by the element in the resource instance, then the code that is used in the instance SHALL be taken from the value set and should be the closest available match for the intended element instance meaning (i.e. neither more general or more specific). However, a more specific code that more completely represents the intended meaning may also be included in the instance as an additional Coding if the data type is CodeableConcept, but it cannot be used instead of the code from the value set. This helps ensure that systems know which codes they should expect to receive and build logic for and it facilitates interoperability.

The CI build of R5 has new wording for [extensible](http://build.fhir.org/terminologies.html#extensible) with the same meaning. Related Zulip threads include [Extensible binding of Identifier.type](https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Extensible.20binding.20of.20Identifier.2Etype) and [Vocabulary WG survey on FHIR extensible binding strength](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Vocabulary.20WG.20survey.20on.20FHIR.20extensible.20binding.20strength).

This has not been made obvious in some HL7 AU Base profiles, they imply that it is enough to use a code from an extended version of the value set.

For example, [Encounter.class](http://hl7.org/fhir/R4/encounter.html) in R4 is bound extensibly to [V3 Value SetActEncounterCode](http://hl7.org/fhir/R4/v3/ActEncounterCode/vs.html). This includes the code [VR](http://hl7.org/fhir/R4/v3/ActCode/cs.html#v3-ActCode-VR). In [AU Base Encounter](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-encounter.html) class is bound to a value set with extra codes. All of the extra codes are subsumed by VR, so all conformant instances with one of the new codes need to also include VR, and there is no hint of this in the profile, or in the examples.

This problem also applies to many of the AU Base profiles of Identifier, as [Identifier.type](http://hl7.org/fhir/R4/datatypes.html#Identifier) in Core has an [extensible](https://hl7.org/fhir/terminologies.html#extensible) binding to [IdentifierType](http://hl7.org/fhir/valueset-identifier-type.html). Note that the descriptions of the codes have been updated between R4 and R4B.

The descriptive parts of the profiles and examples need to be updated so that implementers are not misled.

See also https://jira.hl7.org/browse/FHIR-37739

**Comment by RichardTON** [comment]
Review of profiles of Identifier in [AU Base](http://build.fhir.org/ig/hl7au/au-fhir-base/profiles.html)
Profile | Problem | Effect
-- | -- | --
AU Accession Number | Required   binding to valueset with code outside IdentifierType | Some   conformant instances need two codings. For example, sending LACSN requires   sending ACSN as well.
AU Australian Business Number | Vague   guidance | XX is the   only valid code
AU Australian Company Number | Vague   guidance | XX is the   only valid code
AU Australian Registered Body Number | Vague   guidance | XX is the   only valid code
AU AHPRA Registration Number | Required   value subsumed by one in IdentifierType | PRN is needed
AU Care Agency Employee Identifier | Required   value subsumed by one in IdentifierType | PRN is needed
AU Commonwealth Seniors Health Card Number | Required   value subsumed by one in IdentifierType | SB is needed
AU CSP Registration Number | Required   value subsumed by one in IdentifierType | PRN is needed
AU Delivery Point Identifier | No probs |  
AU DVA Number | Required   binding to valueset with code outside IdentifierType | JHN is needed
AU Employee Number | No probs |  
AU ETP Prescription Identifier | Required   value subsumed by one in IdentifierType | PLAC is   needed
AU G-NAF Identifier | No probs |  
AU Health Care Card Number | Required   value subsumed by one in IdentifierType | SB is needed
AU HPI-I | Required   value subsumed by one in IdentifierType | PRN is needed
AU HPI-O | Required   value subsumed by one in IdentifierType | PRN is needed
AU IHI | Required   value subsumed by one in IdentifierType | JHN is needed
AU Insurance Member Number | No probs |  
AU Local Dispense Identifier | No probs |  
AU Local Order Identifier | No probs |  
AU Local Prescription Identifier | Required   value subsumed by one in IdentifierType | PLAC or FILL   is needed, what if it is unknown which applies? Maybe then neither PLAC nor   FILL is needed.
AU Local Report Identifier | No probs |  
AU Location Specific Practice Number | No probs |  
AU Medical Record Number | No probs |  
AU Medicare Card Number | Required   value subsumed by one in IdentifierType | JHN is needed
AU Medicare Provider Number | Required   value subsumed by one in IdentifierType | PRN is needed
AU NATA Accreditation Number | Required   value subsumed by one in IdentifierType | PRN is needed
AU NATA Site Number | No probs |  
AU National Provider Identifier At Organisation | Required   value subsumed by one in IdentifierType | PRN is needed
AU PAI-D Identifier | ? | Might be a   UDI
AU PAI-O Identifier | Required   value subsumed by one in IdentifierType | PRN is needed
AU PBS Prescriber Number | Required   value subsumed by one in IdentifierType | PRN is needed
AU Pensioner Concession Card Number | Required   value subsumed by one in IdentifierType | SB is needed
AU Pharmacy Approval Number | Required   value subsumed by one in IdentifierType | PRN is needed
AU Residential Aged Care Service Identifier | Required   value subsumed by one in IdentifierType | PRN is needed

**Comment by RichardTON** [comment]
The boundary between SB and JHN is unclear. See Jira thread [Identifier Type Codes](https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Identifier.20Type.20Codes). Some of the BSs and JHNs in the table above may need changing.

**Comment by RichardTON** [comment]
Subsumption in [Identifier Type Codes](https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Identifier.20Type.20Codes) is problematic. See https://jira.hl7.org/browse/UP-331

**Comment by dtr-agency** [comment]
@RichardTON the WG session identified that some of the above were not applicable. and further outcomes for this. Please update this concern and progress.

**Comment by oridashi** [comment]
@RichardTON discussed in PAWG https://confluence.hl7australia.com/display/PA/2022-07-06+Minutes 
- can we have narrative around AU Base IdentifierType being a non-hierarchal codesystem therefore we have specific codes defined for specific identifiers and will by choice chose an appropriate

**Comment by RichardTON** [comment]
The 

> @RichardTON the WG session identified that some of the above were not applicable. and further outcomes for this. Please update this concern and progress.

In the review of profiles of identifiers the list of identifiers and candidate parent terms has been replaced with an analysis arguing that no current Australian identifier types are subsumed by codes in [IdentifierType code system](http://terminology.hl7.org/CodeSystem/v2-0203)

**Comment by RichardTON** [comment]
Review of profiles of Identifier in [AU Base](http://build.fhir.org/ig/hl7au/au-fhir-base/profiles.html)

* [Identifier.type](http://hl7.org/fhir/R4/datatypes.html#Identifier) in Core has an [extensible](https://hl7.org/fhir/terminologies.html#extensible) binding to [IdentifierType value set](http://hl7.org/fhir/valueset-identifier-type.html). Despite appearances, there is no hierarchy of values in [IdentifierType value set](http://hl7.org/fhir/valueset-identifier-type.html) or in [IdentifierType code system](http://terminology.hl7.org/CodeSystem/v2-0203) from which it draws its values (see [FHIR-37739](https://jira.hl7.org/browse/FHIR-37739)).

  * This implies that only identifier types outside [IdentifierType code system](http://terminology.hl7.org/CodeSystem/v2-0203) could be subsumed by a value in [IdentifierType value set](http://hl7.org/fhir/valueset-identifier-type.html). So in AU Accession Number ACSN does not subsume LACSN

* PRN is for local provider numbers, and is not intended for identifiers that are widely recognised. 
  * Identifies like HPI-Is are not local and are not within the intended scope of PRN. 
  * CAE includes employees that are not providers and are outside the scope of PRN.

* JHN is for sub-national identifiers. 
  * Identifies like IHIs are not local and are not within the intended scope of JHN. 

* SB identifies individuals (persons, organisations) not entitlements. 
  * Identifiers like AU Health Care Card Number identify entitlements and are not within the intended scope of SB.

**Comment by RichardTON** [comment]
Identifier type profiles requiring changes:

1. In [AU Accession Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-accessionnumber.html) when type includes the coding LACSN is must also include the coding ACSN.

no others

**Comment by RichardTON** [comment]
Updated review of profiles of Identifier in [AU Base](http://build.fhir.org/ig/hl7au/au-fhir-base/profiles.html)

Profile | Assessment | Effect
-- | -- | --
AU Accession Number |   According to https://jira.hl7.org/browse/FHIR-37739 "LACSN is a type of ACSN so ACSN would be the appropriate code to send and LACSN could also be sent if desired". | Some conformant instances need two codings. For example, sending LACSN requires sending ACSN as well. Maybe drop LACSN from the profile
AU AHPRA Registration Number | This is skill specific, so not a provider and thus not PRN. No others relevant. | none
AU Care Agency Employee Identifier |  Not always providers, so not PRN. No others relevant. | none
AU Commonwealth Seniors Health Card Number |  This is national, not state/province based, so is not JHN. This identifies an entitlement, not a person, so is not SB. Nothing else relevant. | none
AU CSP Registration Number |  CSPs supply IT services, no health related services, so not PRN. Nothing else relevant. |  none
AU Delivery Point Identifier |   Identifies an address. Nothing relevant. |  none
AU DVA Number |  This is national, not state/province based, so is not JHN. This identifies an entitlement, not a person, so is not SB. Nothing else relevant. | none
AU Employee Number |   Nothing relevant. |  none 
AU ETP Prescription Identifier | The identifier is allocated by middleware, not the source system, so not PLAC. Nothing else relevant. | none
AU G-NAF Identifier |   Identifies an address. Nothing relevant. |  none 
AU Health Care Card Number |  This is national, not state/province based, so is not JHN. This identifies an entitlement, not a person, so is not SB. Nothing else relevant. | none
AU HPI-I | This is national, not local/jurisdictional, so not PRN. No others relevant. | none
AU HPI-O | This is national, not local/jurisdictional, so not PRN. No others relevant. | none
AU IHI | This national, not state/province based, so is not JHN. This can only be used for healthcare, so is not SB. No others relevant. | none
AU Insurance Member Number |  Identifies an insurance member. Nothing relevant. |  none 
AU Local Dispense Identifier |   Identifies a dispensing. Nothing relevant. | none
AU Local Order Identifier   | FILL and PLAC are parents. FGN and PGN are not children of any parent | none  
AU Local Prescription Identifier | Could be a placer's or a filler's, not definitely PLAC or FILL, so is neither. Nothing else relevant. | none
AU Local Report Identifier |  Identifies a report. Nothing relevant. | none  
AU Location Specific Practice Number |  Identifies a site. Nothing relevant. |  none 
AU Medical Record Number |  MR is a parent. | none  
AU Medicare Card Number | This national, not state/province based so is not JHN. This may identify a set of 1 to 4 persons, so is not an SB. This identifies an entitlement, not a person, so is not SB. No others relevant. | none
AU Medicare Provider Number |  This is location and skill specific, so not a provider and thus not PRN. No others relevant. | none
AU NATA Accreditation Number | Identifies an approval or license, so not a provider and thus not PRN. No others relevant. | none
AU NATA Site Number |  Identifies a site. Nothing relevant.|   none
AU National Provider Identifier At Organisation | This is national, not local/jurisdictional, so not PRN. No others relevant. | none
AU PAI-D Identifier |   Not a UDI. No others relevant. | none
AU PAI-O Identifier | Not a provider and thus not PRN. No others relevant. | none
AU PBS Prescriber Number | Identifies an approval or license, so not a provider and thus not PRN. Not always  a medical doctor so not MD. No others relevant.| none
AU Pensioner Concession Card Number | This is national, not state/province based, so is not JHN. This identifies an entitlement, not a person, so is not SB. Nothing else relevant.| none
AU Pharmacy Approval Number | Identifies an approval or license, so not a provider and thus not PRN. Not a medical doctor so not MD. No others relevant. | none
AU Residential Aged Care Service Identifier | Identifies a service provided by a provider, so not a provider and thus not PRN. No others relevant. | none

**Comment by RichardTON** [comment]
_Originally posted by @oridashi in https://github.com/hl7au/au-fhir-base/issues/737#issuecomment-1212593785_

> * can we have narrative around AU Base IdentifierType being a non-hierarchal codesystem therefore we have specific codes defined for specific identifiers and will by choice chose an appropriate

As [IdentifierType CodeSystem](https://terminology.hl7.org/3.1.0/CodeSystem-v2-0203.html) is a V2 code system, there is no defined hierarchy to the values. (See comment by Ted Klein in [UP-331](https://jira.hl7.org/browse/UP-331).) This does not mean that there is no subsumption. (See resolution in [FHIR-37739](https://jira.hl7.org/browse/FHIR-37739).) None of the identifiers profiled above use codes subsumed by codes in [IdentifierType value set](http://hl7.org/fhir/valueset-identifier-type.html).

Subsumption will need to be assessed in future profiles of Identifier.

**Comment by RichardTON** [comment]
AU Accession Number problem moved to #748

**Comment by oridashi** [comment]
Need a narrative statement that 203 codesystem is NOT hierachial - leave ACSN and LACSN are not related.

**Comment by dt-r** [comment]
Fixed in commit https://github.com/hl7au/au-fhir-base/commit/910e04010d415b25cb350e502d4295974cbeddc7
