### ISSUE TITLE
AU Local Dispense Identifier - error in documentation

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#738]
In [AU Local Dispense Identifier](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-localdispenseidentifier.html) the definition is accurate 
> Local dispense identifier assigned by an organisation to a dispense record in that organisation's set of dispense records.

but the introductory part of the IG includes
> A local dispense identifier is an organisation’s identifier for a **prescription** in that organisation’s local system set of dispense records.

Which is clearly wrong.

**Comment by davidmckillop** [comment]
The text in the definition was corrected to align with the "AU Local dispense identifier.identifier" definition.

**Comment by davidmckillop** [comment]
Work has been done to correct this.

PR to follow.
