### ISSUE TITLE
Visual acuity measurement - create AU Base profile

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#739]
Child health records include measurements of visual acuity. 

Visual acuity is the ability to recognize small details with precision. The most common measurement of visual acuity assesses vision of stationary shapes on a standard chart at a distance in a good light.

Create an AU Base profile of Observation to support measurement of visual acuity in community and primary care in Australia.

**Comment by RichardTON** [comment]
Measurement of visual acuity is a very common observation of children and adults without a national model. It is worth modelling.

Distance visual acuity is measured at different distances in different parts of the world, e.g. 20 ft (USA), 6 m (Australia), 4 m, and 3 m. The numeric part of the distance is the numerator when visual acuity is expressed as a ratio, e.g. the 6 in 6/12. The denominator is the distance at which a person with standard or normal vision would see the same line. So 6/12 means that the tested vision at 6 m sees what is normal for 12 m, the vision is poor. 6/5 means that the tested vision at 6 m sees what is normal for 5 m, the vision is good. Scores are freely converted e.g. from 3/6 or 20/40 to 6/12, with 6/x being normal in Australia.0

There are many ways of measuring and recording distance visual acuity. The most common method in Australia is with a chart recording values as vulgar fractions, possibly with annotations and as codes for low vision. In parts of Europe visual acuity is recorded as a decimal with the measuring distance a separate element. Researchers often record visual acuity as the decadic logarithm of the minimum angle of resolution measured in minutes of arc, called LogMAR.

The testing chart has standard lines annotated with the value for vision of that line at the standard distance, e.g. 6/9.

In Australia the standard testing distance is 6 m.

A distance visual acuity test is a set of tests (typically from 3 to 12 in number) involving right eye, left eye, both eyes, with and without corrective lenses, and with and without a pinhole occluder. 

Near visual acuity is measured at a person's usual reading or working distance ( usually 30 to 40cm) using a chart with scores noted for each block. The most common scores in Australia are in N-notation (n-point), the letter N followed by an integer (though decimals are occasionally used). The integer is the [point size](https://en.wikipedia.org/wiki/Point_(typography)) for the text, in an agreed font. Testing near vision typically involves 3 to 6 tests: right eye, left eye, both eyes, with and without corrective lenses.

**Comment by brettesler-ext** [comment]
F2F comment - needs specific clinical IG propose hold waiting for appropriate project

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
