### ISSUE TITLE
Low visual acuity - valueset

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#740]
Create a valueset of SNOMED CT concepts that represent findings of different grades of low vision visual acuity. This will be used to represent the results of some measurements of visual acuity.

Low vision visual acuity codes are often used when the vision is worse than 6/60.

**Comment by RichardTON** [comment]
**Suggested title:** Low visual acuity result

**Suggested description:** The Low visual acuity result value set includes values that may be used to indicate the low vision result of a visual acuity measurement.

**Suggested URI:** https://healthterminologies.gov.au/fhir/ValueSet/low-visual-acuity-result-1

**Compose requirements:** Made up of the SNOMED CT concepts with the following preferred terms:
- Counts fingers - distance vision
- Sees hand movements
- Perceives light only
- Visual acuity, no light perception

Do not include any children of these concepts.

**Comment by brettesler-ext** [comment]
F2F comment - needs specific clinical IG propose hold waiting for appropriate project

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
