### ISSUE TITLE
Visual acuity measurement type - valueset

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#741]
Create a valueset of SNOMED CT concepts that represent types of visual acuity measurement. This will be used to represent the type of measurements of visual acuity.

**Comment by RichardTON** [comment]
**Suggested title:** Visual acuity measurement type

**Suggested description:** The Visual acuity measurement type value set includes values that may be used to indicate the type of a visual acuity measurement.

**Suggested URI:** https://healthterminologies.gov.au/fhir/ValueSet/visual-acuity-measurement-type-1

**Compose requirements:** TBD

**Comment by RichardTON** [comment]
The codes are chosen to support the following requirements
- identify the various types of visual acuity measurement in common use in Australia
- minimise the number of codes
- minimise use of multiple codings for the one concept
- avoid using predefined post-coordinated terms

FHIR Observation has suitable elements to move the following information out of Observation.code
- eyes: use bodySite
- test method: use method
- chart type: use device.resolve().type
So, eyes tested will be recorded in Observation.bodySite and not in Observation.code.

**Comment by brettesler-ext** [comment]
F2F comment - needs specific clinical IG propose hold waiting for appropriate project

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
