### ISSUE TITLE
Include the current terminology for Reason Vaccine Not Administered

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#745]
The existing preferred Australian set is outdated and includes inactive concepts. The latest value set should be included (published last month).

Please update the binding of Reason Vaccine Not Administered value set on Immunization.statusReason from -1 to -3 in [AU Base Immunisation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-immunization.html).

```
<binding>
        <strength value="preferred"/>
        <valueSet value="https://healthterminologies.gov.au/fhir/ValueSet/reason-vaccine-not-administered-3"/>
</binding>
```

**Comment by davidmckillop** [comment]
Work has been done to update the binding of Reason Vaccine Not Administered value set on Immunization.statusReason from -1 to -3 in [AU Base Immunisation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-immunization.html).

PR to follow.
