### ISSUE TITLE
Profile AU Accession Number should not mention LACSN

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#748]
The profile [AU Accession Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-accessionnumber.html) requires the use of one of two values for Identifier.type: ACSN and LACSN from http://terminology.hl7.org/CodeSystem/v2-0203.

ACSN subsumes LACSN (See [FHIR-37739](https://jira.hl7.org/browse/FHIR-37739)) and is in the value set [IdentifierType](http://hl7.org/fhir/R4/valueset-identifier-type.html). So, for laboratory accession numbers ACSN would be the appropriate code to send and LACSN could also be sent if desired. 

I suggest that LACSN be removed from the list of values for Identifier.type in  [AU Accession Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-accessionnumber.html). Its correct use is complex and it offers little value.

**Comment by oridashi** [comment]
Will leave LACSN code in the valueset; and need to explicitly add narrative defining the codesystem in NOT hierarchial

**Comment by dt-r** [comment]
Fixed in commit https://github.com/hl7au/au-fhir-base/commit/910e04010d415b25cb350e502d4295974cbeddc7
