### ISSUE TITLE
Eye - valueset

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#750]
Create a valueset of SNOMED CT concepts that represent the eyes; right, left and both. This will be used to represent the eyes involved in a measurement of  visual acuity.

**Comment by RichardTON** [comment]
Suggested title: Eye

Suggested description: The Eye value set includes values that may be used to indicate an eye or both eyes.

Suggested URI: https://healthterminologies.gov.au/fhir/ValueSet/eye-1

Compose requirements:
The codes shall identify right eye, left eye and both eyes.

Suggested codes, from SNOMED CT

- |Entire right eye|362502000
- |Entire left eye|362503005
- |Both eyes, entire|362508001

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
