### ISSUE TITLE
Adoption of Condition Category concept equivalent to US Core into AU Base

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#758]
From HL7 Australian Base FHIR Implementation Guide 4.1.0-ballot feedback: https://jira.hl7australia.com/browse/FHIRIG-216

Bringing in US Core dependency is not desirable; would like to have this concept defined in local codesystem and request an additional code from HL7 international. See https://build.fhir.org/ig/HL7/US-Core/CodeSystem-condition-category.html
Reporter:Brett Esler
Email:brett.esler@oridashi.com.au

The Agency also intended to raise the dependency on US core as an issue. Two other related issues noted:
- Condition.category is bound to the ValueSet 'Condition Category Codes - AU Extended' as preferred. Note that the core spec Condition.category element is bound to its ValueSet as extensible. The core spec profiling page (http://hl7.org/fhir/profiling.html#binding-strength) regarding 'Changing Binding Strength in Profiles' states that a base binding of extensible cannot be changed to preferred in a derived profile. The binding strength in Au Condition needs to be changed to extensible.
- The short name shows the two values included in the core spec ('problem-list-item | encounter-diagnosis') - new code to be added to short name.
Reporter: Jaymee Murdoch

**Comment by brettesler-ext** [comment]
F2F Comment - binding to Us Core was removed but not replaced with AU Valueset - propose we discuss and restore this as an extensible binding Condition.category to https://hl7.org.au/fhir/4.1.0-ballot/ValueSet-au-condition-category-extended.html

**Comment by dt-r** [comment]
I am happy to withdraw this GitHub. If the need arises for a specific project I will create a JIRA.
