### ISSUE TITLE
Adoption of Observation Category concept equivalent to US Core into AU Base

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#759]
From HL7 Australian Base FHIR Implementation Guide 4.1.0-ballot feedback: https://jira.hl7australia.com/browse/FHIRIG-217

Bringing in US Core dependency is not desirable; would like to have this concept defined in local codesystem and request an additional code from HL7 international. See https://build.fhir.org/ig/HL7/US-Core/ValueSet-us-core-category.html
Reporter:Brett Esler
Email:brett.esler@oridashi.com.au

The Agency was going to log this issue also.
Note the comment in QA report: A realm publication for au should not be depend on a realm specific guide from (US).
Consider creating an AU CodeSystem replicating the 'health-concern' code to remove the dependency to US Core.
Reporter: Jaymee Murdoch

**Comment by dt-r** [comment]
Note that an AU CodeSystem for Observation Category already exists.

**Comment by brettesler-ext** [comment]
F2F Comment - no binding to Valueset containing this code; code 'program' is used in https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-healthprogramparticipation.html - discuss AU base Observation (only) profile with terminology bindings for AU use

**Comment by dt-r** [comment]
I am happy to withdraw this GitHub. If the need arises for a specific project I will create a JIRA.
