### ISSUE TITLE
AU Base Healthcare Service: add binding to NCTS Common Languages in Australia

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#760]
The profile [AU Base Healthcare Service](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-healthcareservice.html) does not have an Australian specific binding for element `HealthcareService.communication`.

Recommend that a binding be added on this element to the NCTS ValueSet https://healthterminologies.gov.au/fhir/ValueSet/common-languages-australia-2 as extensible, as is found in [AU Base Patient](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-patient.html) and [AU Base Practitioner](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitioner.html).

Downstream IGs, such as the PCA would make use of this in their derived profiles; eg [PCA Healthcare Service](https://pca.digitalhealth.gov.au/fhir/4.0/currentdraft/StructureDefinition-pca-healthcare-service.html)

**Comment by brettesler-ext** [comment]
F2F Comment - needs action review; ideally a common languages CodeSystem fragment + ValueSet for Australia authored - nominally this will NOT be published by NCTS at this time so need to consider source and management of this fragment.

**Comment by brettesler-ext** [comment]
Moved to Jira [FHIR-46322](https://jira.hl7.org/browse/FHIR-46322)
