### ISSUE TITLE
SPIA Pathology Reporting ValueSet could be improved

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#764]
Raised as ballot issue for 4.1.0: https://jira.hl7australia.com/browse/FHIRIG-208

In the AU Base Pathology Report Profile (http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-pathologyreport.html) the value set https://healthterminologies.gov.au/fhir/ValueSet/spia-pathology-reporting-1 does not cover report panels.
The value set https://healthterminologies.gov.au/fhir/ValueSet/spia-pathology-reporting-1 is made up of LOINC codes which is great for the observable values, but not good for report panels where the specific components are listed with the code.
The value set https://healthterminologies.gov.au/fhir/ValueSet/spia-pathology-reporting-1 does not contain codes for the most common reportable pathology tests such as Full Blood Count, Liver Functions tests, Urea & Electrolytes, Iron Studies, Coagulation Studies to name a few.
The value set needs to be expanded to include the SCT terms for the commonly reported panels that aren't accommodated in https://healthterminologies.gov.au/fhir/ValueSet/spia-pathology-reporting-1.
This has been flagged with the RCPA for attention.

BE: lets have a workshop on this

DTR: This needs to be provided to RCPA, in addition the Agency authors and maintains this content - HL7 AU standards should reflect the peak body content but are not the body that governs this content. This is not a meaningful avenue for requesting change for this content unless it is to propose a competing set of terminology definitions - not in scope of ballot.

**Comment by dt-r** [comment]
This needs to be provided to RCPA, in addition the Agency authors and maintains this content - HL7 AU standards should reflect the peak body content but are not the body that governs this content. This is not a meaningful avenue for requesting change for this content unless it is to propose a competing set of terminology definitions - not in scope of ballot.

**Comment by davidmckillop** [comment]
RCPA notified via email on the 16th Jan 2023.
