### ISSUE TITLE
Sex for Clinical use not represented in AU Base

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#766]
Related existing GitHub issue: https://github.com/hl7au/au-fhir-base/issues/321

Issue raised in 4.1.0 ballot: https://jira.hl7australia.com/browse/FHIRIG-220

https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-patient.html

Sex for Clinical Use (or equivalent) is not represented in AU Base. It is represented in AU Core, however this is low maturity. Suggest guidance in AU Base on where it can be found in core, or will it be represented in AU Base?
Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

**Comment by dt-r** [comment]
This issue looks like it should be subsumed by https://github.com/hl7au/au-fhir-base/issues/321

**Comment by dt-r** [comment]
Consideration on pre-adoption of international material. See meeting minutes from HL7 AU FHIR working group here: https://confluence.hl7australia.com/display/PA/2023-04-12+Minutes

**Comment by brettesler-ext** [comment]
F2F discussion -
*  this is use case specific application for sex for clinical user refer to TDGs
*  Valueset needs AU Base recommendation for appropriateness

**Comment by hl7auadmin** [comment]
eVote: this is now being reviewed and actioned by the AU Core TDG business; Propose close.

**Comment by brettesler-ext** [comment]
Closed as no longer relevant https://confluence.hl7.org/display/HAFWG/2024-04-10+FHIRWG+Meeting+Minutes
