### ISSUE TITLE
AllergyIntolerance requires guidance on negation

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#767]
Ballot issue from 4.1.0: https://jira.hl7australia.com/browse/FHIRIG-221

https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-allergyintolerance-definitions.html

The International R4 AllergyIntolerance resource .code element defines a valueset that includes negation codes
http://hl7.org/fhir/R4/allergyintolerance-definitions.html#AllergyIntolerance.code
The AU Base R4 resource makes no mention on how negation should | can be supported.
Suggest inclusion of guidance similar to core.
Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

DTR comment: There is no Australian specific guidance warranted. The material from the core specification is appropriate - the value set is in full compliance with core guidance on use of negation codes in AllergyInterolerance.code.

No change is needed or appropriate unless all profiles include a statement referring the reader to the resource material in the core specification.

**Comment by brettesler-ext** [comment]
F2F comment - this is AU Core TDG scoped business and agree with DTR re existing material.

**Comment by hl7auadmin** [comment]
eVote: no suggestion beyond what is already in FHIR specification; close as no change needed; AU Core TDG will review usage as part of it's use cases. Propose close,

**Comment by brettesler-ext** [comment]
Closed a no longer relevant
https://confluence.hl7.org/display/HAFWG/2024-04-10+FHIRWG+Meeting+Minutes
