### ISSUE TITLE
Anatomic Region of Interest ValueSet may require improvement

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#768]
Ballot issue from 4.1.0: https://jira.hl7australia.com/browse/FHIRIG-225

https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-imagingreport.html

DiagnosticImagingReport.category.coding:anatomicRegionOfInterest
valueset: https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/imaging-anatomic-region-of-interest-1 (contains 13 very high level anatomical region codes, e.g. Strucutre of head, Structure of neck, Structure of thorax ...)
Binding strength = preferred.

AnatomicRegionOfInterest is a tyical data element or data set used to describe the focal region for ultrasonic waves, or ionizing radiation source, or anatomic pathology to identify the tumour cell cluster of interest.
The site | region is much more specific - not merely a set of very high level anatomic sites as shown in the value set, see examples:
https://www.researchgate.net/figure/Anatomical-regions-of-interest-ROIs-and-abbreviated-regional-labels_tbl2_318304640 (table 4)
https://onlinelibrary.wiley.com/doi/10.1002/ca.23742 (Table 2)

Region of interest has a very specific clinical meaning, which is not represented in this ValueSet. Consider changing binding strength to example, or improve content of ValueSet.

Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

DTR comment: The Agency and Agency terminology SME is the source of the value set. Noting that this comment is directed towards a better value set for clinical use which is not the use in AU Base.

This value set is used to support cross enterprise system categoristion behaviours in a distributed environment as per https://github.com/AuDigitalHealth/ci-fhir-r4/issues/108.

This comment will be passed to the Agency to provide a response.

**Comment by dt-r** [comment]
I am happy for the Agency to design and propose a clinical use value set, and propose where it should be bound.

I do not support changing the system categorisation set to a clinical use set.

**Comment by brettesler-ext** [comment]
F2F comment - need better suggestion as to content or will close..

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
