### ISSUE TITLE
Artefacts that are Maturity Level 1 do not have examples

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#769]
Ballot comment from 4.1.0: https://jira.hl7australia.com/browse/FHIRIG-226

All artefacts with the Maturity Level 1 and higher should have at least one example that demonstrates their use.
Add examples for the following:
Profiles:

AU Base Diagnostic Report
AU Base Diagnostic Imaging Report
AU Base Pathology Report
AU Base Diagnostic Result
AU Base Diagnostic Imaging Result
Profiles on Data Types:

AU Accession Number
AU ETP Prescription Identifier
AU Local Report Identifier
AU Pharmacy Approval Number
Extensions:

Associated Healthcare Service
Medication Brand Name (added in commit https://github.com/hl7au/au-fhir-base/commit/8d15c78cc050265c8bb46d725aa2283ab5d5c564)
Medication Generic Drug Name (added in commit https://github.com/hl7au/au-fhir-base/commit/8d15c78cc050265c8bb46d725aa2283ab5d5c564)
Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

**Comment by brettesler-ext** [comment]
F2F comment: this is a good point... need to find owners for these... i.e. any implementers..

**Comment by brettesler-ext** [comment]
Moved to Jira, DEFERRED [FHIR-46326](https://jira.hl7.org/browse/FHIR-46326)
