### ISSUE TITLE
Suggest addition of ServiceRequest.focus extension to AU Diagnostic Request

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#770]
Raised as ballot issue for 4.1.0: https://jira.hl7australia.com/browse/FHIRIG-227

https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-diagnosticrequest.html

Suggest add ServiceRequest.focus extension

Use case: Support request for imaging request to determine tumour margins of surgical pathology specimen.
This use case is very common, especially in breast conserving surgeries for removal of breast tumours (https://www.nature.com/articles/s41598-021-83330-w).
Potential pre-adoption of R5 when available?
Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

**Comment by brettesler-ext** [comment]
F2F comment - suggest we get eRequesting TDG to consider need for this; and for support for this in R4

**Comment by brettesler-ext** [comment]
Moved to Jira [FHIR-46357 - Suggest addition of ServiceRequest.focus extension to AU Diagnostic Request](https://jira.hl7.org/browse/FHIR-46357)
