### ISSUE TITLE
Dosage.asNeeded[x] ValueSet of 'Clinical Finding' is broad and could be refined

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#771]
Ballot issue from 4.1.0: https://jira.hl7australia.com/browse/FHIRIG-228

https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-dosage.html

AU Base Dosage.asNeeded[x]
asNeededCodeableConcept value set (https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/clinical-finding-1) binding strength = preferred

The ValueSet includes a large number of values inappropriate for describing clinical condition justifications for 'as needed' medication administration.
Examples include |Able to clear mouth|, |Able to cope with pain|, |Able to empty washbasin| etc.
The ValueSet could be made more meaningful with clinically appropriate values.
Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

**Comment by dt-r** [comment]
I am happy for the Agency to design and suggest an improved value set.

**Comment by hl7auadmin** [comment]
eVote: this issue does not have a specific proposal to improve the valueset nor project to provide

**Comment by brettesler-ext** [comment]
Moved to HL7 Jira [FHIR-46305](https://jira.hl7.org/browse/FHIR-46305)
