### ISSUE TITLE
Vaccination Target Disease ValueSet could be improved

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#772]
Raised as ballot issue for 4.1.0: https://jira.hl7australia.com/browse/FHIRIG-229

https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-immunization.html

The Immunization.protocolApplied.targetDisease value set contains a large number of irrelevant codes | concepts, e.g. Abscess of Bartholin's gland, Abscess of right greater vestibular gland, Abscess of spinal cord caused by fungus ... etc

The ValueSet is defined as children of |Disease|, which includes diseases which are not the target of a vaccine as referenced in the title of the ValueSet 'Vaccination Target Disease'. This may be misleading.

Suggest improving the content of the ValueSet.
The list of vaccine targeted diseases in Australia are available on:
https://www.health.gov.au/topics/immunisation/when-to-get-vaccinated/national-immunisation-program-schedule. There would be additional content that is relevant for recording internationally.
Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

**Comment by dt-r** [comment]
I am happy for the Agency to design and suggest an improved value set.

**Comment by hl7auadmin** [comment]
eVote: this issue does not have a specific proposal to improve the valueset nor project to provide

**Comment by brettesler-ext** [comment]
Moved to HL7 Jira [FHIR-46304](https://jira.hl7.org/browse/FHIR-46304)
