### ISSUE TITLE
MedicationDispense.receiver should enable 'RelatedPerson'

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#773]
Raised as ballot issue for 4.1.0: https://jira.hl7australia.com/browse/FHIRIG-232

https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-medicationdispense.html

MedicationDispense.receiver - Reference (Patient | Practitioner)

The receiver should include RelatedPerson to address community dispense use cases.

Please consider also including Organization. In inpatient or hospital settings, except Schedule 8 drugs, medicines supplied are dispensed to designated wards or clinical units.

Noting that core R5 build uses RelatedPerson and Location.
Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

**Comment by brettesler-ext** [comment]
F2F comment - AU Base does not have anything to add; no constraint is added
1) any need to support any pre-adopts?
2) is Organization a valid target and should we raise this as Hl7.org ticket?

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
