### ISSUE TITLE
Add known identifier systems in Australia

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#775]
From HL7 Australian Base FHIR Implementation Guide ballot content found at https://hl7.org.au/fhir/4.1.0-ballot/, feedback https://jira.hl7australia.com/browse/FHIRIG-209

In support of the Australian localisation of the FHIR standard, AU Base should include a section that provides Known Identifier Systems in Australia, i.e. the Australian additions to what is listed in https://www.hl7.org/fhir/identifier-registry.html.

A starter set of identifier systems, defined by NamingSystem resources, was drafted in ADHA Core, see https://build.fhir.org/ig/AuDigitalHealth/ci-fhir-r4/namingsys.html. This material should be migrated to AU Base – which was the intention of that content when it was drafted to move into HL7 AU published materials.

Reporter:Danielle Tavares-Rixon
Email:danielle.tavares-rixon@csiro.au

**Comment by brettesler-ext** [comment]
F2F comment - want to revisit this discussion wrt the provisioning of HL7 AU namespace registry - would be good to discuss an initial scope of a project to publish naming system resources currently have
* existing related OID registry, for HL7 Australia members - consider allowing naming systems from members... 
* existing naming systems already implicitly defined in all HL7 AU IGs
* nselectronichealth (copy from agency);  discuss - this is a resource so can contain useful external content
*  consider private health insurer identifier namespaces

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
