### ISSUE TITLE
Different copyright statement on IG and profiles; update hyperlink text "HL7 Australia" 

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#776]
Two potential issues noted in editorial review for ballot 4.1.0: 
* the footer has "IG © 2017+" but the copyright statement in profiles is "...2018+" - does this matter? From DTR: no issue that they are inconsistent, one will run out sooner than other but no issue here.
* the hyperlink text "HL7 Australia" goes to the URL https://confluence.hl7australia.com/display/PA for Patient Admin Working Group. Maybe the more generic page https://hl7.com.au/ would be more suitable2017+IG 

HL7 Australia to advise if changes are required.

**Comment by dt-r** [comment]
The artefacts in a specification and a specification copyright may have different dates, this is perfectly acceptable and appropriate, there is no inherent conflict in what may appear to be an inconsistency.

**Comment by brettesler-ext** [comment]
F2F comment - related to https://github.com/hl7au/au-fhir-base/issues/777

**Comment by brettesler-ext** [comment]
fixed for all IGs FHIRWG policy
