### ISSUE TITLE
Is HL7 AU copyright required for terminology resources that are SNOMED only?

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#777]
Noted as part of editorial review of ballot 4.1.0.

Copyright for AMT Medicinal Product and Substances VS is SNOMED only. Is HL7 AU copyright also required given the artifact is published by HL7 AU?

**Comment by dt-r** [comment]
My 10 cents - if HL7 AU provides a policy on this topic it should be scoped to HL7 AU authored artefacts, not limited to terminology or limited to terminology that includes only SNOMED (e.g. no reason to exclude the HL7 AU authored MIMs CodeSystem resource etc.).

**Comment by brettesler-ext** [comment]
F2F comment - there is a review of HL7 AU IP and copyright mechanisms undertaken by the board; so there should be a more specific recommendation coming wrt general HL7 AU statements on all HL7 AU IGs

**Comment by brettesler-ext** [comment]
fixed for all IGs FHIRWG policy
