### ISSUE TITLE
Additional guidance required for AU Medicine List to prevent conflicting entries

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#778]
Issues identified in Ballot comments for 4.1.0:

1. https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-medlist.html (https://jira.hl7australia.com/browse/FHIRIG-230)

See below - there are two different structures to express changes, but there is no constraint or invariant statement to ensure that the information carried by the two structures do not conflict. Some descriptive guidance is suggested.

https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-medlist-definitions.html#key_List.entry.flag
List.entry.flag - definition: The flag allows the system constructing the list to indicate the role and significance of the item in the list
binding: The codes SHOULD be taken from Medicine Item Change

https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-medlist-definitions.html#key_List.entry.extension:changeDescription
Definition: Description of a change including the reason for change
Type: Extension(ChangeDescription) (Extension Type: string)

2. https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-medlist.html (https://jira.hl7australia.com/browse/FHIRIG-231)

See below - there are two ways to reference information about medicines at item level, and at list level. The two ValueSets have different codes and values, some are semantically similar but not equivalent, and some are different.
This creates potential for conflicting assertions, or confusion of how to represent.
Suggest harmonising the two ValueSets to remove conflicts, or provide additional descriptive guidance.

List.entry.item - Reference (AU Assertion No relevant finding (https://hl7.org.au/fhir/4.1.0-ballot/StructureDefinition-au-norelevantfinding.html))
Observation.value - value set: https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/assertion-of-absence-1 (no known current medicines, No vaccine administered during encounter)

List.entry.emptyReason - binding: http://hl7.org/fhir/R4/valueset-list-empty-reason.html (nil known, not asked, withheld, unavailable, not started, closed)
Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

**Comment by jaymeemurdoch** [comment]
Additional comment from Stephen Chu:

After further assessment of this issue, it is even more confusing as information about absence of information in the medication list appears in 3 separate places:
At the list level:
List.emptyReason 0..1 codeableConcept - valueset: http://hl7.org/fhir/R4/valueset-list-empty-reason.html, which includes 6 values (nil known, not asked, withheld, unavailable, not started, closed)
At the item level:
List.entry.item 1..1 Reference(AU Assertion of No Relevant Finding) - which includes 2 separate representations) https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-norelevantfinding.html
Observation.dataAbsentReason 0..1 CodeableConcept
Binding: https://healthterminologies.gov.au/fhir/ValueSet/assertion-of-absence-1 (extensible)

includes 6 values (which include: No know current medicines | no vaccine admin during encounter)
Note: "No vaccine admin during encounter" is not a good fit for medication list
Binding: http://hl7.org/fhir/R4/valueset-data-absent-reason.html (extensible)
includes 15 values
These multiple level duplications are highly undesirable.
It is highly unlikely that any amount of descriptive guidance will be able to address this issue adequately

Suggestions:
Option 1
There may be a need to support assertion of absence of data on individual medication list item, e.g. certain vaccine dose administration unknown, or certain vaccine dose was not administered.
To prevent confusion, an invariant should be included stating that if List.entry.item includes "AU Assertion of No Relevant Finding", then List.emptyReason should be prohibted
Option 2
(1) Consider remove from structure definition: List.item Reference(AU Assertion of No Relevant Finding)
(2) Refine | improve List.emptyReason valueset

**Comment by brettesler-ext** [comment]
F2F comment - this is a broader discussion perhaps than medicines list.  For medicines list need to harmonise with Active Script List work?  would be good to discuss the issue and splitting into separate issues as needed

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
