### ISSUE TITLE
Support for prescription type: PBS/Private/Authority

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#782]
ETP prescribing and prescription reporting analytics e.g. https://www.naps.org.au/ have a need to define prescription type. This is likely to need to be an extension

Is terminology support possible? expect values of PBS/Private/Authority

ETP FHIR extension is currently string, see https://fhir.medicationknowledge.com.au/0.2.0/StructureDefinition-script-type.html

AIHW related content is https://meteor.aihw.gov.au/content/601577

**Comment by dt-r** [comment]
See General Practitioner National Antimicrobial Prescribing Survey (NAPS) extension for Prescription Authority Type here: https://build.fhir.org/ig/aehrc/gp-naps-fhir/StructureDefinition-gp-naps-script-authority-type.html

**Comment by brettesler-ext** [comment]
F2F comment - see 
https://hl7.org.au/archive/fhirwg/MED20180725-Meeting_12353769.html : Medical Benefit Category
needs discussion wrt Coverage

**Comment by brettesler-ext** [comment]
on hold - https://confluence.hl7.org/display/HAFWG/Resources%3A+Past+Issues+for+Future+Consideration
