### ISSUE TITLE
Support for Veteran/Australian Defence Force (ADF) status

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#790]
Need to define how to support the exchange of veteran / Australian Defence Force (ADF) status.

AIHW related data element [Person—ADF veteran status, code N](https://meteor.aihw.gov.au/content/737931) and related value domain [Veteran status code N](https://meteor.aihw.gov.au/content/743004)

- Is any other terminology suitable? Other demographic content uses AIHW sets e.g. indigenous status.
- If we use the AIHW set, do we retain 9 for not stated/inadequately described or use "UNK" from DAR.

**Comment by dt-r** [comment]
Candidate extension and terminology for discussion in build branch. 

When agreed, the terminology should go into the NCTS pipeline (remove the valueset & codesystem files from the IG).

**Comment by dt-r** [comment]
Background information from MHR individual profile information to Veteran and Australian Defence Force Status from this page https://www.digitalhealth.gov.au/initiatives-and-programs/my-health-record/manage-your-record/profile-and-settings/view-and-update-profile-details

Values that an individual can choose from: 
- No, I have never served in the ADF
- Yes, and I have a DVA file number
- Yes, but I do not have a DVA file number
- Prefer not to answer

During FWG meeting this content was noted, the questionnaire content seems directed at entitlement support.

**Comment by dt-r** [comment]
Discussed in https://confluence.hl7australia.com/display/PA/2023-07-19+FWG+Minutes.  Adoption of extension with context of Patient & Person. Terminology to be submitted to NCTS.

**Comment by liambarnes** [comment]
NCTS GitHub issues now in the backlog as referenced above.

**Comment by dt-r** [comment]
@liambarnes, what's the timeframes on this?

**Comment by liambarnes** [comment]
> 

Targeting the next (September) NCTS release

**Comment by brettesler-ext** [comment]
@dt-r does this become a backlog AU Base task to add extension when terminology available? I the IG work allocated to anyone?

**Comment by dt-r** [comment]
@brettesler-ext, yes it does become that backlog AU Base task. I had my hand up for that as soon as the terminology is available.

**Comment by RichardTON** [comment]
The guide for use on the related METEOR page [Person—ADF veteran status, code N](https://meteor.aihw.gov.au/content/737931) says that two codes can apply to the same person at the same time.

Either we need to allow multiple values in the [extension](https://build.fhir.org/ig/hl7au/au-fhir-base/branches/veteran-status/StructureDefinition-veteran-status.html) or have compound values in the code system.

**Comment by mjosborne1** [comment]
New NCTS Codeset for ADF Veteran status and corresponding Valueset have been added to NCTS for next release.
