### ISSUE TITLE
Support for Health Insurer (private) identifier

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#791]
Need to define how to support unambiguous identification of a private health insurer that is registered in Australia. This requirement is to support ordering and billing. 

This requirement is surfaced from the Draft Diagnostic Requests work, see [Diagnostic Coverage Profile](http://build.fhir.org/ig/hl7au/draft-diagnostic-orders/branches/master/StructureDefinition-eorders-coverage.html).

The ATO set of ids is a candidate set of identifier values e.g. `HCF` or `NTF`. The set of ATO managed ids can be seen from the consumer site here: https://privatehealth.gov.au/dynamic/insurer

1. Is there another identifier in use for this besides ATO IDs?
1. To progress ATO ID, needs:
    1. Identifier profile in AU Base
    1. system url to be agreed - one of:
        1. ATO url
        1. HL7 AU url
        1. ADHA issued url

In the Coverage resource this identifier can be used in `Coverage.payor.identifier` and `Coverage.identifier.assigner` to identify the private health insurer. 

See example Coverage resource for private health insurance: [Coverage/private](https://build.fhir.org/ig/hl7au/au-fhir-base//Coverage-private.html). When an identifier type for private health insurers is defined this example can be updated.

_NOTE: Support is already present for a patient's individual private health insurance number._

**Comment by dt-r** [comment]
@davidmckillop, @robeastwood-agency, @dbojicic-agency - request input from Agency on defining this Identifier type.

**Comment by heathfrankel** [comment]
After further discussions with Sonic and Healius, it is understood that private insurance is actually used for Diagnostic Requests, this is more for theatre bookings. If private insurance covers the diagnostic service, the patient would self pay and then claim back through their private insurance. 

Therefore, I suggest we remove insuranemembernumber slice from the Diagnostic Coverage profile.
cc @gonatf @angusmillar 

Having said that, for theatre bookings Genie is currently using the ATO ids from https://privatehealth.gov.au/dynamic/insurer. Currently Genie uses the existing AU Insurance Member Number profile (http://hl7.org.au/fhir/4.1.0/StructureDefinition-au-insurancemembernumber.html) with a system url of 
`https://privatehealth.gov.au/insurer/{ATO ID}/member/memberid`
It would be good to have this defined in AU Core

**Comment by heathfrankel** [comment]
BTW, while we are looking at system urls for private insurance member number, we may want to consider a system URL for the private insurance organisation them selves. For example in Coverage Genie uses an Identifier in the Payor element rather than a reference. For example:

* payor
  * identifier
    * type = $v2-0203#NII
    * value = "BUP"
    * system = "https://privatehealth.gov.au/dynamic/insurer"

**Comment by dt-r** [comment]
This issue is looking at the payor identifier, i.e. the health insurer, not the private insurance member number.

**Comment by dbojicic-agency** [comment]
@dt-r, did a bit of a search around for any private health insurer identifiers other than the ones assigned by ATO. 
From what I found, ATO assigns private health insurer identifiers to 'complying' policies only (can be claimed in a tax return). 

Services Australia (SA) maintains a list of private health insurers: https://www.servicesaustralia.gov.au/private-health-insurers-functions-and-contact-details?context=22886#a1, with some differences noted differences between the ATO and the SA lists, e.g. Defence Health Limited ID "DHF"(SA) and "AHB" (ATO). 

Propose an ADHA-issued url for the (non-ATO) specific health insurer identifier in Australia:

**Proposed namespace**
http://ns.electronichealth.net.au/id/private-health-insurer-id
**Description**
This namespace is used for identifiers assigned to a private health insurers registered in Australia.
In OID-based systems use 1.2.36.1.2001.1005.xx (to be progressed within Agency)

**Comment by dt-r** [comment]
It looks like the suggestion is to not use the ATO list but to use the Services Australia list of identifiers. But @dbojicic-agency are they the same set of entities?

I'm not concerned with the IDs being different when there are two separate issuing entities - the real world entity is the same but there are two different identifiers that could be used?

In either case (ATO issued identifier, Services Australia issued identifier)  I think the URL needs to declare what it is. If it is the ATO list it should have something in the URL that states that. If it is the Services Australia list then the identifier URL should be clear on that.

**Comment by brettesler-ext** [comment]
From Timothy.Panoho@act.gov.au 
Private Health Insurer comments.

From an EMR perspective will always differ from the private companies and practice software and workflow will be fairly different.
I think that having a list / directory of private health insurers is good, the model for requesting this information (like HI Service for IHI validation) sounds like a process heavy workflow/activity but possibly resolves our data quality issues in software. Currently we get a manual file from Service Australia (made up of the Eclipse 3 acronym codes) we do not use ATO lists. We manually extract and upload into our Power Billing system (PBRC for Billing).
Discussing with the billing team another field that would benefit from this type of billing workflow is the validation of Medicare numbers.
The specific fields that we send to our billing systems include (NIB is a live company but I will not include PHI/PII) I think that the most valid component would be the Insurance Company and how to standardise:
Insurance Company
ID: NIB
Name: N.I.B. HEALTH FUNDS LTD.
Address: LOCKED BAG 2010 NEWCASTLE 2300
Phone: 02 4921 2428
Effective Dates
Plan Type: HealthFund /Insurer
Name of client (patient name)
Issured Relationship: Self
Policy numbers
Company Plan Code
Coverage Types
Verification Status

**Comment by brettesler-ext** [comment]
F2F comment - confirm plan for this item; would be good to confim services Australia plans to publish this list into the future

**Comment by brettesler-ext** [comment]
Moved to Jira [FHIR-46321](https://jira.hl7.org/browse/FHIR-46321)
