### ISSUE TITLE
Concession selfpay code for Coverage type to Diagnostic Requests

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-base#793]
As part of the AU Diagnostic Requests IG, we have identified the need to represent a billing (Coverage) type code of Concession, which in a nutshell is indicating that the patient will self pay, but do this at a reduced rate, usually equivalent to what Medicare would pay when bulkbilled.
The current coverage codes are http://build.fhir.org/ig/hl7au/draft-diagnostic-orders/branches/master/ValueSet-eorders-coverage-type.html where are mapped from commonly used request form terms as follows:

Private => pay
Bulk Billed => PUBLICPOL
DVA => VET

The other common used term is Concession used as described above, but there is no equivalent concept in the base value set http://hl7.org/fhir/R4/valueset-coverage-type.html.

In my opinion, this should be a sub-term of self, something like payconc.

**Comment by dt-r** [comment]
As per https://confluence.hl7australia.com/display/PA/2023-07-05+Minutes we will:
* propose to Financial Group for inclusion in HL7 terminology
* support AU code system - remove or deprecate if supported in HL7 terminology
