### ISSUE TITLE
Indigenous status is only applicable to patient

### ISSUE THREAD

**Issue by techintrorepo** [hl7au/au-fhir-base#794]
This is regarding the ‘indigenous status’. My client has a requirement to record the indigenous status of the father and mother of a child patient. I was aiming to use the ‘indigenous status’ extension (http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-indigenous-status.html ) under AU Base and apply that to build a RelatedPerson profile. However, I noticed that the context of the extension is bounded with ‘Patient’ only and the documentation also says it’s applies to Patient only. I was wondering if this extension can be made usable for RelatedPerson resource and may be for Person as well.

**Comment by davidmckillop** [comment]
To be discussed at the next HL7 AU working group teleconference on the 19th July with details [here](https://confluence.hl7australia.com/display/PA/2023-07-19+Minutes).
All interested parties are welcome to attend.
