### ISSUE TITLE
AU Base FamilyMemberHistory profile

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-base#797]
AU Base should have a FamilyMemberHistory profile with recommended terminology bindings e.g.

 **relationship from Genetic_Family_Member_ValueSet** 

ValueSet: Genetic_Family_Member_ValueSet
Id: geneticfamilymember
Title: "Genetic Family Member ValueSet"
Description: "Members of a family from a genetic perspective"
* ^url = "http://aehrc.com/ValueSet/geneticfamilymember"
* codes from system http://snomed.info/sct where constraint = "< 444148008"

 **condition.code from https://healthterminologies.gov.au/fhir/ValueSet/clinical-condition-1**

dataAbsentReason ??

**Comment by davidmckillop** [comment]
Hi @brettesler-ext,
FYI -  code "444148008" is no longer active with reason being "Nonconformance to editorial policy component".
Code "444148008" has been replaced by code "303071001" with FSN of "Person in the family (person)" which should serve your purpose.
Cheers
D. Mc

**Comment by mjosborne1** [comment]
My personal opinion is that when the Family Member History moves/copies over to AU Base from Primary Care Data modeling repo (https://github.com/aehrc/primary-care-data-technical/) the URL (^url) should change from aehrc.com to something under the HL7 umbrella - if that's terminology.hl7.org.au then that's totally fine.

**Comment by brettesler-ext** [comment]
F2F comment - discuss plans for this artefact; would like an FMM1 publication ready for future AUCDI + AU Core discussion - for FHIRWG proposal

**Comment by brettesler-ext** [comment]
Moved to Jira [FHIR-46316](https://jira.hl7.org/browse/FHIR-46316)
