### ISSUE TITLE
indicator-hypersensitivity-intolerance-to-substance-2 Valueset changed in latest SNOMED CT AU Release

### ISSUE THREAD

**Issue by mjosborne1** [hl7au/au-fhir-base#799]
The valueset 
[indicator-hypersensitivity-intolerance-to-substance-2 ](https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2)
changed in latest SNOMED CT AU Release due to an inactivated concept in the SNOMED CT International release.

The concept that has been inactivated in SNOMED is “418038007| Propensity to adverse reactions to substance” and has been replaced by “420134006| Propensity to adverse reaction”.
 
The affected part of the ValueSet codes for SNOMED concepts that are “Descendents of Propensity to adverse reactions to substance”.

**Comment by mjosborne1** [comment]
Closing this one, it's not an issue per-se with AU Base. We do need to raise it however as part of change management for Value sets with bindings in AU Base.

**Comment by dt-r** [comment]
I don't agree in general that this is an issue. The value set was designed this way intentionally to be able to pick up such changes.
