### ISSUE TITLE
Support for NDIS (National Disability Insurance Scheme) number

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#800]
Outcome from [2023-09-28 AU Core TDG Agenda/Minutes](https://confluence.hl7.org/pages/viewpage.action?pageId=184920587) is a request for NDIS identification number defined in AU Base enabling a standard defined use in FHIR.

NDIS identification number (sometimes called reference number) is a nine-digit number that is unique to an individual who is participating in the NDIS.

**Comment by brettesler-ext** [comment]
FHIRWG approves this to proceed with this as a discussion
allied health; GP 
assistive device prescriptions NDIS screen
use cases need to be reviewed is this a patient identifier and/or insurance number?

**Comment by blestab** [comment]
@brettesler-ext just wondering if this would be a good first issue for someone to start contributing? If so I am interested in learning and contributing.

**Comment by brettesler-ext** [comment]
F2F comment - requires a plan of action re developing this further

**Comment by brettesler-ext** [comment]
Moved to Jira [FHIR-46323](https://jira.hl7.org/browse/FHIR-46323)
