### ISSUE TITLE
Require improvement to Practitioner.qualification.identifier and how AHPRA is handled

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#801]
Outcome from [2023-09-28 AU Core TDG Agenda/Minutes](https://confluence.hl7.org/pages/viewpage.action?pageId=184920587). Practitioner.qualification.identifier in AU Base is poorly defined. How is this element used and how is AHPRA related to this. Is an AHPRA number really an identifier of the qualification itself?

AU Core TDG notes that the AHPRA extension definitions are absent and need to be provided to understand how to use this. Related to:

- https://github.com/hl7au/au-fhir-base/issues/736
- ballot issue [FHIRIG-172](https://jira.hl7australia.com/browse/FHIRIG-172) The extension AHPRA Profession Details is not conceptually defined 
- ballot issue [FHIRIG-173](https://jira.hl7australia.com/browse/FHIRIG-173) The extension AHPRA Registration Details is not conceptually defined
- [FHIRIG-240](https://jira.hl7australia.com/browse/FHIRIG-240) Why are Ahpra registration details and Ahpra profession details mutually exclusive concepts?

**Comment by dt-r** [comment]
@jakubsielewicz and @robeastwood-agency is this issue something you guys can look at? These extensions came from the PCA project. I'm not sure anyone outside of the Agency can address the conceptual definition issues with these extensions.

**Comment by brettesler-ext** [comment]
F2F Comment - needs discussion for next steps

**Comment by robeastwood-agency** [comment]
I have requested input from the PCA project team re the interest to take this on

**Comment by brettesler-ext** [comment]
Moved to Jira [FHIR-46320](https://jira.hl7.org/browse/FHIR-46320)
