### ISSUE TITLE
Consider supporting as property of identifier: name used in identifier lookup

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#802]
Outcome from [2023-09-28 AU Core TDG Agenda/Minutes](https://confluence.hl7.org/pages/viewpage.action?pageId=184920587).

Consider supporting as a property of identifier the name used in identifier lookup. This would be official name associated with an identifier. Similar to other extensions on AU Base like IHI verified date. 

This item is considered a property of an identifier; official name as defined in registries can differ between registries. 

This item is raised in AU Base for consideration on use and relevance. This item is relevant to patient identifiers and provider identifiers.

**Comment by grahamegrieve** [comment]
I think this is a property of the IHI, not a flag on a particular name

**Comment by dt-r** [comment]
Agreed. That what what I mean to raise. I'll clarify the issue.

**Comment by angusmillar** [comment]
Would this also need to consider 'Date Of Birth' and 'Sex', given they are mandatory elements of an IHI search?  Address searches for IHIs are also possible, though uncommon, that said we do them at Sonic. 

Furthermore, the sex values for IHI searches (F: Female, M: Male, N: Not stated/inadequately described, I: Intersex or indeterminate) are inconsistent with the FHIR's Patient.gender values (F: Female, M: Male, O: Other, U: Unknown)

**Comment by angusmillar** [comment]
This was discussed in today's FHIRWG meeting and the group was leaning back towards an extension on Patient.name's HumanName to indicate a name instance is related to an Identifier of a particular identifier system. (i.e. the IHI's system)
There was concern regarding the IHI name diverging from the currently recorded patient name. This led to the notation of keeping them all in one place.

**Comment by brettesler-ext** [comment]
F2F comment - see branch https://build.fhir.org/ig/hl7au/au-fhir-base/branches/individual-name-context/StructureDefinition-individual-name-context.html for FWG review and approval on approach

**Comment by brettesler-ext** [comment]
Transferred to JIRA - https://jira.hl7.org/browse/FHIR-45980
