### ISSUE TITLE
IdentifierType AU CodeSystem - incorrect definition for code 'VDI'

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#808]
[IdentifierType AU CodeSystem](https://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-v2-0203.html) 

In the context of discussing a fix for a AU PD issue (https://github.com/hl7au/au-fhir-pd/issues/45) it was noticed by @brettesler-ext and @jakubsielewicz that the definition for the code `VDI` (Vendor Directory Identifier) is incorrect.

Currently the definition is:
> A unique vendor identifier allocated to a provider directory entry (PractitionerRole or HealthcareService), _typically used for routing secure messages_.

Actually VDI should not be used for routing, therefore the recommendation is that the definition be simplified to:
> A unique vendor identifier allocated to a provider directory entry (PractitionerRole or HealthcareService).

**Comment by dt-r** [comment]
@robeastwood-agency, agree this is a typographical error. Are you happy to fix?

**Comment by robeastwood-agency** [comment]
@dt-r - yes we are happy to address and will be (sorry for the delay in responding)

**Comment by brettesler-ext** [comment]
F2F disposition - agree and for a approval

**Comment by robeastwood-agency** [comment]
A PR for this is underway

**Comment by robeastwood-agency** [comment]
A PR is now available for consideration
