### ISSUE TITLE
Use international extension for timezone

### ISSUE THREAD

**Issue by lmckenzi** [hl7au/au-fhir-base#811]
The au base guide defines http://hl7.org.au/fhir/StructureDefinition/au-timezone|4.1.1
However, there's already a standard extension http://hl7.org/fhir/StructureDefinition/timezone|1.0.0 which seems to serve the same purpose and should be used instead

**Comment by brettesler-ext** [comment]
[FHIR-46319](https://jira.hl7.org/browse/FHIR-46319)
