### ISSUE TITLE
Guidance page needed on HL7 AU Stds in particular AU Base and relationship with other AU Stds

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-base#820]
We need to put into the IGs the explanation and diagrams on HL7 AU Standards and go into some more detail on AU Base.

There's a corresponding issue for AU Core https://github.com/hl7au/au-fhir-core/issues/91.

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43843](https://jira.hl7.org/browse/FHIR-43843).
